import type { SFX } from "../audio/legacy-synth";
import type { A11Y, CLOCK, CONFIG, GFX, OVERSCAN, REMOTE, SAFE, THEME } from "../config/game-config";
import type * as Geometry from "../domain/geometry";
import type * as Affixes from "../gameplay/affixes";
import type { createBlade } from "../gameplay/entities/blade";
import type { createEnemyTypes } from "../gameplay/entities/enemies";
import type { createMirrorTypes } from "../gameplay/entities/mirror";
import type { createPlayer } from "../gameplay/entities/player";
import type { createProjectile } from "../gameplay/entities/projectile";
import type { createAchievements } from "../gameplay/progression/achievements";
import type { createDailyChallenges } from "../gameplay/progression/challenges";
import type { createMetaProgression } from "../gameplay/progression/meta";
import type * as Stages from "../gameplay/stages";
import type * as Upgrades from "../gameplay/upgrades";
import type * as Variants from "../gameplay/variants";
import type { VoidGen } from "../gameplay/voidgen";
import type * as Weapons from "../gameplay/weapons";
import type { LegacyGamepad, LegacyInput } from "../input/legacy-input-contracts";
import type { createLegacyProfile } from "../persistence/legacy-profile";
import type { CloudFactory } from "../platform/cloud-factory";
import type { createLegacyPlatformCompatibility } from "../platform/legacy-compat";
import type { createRunSeed } from "../platform/run-seed";
import type { PwaUpdateCapability } from "../platform/pwa-update";
import type { createAttract } from "../presentation/attract";
import type { Backdrop } from "../presentation/backdrop";
import type { Cinematics } from "../presentation/cinematics";
import type { cosmeticRandom } from "../presentation/cosmetic-random";
import type { FX } from "../presentation/particles";
import type { createUi } from "../presentation/ui";
import type { createLegacyReplayCompatibility } from "../replay/legacy-compat";
import type { GAME_RANDOM } from "../simulation/run-random";
import type { PerformanceMonitor } from "../diagnostics/performance-monitor";
import type { LegacyAppStateController } from "./legacy-state-controller";

type EnemyTypes = ReturnType<typeof createEnemyTypes>;
type MirrorTypes = ReturnType<typeof createMirrorTypes>;
type Cloud = ReturnType<CloudFactory>;
type PlatformCompatibility = ReturnType<typeof createLegacyPlatformCompatibility>;
type ReplayCompatibility = ReturnType<typeof createLegacyReplayCompatibility>;

/** Inferred composition contract shared by the strict runtime host and platform composition root. */
export interface GameRuntimeDependencies {
  readonly A11Y: typeof A11Y; readonly ACH: ReturnType<typeof createAchievements>;
  readonly AFFIXES: typeof Affixes.AFFIXES; readonly APP: LegacyAppStateController;
  readonly Aldric: EnemyTypes["Aldric"]; readonly Armored: EnemyTypes["Armored"];
  readonly Attract: ReturnType<typeof createAttract>; readonly BOSSFX: EnemyTypes["BOSSFX"];
  readonly Backdrop: typeof Backdrop; readonly Blade: ReturnType<typeof createBlade>;
  readonly Bomber: EnemyTypes["Bomber"]; readonly Boss: EnemyTypes["Boss"];
  readonly CG: PlatformCompatibility["CG"]; readonly CLOCK: typeof CLOCK; readonly CONFIG: typeof CONFIG;
  readonly Charger: EnemyTypes["Charger"]; readonly Chimera: EnemyTypes["Chimera"];
  readonly Cinematics: typeof Cinematics; readonly Clipper: Readonly<{ start(): void; stop(): void }> | undefined;
  readonly Cloud: Cloud["Cloud"]; readonly Colossus: EnemyTypes["Colossus"];
  readonly DAILY: ReturnType<typeof createDailyChallenges>; readonly DIAG: PerformanceMonitor;
  readonly Echo: EnemyTypes["Echo"]; readonly FX: typeof FX; readonly FirebaseProvider: Cloud["FirebaseProvider"];
  readonly Flyer: EnemyTypes["Flyer"]; readonly GAME_RANDOM: typeof GAME_RANDOM; readonly GFX: typeof GFX;
  readonly GHOST: ReplayCompatibility["GHOST"]; readonly Input: LegacyInput;
  readonly META: ReturnType<typeof createMetaProgression>["META"]; readonly Mirror: MirrorTypes["Mirror"];
  readonly MirrorHost: MirrorTypes["MirrorHost"]; readonly OVERSCAN: typeof OVERSCAN;
  readonly PAD: LegacyGamepad; readonly PRESETS: typeof Affixes.PRESETS;
  readonly PROFILE: ReturnType<typeof createLegacyProfile>; readonly Player: ReturnType<typeof createPlayer>;
  readonly Projectile: ReturnType<typeof createProjectile>; readonly PwaUpdate: PwaUpdateCapability;
  readonly REMOTE: typeof REMOTE; readonly Ranged: EnemyTypes["Ranged"];
  readonly ReflectionEnemy: MirrorTypes["ReflectionEnemy"]; readonly SAFE: typeof SAFE; readonly SFX: typeof SFX;
  readonly SHOP: ReturnType<typeof createMetaProgression>["SHOP"]; readonly STAGES: typeof Stages.STAGES;
  readonly Source: EnemyTypes["Source"]; readonly Support: EnemyTypes["Support"]; readonly THEME: typeof THEME;
  readonly UI: ReturnType<typeof createUi>; readonly UPGRADES: typeof Upgrades.UPGRADES;
  readonly VAULT: ReplayCompatibility["VAULT"]; readonly VARIANTS: typeof Variants.VARIANTS;
  readonly VoidGen: typeof VoidGen; readonly VoidWisp: EnemyTypes["VoidWisp"];
  readonly WEAPONS: typeof Weapons.WEAPONS; readonly Warden: EnemyTypes["Warden"]; readonly Wraith: EnemyTypes["Wraith"];
  readonly aabbOverlap: typeof Geometry.aabbOverlap; readonly applyPreset: typeof Affixes.applyPreset;
  readonly applyUpgrade: typeof Upgrades.applyUpgrade; readonly applyVariant: typeof Variants.applyVariant;
  readonly applyWeapon: typeof Weapons.applyWeapon; readonly clamp: typeof Geometry.clamp;
  readonly cosmeticRandom: typeof cosmeticRandom; readonly createRunSeed: typeof createRunSeed;
  readonly drawBossTransformationWorld: EnemyTypes["drawBossTransformationWorld"];
  readonly len: typeof Geometry.len; readonly lerp: typeof Geometry.lerp; readonly newMods: typeof Upgrades.newMods;
  readonly nextTierDesc: typeof Upgrades.nextTierDesc; readonly rollAffixes: typeof Affixes.rollAffixes;
  readonly rollUpgrades: typeof Upgrades.rollUpgrades; readonly rollVariant: typeof Variants.rollVariant;
  readonly segCircle: typeof Geometry.segCircle; readonly segPointDist: typeof Geometry.segPointDist;
  readonly stageAt: typeof Stages.stageAt; readonly stagePlatforms: typeof Stages.stagePlatforms;
  readonly tierUp: typeof Upgrades.tierUp;
  readonly weaponCapsuleIntersectsSegment: EnemyTypes["weaponCapsuleIntersectsSegment"];
}
