import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import { TearFoundryDecisionExecutor } from "./foundry-job-decision";
import { parseTearFoundryBootstrapReceipt } from "./foundry-job-bootstrap";
import { parseTearFoundryEvaluationReadinessReceipt } from "./foundry-job-offline-training-finalization";
import { parseTearFoundryOnlineTrainingLaunch, parseTearFoundryPairedEvaluationReadinessReceipt } from "./foundry-job-online-training-launch";
import { parseTearFoundrySourceEvaluationPlanReceipt, parseTearFoundrySourceEvaluationReceipt } from "./foundry-job-source-evaluation-execution";
import { parseTearFoundryJob } from "./foundry-job-state";
import { concludeTearFoundryJobSchedule, rebindTearFoundryJobSchedule, type TearFoundryJobScheduleV1 } from "./foundry-job-schedule";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import { createTearFoundryExecutionBindingV4, parseTearFoundryExecutionBindingV4, type TearFoundryExecutionBindingV4 } from "./foundry-job-v4-offline-terminal";
import { parseTearFoundryV4OnlineLaunchAuthority, parseTearFoundryV4OnlineLaunchHandoffReceipt } from "./foundry-job-v4-online-launch-authority";
import { parseTearFoundryLaunchProfile } from "./foundry-launch-profile";
import { parseTearOnlineRlSourceEvaluationResult } from "./online-rl-source-evaluation";
import { stableVerificationHash } from "../replay/hash";

const BINDING = "foundry-job-execution-binding:v4:";
const POINTER = "foundry-job-execution-binding-current:v4:";
const guard = (key: string, expected: string | undefined): Readonly<{ store: "analysis"; key: string; expected?: string }> => Object.freeze({ store: "analysis" as const, key, ...(expected === undefined ? {} : { expected }) });
type DecisionPayload = Extract<TearFoundryExecutionBindingV4["payload"], Readonly<{ kind: "source-evaluation-decision-ready" }>>;
function payload(value: TearFoundryExecutionBindingV4["payload"]): DecisionPayload { if (value.kind === "source-evaluation-decision-ready") return value; throw new RangeError("Foundry V4 decision is not declared"); }

/** Consumes one immutable C34 result and atomically retains its non-promotional V2 decision. */
export class TearFoundryV4DecisionScheduler {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore) { if (jobs.backend() !== custody.backend()) throw new TypeError("Foundry V4 decision must share the C31 Vault boundary"); this.#jobs = jobs; this.#custody = custody; }
  async decide(schedule: TearFoundryJobScheduleV1, source: TearFoundryExecutionBindingV4, at: string): Promise<TearFoundryExecutionBindingV4> {
    const p = payload(source.payload), backend = this.#jobs.backend(), scheduleKey = `foundry-job-schedule:v1:${schedule.id}`, jobKey = `foundry-job:v1:${source.job.id}`, sourceKey = `${BINDING}${source.bindingHash}`, pointerKey = `${POINTER}${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`;
    if (!Number.isFinite(Date.parse(at)) || source.schedule.scheduleHash !== schedule.scheduleHash || source.job.phase !== "deciding") throw new RangeError("Foundry V4 decision declaration changed");
    const authorityKey = `foundry-job-v4-online-launch-authority:v1:${p.authorityHash}`, handoffKey = `foundry-job-v4-online-launch-handoff:v1:${p.handoffReceiptHash}`, launchKey = `foundry-job-online-training-launch:v1:${p.launchHash}`, pairedKey = `foundry-job-paired-evaluation-ready:v1:${p.pairedReadinessHash}`, planKey = `foundry-job-source-evaluation-plan:v1:${p.planReceiptHash}`, evaluationKey = `foundry-job-source-evaluation:v1:${p.evaluationReceiptHash}`;
    const [scheduleRaw, jobRaw, sourceRaw, pointerRaw, authorityRaw, handoffRaw, launchRaw, pairedRaw, planRaw, evaluationRaw] = await Promise.all([backend.get("analysis", scheduleKey), backend.get("analysis", jobKey), backend.get("analysis", sourceKey), backend.get("analysis", pointerKey), backend.get("analysis", authorityKey), backend.get("analysis", handoffKey), backend.get("analysis", launchKey), backend.get("analysis", pairedKey), backend.get("analysis", planKey), backend.get("analysis", evaluationKey)]);
    if ([scheduleRaw, jobRaw, sourceRaw, authorityRaw, handoffRaw, launchRaw, pairedRaw, planRaw, evaluationRaw].some((raw) => raw === undefined) || pointerRaw !== source.bindingHash || scheduleRaw !== JSON.stringify(schedule) || sourceRaw !== JSON.stringify(source)) throw new RangeError("Foundry V4 decision authority changed");
    let job; let authority; let handoff; let launch; let paired; let plan; let evaluation;
    try { job = parseTearFoundryJob(JSON.parse(jobRaw!)); authority = parseTearFoundryV4OnlineLaunchAuthority(JSON.parse(authorityRaw!)); handoff = parseTearFoundryV4OnlineLaunchHandoffReceipt(JSON.parse(handoffRaw!)); launch = parseTearFoundryOnlineTrainingLaunch(JSON.parse(launchRaw!)); paired = parseTearFoundryPairedEvaluationReadinessReceipt(JSON.parse(pairedRaw!)); plan = parseTearFoundrySourceEvaluationPlanReceipt(JSON.parse(planRaw!)); evaluation = parseTearFoundrySourceEvaluationReceipt(JSON.parse(evaluationRaw!)); } catch { throw new RangeError("Foundry V4 decision retained evidence is invalid"); }
    const readinessKey = `foundry-job-evaluation-ready:v1:${authority.readinessReceiptHash}`, profileKey = `foundry-launch-profile:v1:${authority.profile.id}`, declaredKey = `${BINDING}${authority.sourceBindingHash}`, resultKey = evaluation.resultHash === undefined ? undefined : `online-rl-source-evaluation:v1:${evaluation.resultHash}`;
    const [readinessRaw, profileRaw, declaredRaw, resultRaw, inventory, held] = await Promise.all([backend.get("analysis", readinessKey), backend.get("analysis", profileKey), backend.get("analysis", declaredKey), resultKey === undefined ? Promise.resolve(undefined) : backend.get("analysis", resultKey), this.#custody.inventory(), this.#custody.held(at)]);
    if (readinessRaw === undefined || profileRaw === undefined || declaredRaw === undefined || resultRaw === undefined || evaluation.disposition !== "executed" || evaluation.resultHash === undefined) throw new RangeError("Foundry V4 decision source result is unavailable");
    try { const readiness = parseTearFoundryEvaluationReadinessReceipt(JSON.parse(readinessRaw)), profile = parseTearFoundryLaunchProfile(JSON.parse(profileRaw)), declared = parseTearFoundryExecutionBindingV4(JSON.parse(declaredRaw)), result = parseTearOnlineRlSourceEvaluationResult(JSON.parse(resultRaw)); if (job.jobHash !== source.job.jobHash || authority.authorityHash !== p.authorityHash || handoff.receiptHash !== p.handoffReceiptHash || handoff.authorityHash !== authority.authorityHash || handoff.sourceBindingHash !== authority.sourceBindingHash || launch.launchHash !== p.launchHash || launch.readinessReceiptHash !== authority.readinessReceiptHash || paired.receiptHash !== p.pairedReadinessHash || paired.launchHash !== launch.launchHash || plan.receiptHash !== p.planReceiptHash || evaluation.receiptHash !== p.evaluationReceiptHash || evaluation.job.resultJobHash !== job.jobHash || evaluation.planReceiptHash !== plan.receiptHash || evaluation.planHash !== plan.planHash || result.resultHash !== evaluation.resultHash || result.planHash !== plan.planHash || readiness.receiptHashValue !== authority.readinessReceiptHash || profile.profileHash !== authority.profile.profileHash || declared.bindingHash !== authority.sourceBindingHash || declared.payload.kind !== "evaluation-ready" || declared.job.jobHash !== authority.job.jobHash || (await this.#jobs.get(job.id))?.jobHash !== job.jobHash) throw new Error("mismatch"); } catch { throw new RangeError("Foundry V4 decision lineage changed"); }
    const records = inventory.records.filter((record) => job.inputs.corpusRecordHashes.includes(record.recordHash)).sort((a, b) => a.candidateHash.localeCompare(b.candidateHash)); const custodyRaw = await Promise.all(records.map((record) => backend.get("analysis", `academy-candidate-custody:v1:${record.candidateHash}`)));
    let bootstrapKey: string | undefined; let bootstrapRaw: string | undefined;
    for (const key of (await backend.keys("analysis")).filter((key) => key.startsWith("foundry-job-bootstrap:v1:"))) { const raw = await backend.get("analysis", key); try { if (raw !== undefined && parseTearFoundryBootstrapReceipt(JSON.parse(raw)).receiptHash === authority.bootstrapReceiptHash) { bootstrapKey = key; bootstrapRaw = raw; break; } } catch { /* fail closed below */ } }
    if (bootstrapKey === undefined || bootstrapRaw === undefined || records.length !== job.inputs.corpusRecordHashes.length || custodyRaw.some((raw) => raw === undefined) || !job.inputs.corpusRecordHashes.every((hash) => held.some((record) => record.recordHash === hash)) || stableVerificationHash(records.map((record, index) => ({ candidateHash: record.candidateHash, recordHash: record.recordHash, raw: custodyRaw[index] }))) !== authority.custodyHash) throw new RangeError("Foundry V4 decision custody or bootstrap changed");
    let next: TearFoundryExecutionBindingV4 | undefined;
    let nextSchedule: TearFoundryJobScheduleV1 | undefined;
    const output = await new TearFoundryDecisionExecutor(this.#jobs).decide(job, p.evaluationReceiptHash, at, {
      guards: (complete) => {
        nextSchedule = complete.job.phase === "rejected" ? concludeTearFoundryJobSchedule(schedule, job, complete.job) : rebindTearFoundryJobSchedule(schedule, job, complete.job, at);
        next = createTearFoundryExecutionBindingV4({ schedule: { id: nextSchedule.id, revision: nextSchedule.revision, scheduleHash: nextSchedule.scheduleHash }, job: { id: complete.job.id, jobHash: complete.job.jobHash, phase: complete.job.phase }, payload: { kind: "decision-terminal", decisionReceiptHash: complete.receipt.receiptHash } });
        return Object.freeze([guard(scheduleKey, scheduleRaw), guard(jobKey, jobRaw), guard(sourceKey, sourceRaw), guard(pointerKey, source.bindingHash), guard(authorityKey, authorityRaw), guard(handoffKey, handoffRaw), guard(launchKey, launchRaw), guard(pairedKey, pairedRaw), guard(planKey, planRaw), guard(evaluationKey, evaluationRaw), guard(readinessKey, readinessRaw), guard(profileKey, profileRaw), guard(declaredKey, declaredRaw), guard(resultKey!, resultRaw), guard(bootstrapKey!, bootstrapRaw), guard(`${BINDING}${next.bindingHash}`, undefined), guard(`${POINTER}${next.schedule.id}:${String(next.schedule.revision)}:${next.schedule.scheduleHash}`, undefined), ...records.map((record, index) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, custodyRaw[index]))]);
      },
      writes: (complete) => {
        if (next === undefined || nextSchedule === undefined) throw new Error("Foundry V4 decision continuation disappeared");
        return Object.freeze([{ store: "analysis" as const, key: scheduleKey, value: JSON.stringify(nextSchedule) }, { store: "analysis" as const, key: `${BINDING}${next.bindingHash}`, value: JSON.stringify(next) }, { store: "analysis" as const, key: `${POINTER}${next.schedule.id}:${String(next.schedule.revision)}:${next.schedule.scheduleHash}`, value: next.bindingHash }, { store: "indexes" as const, key: `foundry-job-v4-decision:${complete.job.id}:${complete.receipt.receiptHash}`, value: JSON.stringify({ sourceBindingHash: source.bindingHash, disposition: complete.receipt.disposition, promotional: false, bindingHash: next.bindingHash }) }]);
      },
    });
    if (next === undefined || next.payload.kind !== "decision-terminal" || next.payload.decisionReceiptHash !== output.receipt.receiptHash) throw new Error("Foundry V4 decision continuation was not retained"); return next;
  }
}
