import { stableVerificationHash } from "../replay/hash";
import type { GhostVaultBackend } from "../ghost";
import type { TearFoundryExecutionBindingPayloadV1 } from "./foundry-job-execution-binding";
import type { TearFoundryJobPhase } from "./foundry-job-state";

const KEY = "foundry-job-successor-binding-material:v1:"; const HASH = /^[a-f0-9]{16}$/u;
export interface TearFoundrySuccessorExecutionBindingMaterialV1 { readonly format: "tear-foundry-successor-binding-material"; readonly schemaVersion: 1; readonly attemptReceiptHash: string; readonly sourceJobHash: string; readonly successor: Readonly<{ id: string; jobHash: string; phase: TearFoundryJobPhase }>; readonly payload: TearFoundryExecutionBindingPayloadV1; readonly materialHash: string; }
function hash(value: unknown): value is string { return typeof value === "string" && HASH.test(value); }
function payload(value: TearFoundryExecutionBindingPayloadV1, phase: TearFoundryJobPhase): TearFoundryExecutionBindingPayloadV1 { if (phase === "training" && value.kind === "offline-resume" && hash(value.launchHash)) return Object.freeze({ kind: "offline-resume", launchHash: value.launchHash }); throw new RangeError(`Foundry successor material does not declare the ${phase} phase`); }
function valid(value: TearFoundrySuccessorExecutionBindingMaterialV1): TearFoundrySuccessorExecutionBindingMaterialV1 { if (!hash(value.attemptReceiptHash) || !hash(value.sourceJobHash) || typeof value.successor.id !== "string" || !value.successor.id.trim() || !hash(value.successor.jobHash) || ["rejected", "rolled-back", "completed", "cancelled", "failed"].includes(value.successor.phase)) throw new TypeError("invalid Foundry successor binding material"); const frozen = Object.freeze({ format: "tear-foundry-successor-binding-material" as const, schemaVersion: 1 as const, attemptReceiptHash: value.attemptReceiptHash, sourceJobHash: value.sourceJobHash, successor: Object.freeze({ ...value.successor }), payload: payload(value.payload, value.successor.phase) }); const materialHash = stableVerificationHash(frozen); if (value.materialHash !== materialHash) throw new TypeError("Foundry successor binding material integrity mismatch"); return Object.freeze({ ...frozen, materialHash }); }
export function createTearFoundrySuccessorExecutionBindingMaterial(input: Omit<TearFoundrySuccessorExecutionBindingMaterialV1, "format" | "schemaVersion" | "materialHash">): TearFoundrySuccessorExecutionBindingMaterialV1 { const draft = { format: "tear-foundry-successor-binding-material" as const, schemaVersion: 1 as const, ...input }, materialHash = stableVerificationHash(draft); return valid({ ...draft, materialHash }); }
export function parseTearFoundrySuccessorExecutionBindingMaterial(value: unknown): TearFoundrySuccessorExecutionBindingMaterialV1 { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("invalid Foundry successor binding material"); return valid(value as TearFoundrySuccessorExecutionBindingMaterialV1); }
/** Immutable receipt-bound provenance only. It does not bind, schedule, or execute a successor. */
export class TearFoundrySuccessorExecutionBindingMaterialVault { readonly #backend: GhostVaultBackend; constructor(backend: GhostVaultBackend) { this.#backend = backend; } async persist(input: TearFoundrySuccessorExecutionBindingMaterialV1): Promise<TearFoundrySuccessorExecutionBindingMaterialV1> { const material = parseTearFoundrySuccessorExecutionBindingMaterial(input), key = `${KEY}${material.attemptReceiptHash}`, old = await this.#backend.get("analysis", key); if (old !== undefined) { try { const prior = parseTearFoundrySuccessorExecutionBindingMaterial(JSON.parse(old)); if (prior.materialHash === material.materialHash) return prior; } catch { await this.#backend.put("quarantine", key, old); await this.#backend.commit(Object.freeze([{ store: "analysis", key, value: JSON.stringify(material) }])); return material; } throw new RangeError("Foundry successor binding material already differs"); } await this.#backend.commit(Object.freeze([{ store: "analysis", key, value: JSON.stringify(material) }])); return material; } async get(attemptReceiptHash: string): Promise<TearFoundrySuccessorExecutionBindingMaterialV1 | undefined> { if (!hash(attemptReceiptHash)) throw new TypeError("Foundry successor binding receipt hash is invalid"); const key = `${KEY}${attemptReceiptHash}`, raw = await this.#backend.get("analysis", key); if (raw === undefined) return undefined; try { return parseTearFoundrySuccessorExecutionBindingMaterial(JSON.parse(raw)); } catch { await this.#backend.put("quarantine", key, raw); return undefined; } } }
