import { stableVerificationHash } from "../replay/hash";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import { parseTearFoundryBootstrapReceipt } from "./foundry-job-bootstrap";
import { parseTearFoundryEvaluationReadinessReceipt } from "./foundry-job-offline-training-finalization";
import { parseTearFoundryJob, type TearFoundryJobV1 } from "./foundry-job-state";
import { parseTearFoundryLaunchProfile } from "./foundry-launch-profile";
import { parseTearFoundryOnlineTrainingLaunch, TearFoundryOnlineTrainingFinalizationExecutor } from "./foundry-job-online-training-launch";
import { rebindTearFoundryJobSchedule, setTearFoundryJobScheduleEnabled, type TearFoundryJobScheduleV1 } from "./foundry-job-schedule";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import { createTearFoundryExecutionBindingV4, parseTearFoundryExecutionBindingV4, type TearFoundryExecutionBindingV4 } from "./foundry-job-v4-offline-terminal";
import { parseTearFoundryV4OnlineLaunchAuthority, parseTearFoundryV4OnlineLaunchHandoffReceipt } from "./foundry-job-v4-online-launch-authority";
import { TearOnlineRlCheckpointVault } from "./online-rl-training";

const HASH = /^[a-f0-9]{16}$/u, BINDING = "foundry-job-execution-binding:v4:", POINTER = "foundry-job-execution-binding-current:v4:";
const guard = (key: string, expected: string | undefined): Readonly<{ store: "analysis"; key: string; expected?: string }> => Object.freeze({ store: "analysis" as const, key, ...(expected === undefined ? {} : { expected }) });

interface Validated { readonly authorityRaw: string; readonly handoffRaw: string; readonly launchRaw: string; readonly profileRaw: string; readonly readinessRaw: string; readonly bootstrapKey: string; readonly bootstrapRaw: string; readonly scheduleRaw: string; readonly jobRaw: string; readonly sourceRaw: string; readonly pointerKey: string; readonly records: readonly Readonly<{ candidateHash: string; recordHash: string; raw: string }>[]; readonly job: TearFoundryJobV1; readonly checkpointHash: string; readonly checkpointRaw: string; }

/**
 * V4 terminal work is deliberately two wakes: a detector binds only the exact
 * named terminal C30 checkpoint, then finalization atomically retains its
 * result, legal successor, cadence, and (only for completion) paired-ready
 * pointer. It never evaluates, admits, or promotes a candidate.
 */
export class TearFoundryV4OnlineTerminalScheduler {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore) { if (jobs.backend() !== custody.backend()) throw new TypeError("Foundry V4 online terminal must share the C31 Vault boundary"); this.#jobs = jobs; this.#custody = custody; }
  async detect(schedule: TearFoundryJobScheduleV1, source: TearFoundryExecutionBindingV4, at: string): Promise<TearFoundryExecutionBindingV4 | undefined> {
    const checked = await this.#validate(schedule, source, at, "online-resume");
    if (checked === undefined) return undefined;
    const next = createTearFoundryExecutionBindingV4({ schedule: source.schedule, job: source.job, payload: { kind: "online-finalization", authorityHash: source.payload.authorityHash, handoffReceiptHash: source.payload.handoffReceiptHash, launchHash: source.payload.launchHash, checkpointHash: checked.checkpointHash } });
    const backend = this.#jobs.backend(), key = `${BINDING}${next.bindingHash}`;
    try { await backend.commitIfMatches(Object.freeze([guard(`foundry-job-schedule:v1:${schedule.id}`, checked.scheduleRaw), guard(`foundry-job:v1:${source.job.id}`, checked.jobRaw), guard(checked.pointerKey, source.bindingHash), guard(`${BINDING}${source.bindingHash}`, checked.sourceRaw), guard(key, undefined), guard(`foundry-job-v4-online-launch-authority:v1:${source.payload.authorityHash}`, checked.authorityRaw), guard(`foundry-job-v4-online-launch-handoff:v1:${source.payload.handoffReceiptHash}`, checked.handoffRaw), guard(`foundry-job-online-training-launch:v1:${source.payload.launchHash}`, checked.launchRaw), guard(`foundry-launch-profile:v1:${JSON.parse(checked.authorityRaw).profile.id}`, checked.profileRaw), guard(`foundry-job-evaluation-ready:v1:${JSON.parse(checked.authorityRaw).readinessReceiptHash}`, checked.readinessRaw), guard(checked.bootstrapKey, checked.bootstrapRaw), ...checked.records.map((record) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, record.raw))]), Object.freeze([{ store: "analysis", key, value: JSON.stringify(next) }, { store: "analysis", key: checked.pointerKey, value: next.bindingHash }])); } catch { throw new RangeError("Foundry V4 online terminal detection lost its authority"); }
    return next;
  }
  async finalize(schedule: TearFoundryJobScheduleV1, source: TearFoundryExecutionBindingV4, at: string): Promise<TearFoundryExecutionBindingV4 | undefined> {
    const checked = await this.#validate(schedule, source, at, "online-finalization"); if (checked === undefined) throw new RangeError("Foundry V4 online finalization checkpoint is running");
    const backend = this.#jobs.backend(), authority = parseTearFoundryV4OnlineLaunchAuthority(JSON.parse(checked.authorityRaw)), handoff = parseTearFoundryV4OnlineLaunchHandoffReceipt(JSON.parse(checked.handoffRaw));
    let nextBinding: TearFoundryExecutionBindingV4 | undefined; let nextSchedule: TearFoundryJobScheduleV1 | undefined;
    const result = await new TearFoundryOnlineTrainingFinalizationExecutor(this.#jobs).finalize(checked.job, parseTearFoundryEvaluationReadinessReceipt(JSON.parse(checked.readinessRaw)), source.payload.launchHash, at, {
      guards: (output) => { const stopped = output.receipt.disposition === "online-training-stopped"; nextSchedule = stopped ? setTearFoundryJobScheduleEnabled(schedule, false, at) : rebindTearFoundryJobSchedule(schedule, checked.job, output.job, at); if (!stopped) nextBinding = createTearFoundryExecutionBindingV4({ schedule: { id: nextSchedule.id, revision: nextSchedule.revision, scheduleHash: nextSchedule.scheduleHash }, job: { id: output.job.id, jobHash: output.job.jobHash, phase: output.job.phase }, payload: { kind: "evaluation-ready" } }); return Object.freeze([guard(`foundry-job-schedule:v1:${schedule.id}`, checked.scheduleRaw), guard(checked.pointerKey, source.bindingHash), guard(`${BINDING}${source.bindingHash}`, checked.sourceRaw), guard(`foundry-job-v4-online-launch-authority:v1:${authority.authorityHash}`, checked.authorityRaw), guard(`foundry-job-v4-online-launch-handoff:v1:${handoff.receiptHash}`, checked.handoffRaw), guard(`foundry-job-online-training-launch:v1:${source.payload.launchHash}`, checked.launchRaw), guard(`online-rl-checkpoint:v1:${source.payload.checkpointHash}`, checked.checkpointRaw), guard(`foundry-launch-profile:v1:${authority.profile.id}`, checked.profileRaw), guard(`foundry-job-evaluation-ready:v1:${authority.readinessReceiptHash}`, checked.readinessRaw), guard(checked.bootstrapKey, checked.bootstrapRaw), guard(`online-rl-training:v1:${output.result.resultHash}`, undefined), guard(`foundry-job-paired-evaluation-ready:v1:${output.receipt.receiptHash}`, undefined), ...(nextBinding === undefined ? [] : [guard(`${BINDING}${nextBinding.bindingHash}`, undefined), guard(`${POINTER}${nextSchedule.id}:${String(nextSchedule.revision)}:${nextSchedule.scheduleHash}`, undefined)]), ...checked.records.map((record) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, record.raw))]); },
      writes: (output) => {
        if (nextSchedule === undefined) throw new Error("Foundry V4 online terminal continuation disappeared");
        return Object.freeze([{ store: "analysis" as const, key: `foundry-job-schedule:v1:${schedule.id}`, value: JSON.stringify(nextSchedule) }, { store: "indexes" as const, key: `foundry-job-v4-online-terminal:${checked.job.id}:${output.receipt.receiptHash}`, value: JSON.stringify(Object.freeze({ disposition: output.receipt.disposition, checkpointHash: source.payload.checkpointHash, authorityHash: authority.authorityHash })) }, ...(nextBinding === undefined ? [] : [{ store: "analysis" as const, key: `${BINDING}${nextBinding.bindingHash}`, value: JSON.stringify(nextBinding) }, { store: "analysis" as const, key: `${POINTER}${nextSchedule.id}:${String(nextSchedule.revision)}:${nextSchedule.scheduleHash}`, value: nextBinding.bindingHash }])]);
      },
    });
    void result;
    return nextBinding;
  }
  async #validate(schedule: TearFoundryJobScheduleV1, source: TearFoundryExecutionBindingV4, at: string, kind: "online-resume" | "online-finalization"): Promise<Validated | undefined> {
    if (!Number.isFinite(Date.parse(at)) || source.payload.kind !== kind || source.schedule.scheduleHash !== schedule.scheduleHash || source.job.phase !== "evaluating") throw new RangeError("Foundry V4 online terminal is not exactly declared");
    const payload = source.payload, backend = this.#jobs.backend(), authorityKey = `foundry-job-v4-online-launch-authority:v1:${payload.authorityHash}`, handoffKey = `foundry-job-v4-online-launch-handoff:v1:${payload.handoffReceiptHash}`, launchKey = `foundry-job-online-training-launch:v1:${payload.launchHash}`, pointerKey = `${POINTER}${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`, sourceKey = `${BINDING}${source.bindingHash}`, scheduleKey = `foundry-job-schedule:v1:${schedule.id}`, jobKey = `foundry-job:v1:${source.job.id}`;
    const [authorityRaw, handoffRaw, launchRaw, pointerRaw, sourceRaw, scheduleRaw, jobRaw] = await Promise.all([backend.get("analysis", authorityKey), backend.get("analysis", handoffKey), backend.get("analysis", launchKey), backend.get("analysis", pointerKey), backend.get("analysis", sourceKey), backend.get("analysis", scheduleKey), backend.get("analysis", jobKey)]);
    if ([authorityRaw, handoffRaw, launchRaw, sourceRaw, scheduleRaw, jobRaw].some((v) => v === undefined) || pointerRaw !== source.bindingHash || sourceRaw !== JSON.stringify(source) || scheduleRaw !== JSON.stringify(schedule)) throw new RangeError("Foundry V4 online terminal source authority changed");
    let authority; let handoff; let launch; let job; try { authority = parseTearFoundryV4OnlineLaunchAuthority(JSON.parse(authorityRaw!)); handoff = parseTearFoundryV4OnlineLaunchHandoffReceipt(JSON.parse(handoffRaw!)); launch = parseTearFoundryOnlineTrainingLaunch(JSON.parse(launchRaw!)); job = parseTearFoundryJob(JSON.parse(jobRaw!)); } catch { throw new RangeError("Foundry V4 online terminal authority is invalid"); }
    if (authority.authorityHash !== payload.authorityHash || handoff.receiptHash !== payload.handoffReceiptHash || handoff.authorityHash !== authority.authorityHash || handoff.sourceBindingHash !== authority.sourceBindingHash || authority.schedule.id !== schedule.id || authority.job.id !== source.job.id || launch.launchHash !== payload.launchHash || launch.jobHash !== source.job.jobHash || launch.readinessReceiptHash !== authority.readinessReceiptHash || job.jobHash !== source.job.jobHash || (await this.#jobs.get(job.id))?.jobHash !== job.jobHash) throw new RangeError("Foundry V4 online terminal handoff changed");
    const declaredRaw = await backend.get("analysis", `${BINDING}${authority.sourceBindingHash}`); try { const declared = declaredRaw === undefined ? undefined : parseTearFoundryExecutionBindingV4(JSON.parse(declaredRaw)); if (declared?.bindingHash !== authority.sourceBindingHash || declared.payload.kind !== "evaluation-ready" || declared.job.id !== job.id || declared.job.jobHash !== authority.job.jobHash) throw new Error("mismatch"); } catch { throw new RangeError("Foundry V4 online terminal declared source changed"); }
    const profileKey = `foundry-launch-profile:v1:${authority.profile.id}`, readinessKey = `foundry-job-evaluation-ready:v1:${authority.readinessReceiptHash}`, [profileRaw, readinessRaw, held, inventory] = await Promise.all([backend.get("analysis", profileKey), backend.get("analysis", readinessKey), this.#custody.held(at), this.#custody.inventory()]);
    if (profileRaw === undefined || readinessRaw === undefined) throw new RangeError("Foundry V4 online terminal profile or readiness unavailable"); try { if (parseTearFoundryLaunchProfile(JSON.parse(profileRaw)).profileHash !== authority.profile.profileHash || parseTearFoundryEvaluationReadinessReceipt(JSON.parse(readinessRaw)).receiptHashValue !== authority.readinessReceiptHash) throw new Error("mismatch"); } catch { throw new RangeError("Foundry V4 online terminal retained authority changed"); }
    let bootstrapKey: string | undefined; let bootstrapRaw: string | undefined; for (const key of (await backend.keys("analysis")).filter((key) => key.startsWith("foundry-job-bootstrap:v1:"))) { const raw = await backend.get("analysis", key); try { if (raw !== undefined && parseTearFoundryBootstrapReceipt(JSON.parse(raw)).receiptHash === authority.bootstrapReceiptHash) { bootstrapKey = key; bootstrapRaw = raw; break; } } catch { /* invalid candidates cannot satisfy authority */ } }
    if (bootstrapKey === undefined || bootstrapRaw === undefined) throw new RangeError("Foundry V4 online terminal bootstrap changed");
    const records = inventory.records.filter((record) => job.inputs.corpusRecordHashes.includes(record.recordHash)).sort((a, b) => a.candidateHash.localeCompare(b.candidateHash));
    const raws = await Promise.all(records.map((record) => backend.get("analysis", `academy-candidate-custody:v1:${record.candidateHash}`)));
    const custodyHash = stableVerificationHash(records.map((record, index) => Object.freeze({ candidateHash: record.candidateHash, recordHash: record.recordHash, raw: raws[index] })));
    if (records.length !== job.inputs.corpusRecordHashes.length || raws.some((raw) => raw === undefined) || custodyHash !== authority.custodyHash || !job.inputs.corpusRecordHashes.every((hash) => held.some((record) => record.recordHash === hash))) throw new RangeError("Foundry V4 online terminal custody changed");
    const checkpointKey = `online-rl-checkpoint:v1:${launch.checkpointHash}`, checkpointRaw = await backend.get("analysis", checkpointKey), checkpoint = await new TearOnlineRlCheckpointVault(backend).get(launch.checkpointHash); if (checkpointRaw === undefined || checkpoint?.checkpointHash !== launch.checkpointHash) throw new RangeError("Foundry V4 online terminal checkpoint changed"); if (kind === "online-resume" && checkpoint.status === "running") return undefined; if (kind === "online-finalization" && (checkpoint.status === "running" || payload.checkpointHash !== checkpoint.checkpointHash)) throw new RangeError("Foundry V4 online terminal checkpoint changed");
    return Object.freeze({ authorityRaw: authorityRaw!, handoffRaw: handoffRaw!, launchRaw: launchRaw!, profileRaw, readinessRaw, bootstrapKey, bootstrapRaw, scheduleRaw: scheduleRaw!, jobRaw: jobRaw!, sourceRaw: sourceRaw!, pointerKey, records: Object.freeze(records.map((record, index) => Object.freeze({ candidateHash: record.candidateHash, recordHash: record.recordHash, raw: raws[index]! }))), job, checkpointHash: checkpoint.checkpointHash, checkpointRaw });
  }
}
