import { stableVerificationHash } from "../replay/hash";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import type { TearAcademyCorpusStore } from "./academy-corpus";
import type { TearAcademyTrainingDatasetLoader } from "./academy-training-dataset";
import { parseTearFoundryBootstrapReceipt } from "./foundry-job-bootstrap";
import { parseTearFoundryJob, type TearFoundryJobV1 } from "./foundry-job-state";
import { parseTearFoundryEvaluationReadinessReceipt } from "./foundry-job-offline-training-finalization";
import { parseTearFoundryOnlineTrainingLaunch, TearFoundryOnlineTrainingExecutionExecutor, type TearFoundryOnlineTrainingExecutionReceiptV1, type TearFoundryOnlineTrainingLaunchV1 } from "./foundry-job-online-training-launch";
import { parseTearFoundryLaunchProfile } from "./foundry-launch-profile";
import { rebindTearFoundryJobSchedule, type TearFoundryJobScheduleV1 } from "./foundry-job-schedule";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import { createTearFoundryExecutionBindingV4, parseTearFoundryExecutionBindingV4, type TearFoundryExecutionBindingV4 } from "./foundry-job-v4-offline-terminal";
import { parseTearFoundryV4OnlineLaunchAuthority, parseTearFoundryV4OnlineLaunchHandoffReceipt } from "./foundry-job-v4-online-launch-authority";
import type { TearOnlineRlCheckpointV1 } from "./online-rl-training";

const HASH = /^[a-f0-9]{16}$/u, BINDING = "foundry-job-execution-binding:v4:", POINTER = "foundry-job-execution-binding-current:v4:", CLAIM = "foundry-job-v4-online-execution-claim:v1:";
const guard = (key: string, expected: string | undefined): Readonly<{ store: "analysis"; key: string; expected?: string }> => Object.freeze({ store: "analysis" as const, key, ...(expected === undefined ? {} : { expected }) });
interface Claim { readonly format: "tear-foundry-v4-online-execution-claim"; readonly schemaVersion: 1; readonly authorityHash: string; readonly handoffReceiptHash: string; readonly sourceBindingHash: string; readonly launchHash: string; readonly claimedAt: string; readonly claimHash: string; }
type ExecutionOutput = Readonly<{ job: TearFoundryJobV1; launch: TearFoundryOnlineTrainingLaunchV1; receipt: TearFoundryOnlineTrainingExecutionReceiptV1; checkpoint: TearOnlineRlCheckpointV1 }>;
function claim(draft: Omit<Claim, "format" | "schemaVersion" | "claimHash">): Claim { if (![draft.authorityHash, draft.handoffReceiptHash, draft.sourceBindingHash, draft.launchHash].every((entry) => HASH.test(entry)) || !Number.isFinite(Date.parse(draft.claimedAt))) throw new TypeError("invalid Foundry V4 online execution claim"); const value = Object.freeze({ format: "tear-foundry-v4-online-execution-claim" as const, schemaVersion: 1 as const, ...draft }); return Object.freeze({ ...value, claimHash: stableVerificationHash(value) }); }
function parseClaim(value: unknown): Claim { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("invalid Foundry V4 online execution claim"); const source = value as Record<string, unknown>; if (source.format !== "tear-foundry-v4-online-execution-claim" || source.schemaVersion !== 1 || typeof source.claimHash !== "string" || !HASH.test(source.claimHash)) throw new TypeError("invalid Foundry V4 online execution claim"); const { claimHash, format, schemaVersion, ...draft } = source; void format; void schemaVersion; const parsed = claim(draft as Omit<Claim, "format" | "schemaVersion" | "claimHash">); if (parsed.claimHash !== claimHash) throw new TypeError("Foundry V4 online execution claim integrity mismatch"); return parsed; }

/**
 * The only scheduled consumer of a retained V4 online-resume binding. It
 * claims the exact authority/launch before C30 can advance, then retains one
 * successor launch and receipt. It never finalizes, evaluates, or routes a policy.
 */
export class TearFoundryV4OnlineExecutionScheduler {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore; readonly #corpus: TearAcademyCorpusStore; readonly #loader: TearAcademyTrainingDatasetLoader;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore, corpus: TearAcademyCorpusStore, loader: TearAcademyTrainingDatasetLoader) { if (jobs.backend() !== custody.backend() || jobs.backend() !== corpus.backend()) throw new TypeError("Foundry V4 online execution must share the C31 Vault boundary"); this.#jobs = jobs; this.#custody = custody; this.#corpus = corpus; this.#loader = loader; }
  async execute(schedule: TearFoundryJobScheduleV1, source: TearFoundryExecutionBindingV4, at: string): Promise<Readonly<{ schedule: TearFoundryJobScheduleV1; binding: TearFoundryExecutionBindingV4; launch: TearFoundryOnlineTrainingLaunchV1; receipt: TearFoundryOnlineTrainingExecutionReceiptV1 }>> {
    if (!Number.isFinite(Date.parse(at)) || source.payload.kind !== "online-resume" || source.schedule.scheduleHash !== schedule.scheduleHash || source.job.phase !== "evaluating") throw new RangeError("Foundry V4 online execution is not exactly declared");
    const backend = this.#jobs.backend(), authorityKey = `foundry-job-v4-online-launch-authority:v1:${source.payload.authorityHash}`, handoffKey = `foundry-job-v4-online-launch-handoff:v1:${source.payload.handoffReceiptHash}`, launchKey = `foundry-job-online-training-launch:v1:${source.payload.launchHash}`, claimKey = `${CLAIM}${source.payload.authorityHash}:${source.payload.launchHash}`, pointerKey = `${POINTER}${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`, sourceKey = `${BINDING}${source.bindingHash}`, scheduleKey = `foundry-job-schedule:v1:${schedule.id}`, jobKey = `foundry-job:v1:${source.job.id}`;
    const [authorityRaw, handoffRaw, launchRaw, pointerRaw, sourceRaw, scheduleRaw, jobRaw] = await Promise.all([backend.get("analysis", authorityKey), backend.get("analysis", handoffKey), backend.get("analysis", launchKey), backend.get("analysis", pointerKey), backend.get("analysis", sourceKey), backend.get("analysis", scheduleKey), backend.get("analysis", jobKey)]);
    if ([authorityRaw, handoffRaw, launchRaw, pointerRaw, sourceRaw, scheduleRaw, jobRaw].some((entry) => entry === undefined) || pointerRaw !== source.bindingHash || sourceRaw !== JSON.stringify(source) || scheduleRaw !== JSON.stringify(schedule)) throw new RangeError("Foundry V4 online execution source authority changed");
    let authority; let handoff; let launch; let job; try { authority = parseTearFoundryV4OnlineLaunchAuthority(JSON.parse(authorityRaw!)); handoff = parseTearFoundryV4OnlineLaunchHandoffReceipt(JSON.parse(handoffRaw!)); launch = parseTearFoundryOnlineTrainingLaunch(JSON.parse(launchRaw!)); job = parseTearFoundryJob(JSON.parse(jobRaw!)); } catch { throw new RangeError("Foundry V4 online execution authority is invalid"); }
    if (authority.authorityHash !== source.payload.authorityHash || handoff.receiptHash !== source.payload.handoffReceiptHash || handoff.authorityHash !== authority.authorityHash || handoff.sourceBindingHash !== authority.sourceBindingHash || authority.schedule.scheduleHash !== schedule.scheduleHash || authority.schedule.id !== schedule.id || authority.schedule.revision !== schedule.revision || authority.job.id !== source.job.id || authority.job.jobHash !== source.job.jobHash || launch.launchHash !== source.payload.launchHash || launch.jobHash !== source.job.jobHash || launch.readinessReceiptHash !== authority.readinessReceiptHash || (await this.#jobs.get(job.id))?.jobHash !== job.jobHash) throw new RangeError("Foundry V4 online execution handoff changed");
    const declaredRaw = await backend.get("analysis", `${BINDING}${authority.sourceBindingHash}`); try { const declared = declaredRaw === undefined ? undefined : parseTearFoundryExecutionBindingV4(JSON.parse(declaredRaw)); if (declared?.payload.kind !== "evaluation-ready" || declared.bindingHash !== authority.sourceBindingHash || declared.job.jobHash !== job.jobHash) throw new TypeError("mismatch"); } catch { throw new RangeError("Foundry V4 online execution declared source changed"); }
    const profileKey = `foundry-launch-profile:v1:${authority.profile.id}`, readinessKey = `foundry-job-evaluation-ready:v1:${authority.readinessReceiptHash}`, [profileRaw, readinessRaw, held, inventory] = await Promise.all([backend.get("analysis", profileKey), backend.get("analysis", readinessKey), this.#custody.held(at), this.#custody.inventory()]);
    if (profileRaw === undefined || readinessRaw === undefined) throw new RangeError("Foundry V4 online execution profile or readiness is unavailable"); let profile; let readiness; try { profile = parseTearFoundryLaunchProfile(JSON.parse(profileRaw)); readiness = parseTearFoundryEvaluationReadinessReceipt(JSON.parse(readinessRaw)); } catch { throw new RangeError("Foundry V4 online execution profile or readiness changed"); }
    if (profile.profileHash !== authority.profile.profileHash || profile.jobId !== job.id || readiness.receiptHashValue !== authority.readinessReceiptHash || readiness.job.resultJobHash !== job.jobHash) throw new RangeError("Foundry V4 online execution retained authority changed");
    const records = inventory.records.filter((record) => job.inputs.corpusRecordHashes.includes(record.recordHash)).sort((a, b) => a.candidateHash.localeCompare(b.candidateHash)), custodyRaw = await Promise.all(records.map((record) => backend.get("analysis", `academy-candidate-custody:v1:${record.candidateHash}`))), custodyHash = stableVerificationHash(records.map((record, index) => Object.freeze({ candidateHash: record.candidateHash, recordHash: record.recordHash, raw: custodyRaw[index] })));
    if (records.length !== job.inputs.corpusRecordHashes.length || custodyRaw.some((raw) => raw === undefined) || custodyHash !== authority.custodyHash || !job.inputs.corpusRecordHashes.every((hash) => held.some((record) => record.recordHash === hash))) throw new RangeError("Foundry V4 online execution custody changed");
    let bootstrapKey: string | undefined; let bootstrapRaw: string | undefined; for (const key of (await backend.keys("analysis")).filter((key) => key.startsWith("foundry-job-bootstrap:v1:"))) { const raw = await backend.get("analysis", key); try { if (raw !== undefined && parseTearFoundryBootstrapReceipt(JSON.parse(raw)).receiptHash === authority.bootstrapReceiptHash) { bootstrapKey = key; bootstrapRaw = raw; break; } } catch { if (raw !== undefined) await backend.put("quarantine", key, raw); } }
    if (bootstrapRaw === undefined || bootstrapKey === undefined) throw new RangeError("Foundry V4 online execution bootstrap changed");
    const desiredClaim = claim({ authorityHash: authority.authorityHash, handoffReceiptHash: handoff.receiptHash, sourceBindingHash: source.bindingHash, launchHash: launch.launchHash, claimedAt: authority.declaredAt }), priorClaim = await backend.get("analysis", claimKey);
    if (priorClaim !== undefined) { try { if (parseClaim(JSON.parse(priorClaim)).claimHash !== desiredClaim.claimHash) throw new TypeError("mismatch"); } catch { throw new RangeError("Foundry V4 online execution claim is invalid"); } } else { try { await backend.commitIfMatches(Object.freeze([guard(scheduleKey, scheduleRaw), guard(jobKey, jobRaw), guard(pointerKey, source.bindingHash), guard(sourceKey, sourceRaw), guard(authorityKey, authorityRaw), guard(handoffKey, handoffRaw), guard(launchKey, launchRaw), guard(profileKey, profileRaw), guard(readinessKey, readinessRaw), guard(bootstrapKey, bootstrapRaw), guard(claimKey, undefined), ...records.map((record, index) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, custodyRaw[index]))]), Object.freeze([{ store: "analysis", key: claimKey, value: JSON.stringify(desiredClaim) }])); } catch { throw new RangeError("Foundry V4 online execution lost its pre-execution authority"); } }
    let nextSchedule: TearFoundryJobScheduleV1 | undefined; let next: TearFoundryExecutionBindingV4 | undefined;
    const output = await new TearFoundryOnlineTrainingExecutionExecutor(this.#jobs, this.#custody, this.#corpus, this.#loader).execute(job, readiness, launch.launchHash, at, {}, Object.freeze({ guards: (result: ExecutionOutput) => { const rebound = rebindTearFoundryJobSchedule(schedule, job, result.job, at), binding = createTearFoundryExecutionBindingV4({ schedule: { id: rebound.id, revision: rebound.revision, scheduleHash: rebound.scheduleHash }, job: { id: result.job.id, jobHash: result.job.jobHash, phase: result.job.phase }, payload: { kind: "online-resume", authorityHash: authority.authorityHash, handoffReceiptHash: handoff.receiptHash, launchHash: result.launch.launchHash } }), nextKey = `${BINDING}${binding.bindingHash}`, nextPointer = `${POINTER}${rebound.id}:${String(rebound.revision)}:${rebound.scheduleHash}`; nextSchedule = rebound; next = binding; return Object.freeze([guard(scheduleKey, scheduleRaw), guard(pointerKey, source.bindingHash), guard(sourceKey, sourceRaw), guard(authorityKey, authorityRaw), guard(handoffKey, handoffRaw), guard(launchKey, launchRaw), guard(profileKey, profileRaw), guard(readinessKey, readinessRaw), guard(bootstrapKey!, bootstrapRaw), guard(claimKey, JSON.stringify(desiredClaim)), guard(`online-rl-checkpoint:v1:${result.checkpoint.checkpointHash}`, undefined), guard(nextKey, undefined), guard(nextPointer, undefined), ...records.map((record, index) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, custodyRaw[index]))]); }, writes: (result: ExecutionOutput) => { if (nextSchedule === undefined || next === undefined) throw new Error("Foundry V4 online execution continuation disappeared"); return Object.freeze([{ store: "analysis" as const, key: scheduleKey, value: JSON.stringify(nextSchedule) }, { store: "analysis" as const, key: `${BINDING}${next.bindingHash}`, value: JSON.stringify(next) }, { store: "analysis" as const, key: `${POINTER}${nextSchedule.id}:${String(nextSchedule.revision)}:${nextSchedule.scheduleHash}`, value: next.bindingHash }, { store: "indexes" as const, key: `foundry-job-v4-online-execution:${result.job.id}:${result.receipt.receiptHash}`, value: JSON.stringify(Object.freeze({ authorityHash: authority.authorityHash, launchHash: result.launch.launchHash, status: result.receipt.status })) }]); } })); if (nextSchedule === undefined || next === undefined) throw new Error("Foundry V4 online execution continuation was not retained"); return Object.freeze({ schedule: nextSchedule, binding: next, launch: output.launch, receipt: output.receipt });
  }
}
