import { stableVerificationHash } from "../replay/hash";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import { parseTearFoundryBootstrapReceipt, type TearFoundryBootstrapReceiptV1 } from "./foundry-job-bootstrap";
import { parseTearFoundryEvaluationReadinessReceipt, type TearFoundryEvaluationReadinessReceiptV1 } from "./foundry-job-offline-training-finalization";
import type { TearFoundryOnlineTrainingRequestV1 } from "./foundry-job-online-training-launch";
import { parseTearFoundryJob, type TearFoundryJobV1 } from "./foundry-job-state";
import { parseTearFoundryLaunchProfile, type TearFoundryLaunchProfileV1 } from "./foundry-launch-profile";
import type { TearFoundryJobScheduleV1 } from "./foundry-job-schedule";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import { createTearFoundryExecutionBindingV4, parseTearFoundryExecutionBindingV4, type TearFoundryExecutionBindingV4 } from "./foundry-job-v4-offline-terminal";

const AUTHORITY = "foundry-job-v4-online-launch-authority:v1:";
const RECEIPT = "foundry-job-v4-online-launch-handoff:v1:";
const BINDING = "foundry-job-execution-binding:v4:";
const POINTER = "foundry-job-execution-binding-current:v4:";
const HASH = /^[a-f0-9]{16}$/u;
type Identity = Readonly<{ id: string; revision: number; scheduleHash: string }>;
export interface TearFoundryV4OnlineLaunchAuthorityV1 { readonly format: "tear-foundry-v4-online-launch-authority"; readonly schemaVersion: 1; readonly profile: Readonly<{ id: string; profileHash: string }>; readonly bootstrapReceiptHash: string; readonly schedule: Identity; readonly job: Readonly<{ id: string; jobHash: string }>; readonly sourceBindingHash: string; readonly readinessReceiptHash: string; readonly custodyHash: string; readonly request: TearFoundryOnlineTrainingRequestV1; readonly declaredAt: string; readonly authorityHash: string; }
export interface TearFoundryV4OnlineLaunchHandoffReceiptV1 { readonly format: "tear-foundry-v4-online-launch-handoff"; readonly schemaVersion: 1; readonly authorityHash: string; readonly sourceBindingHash: string; readonly declaredAt: string; readonly receiptHash: string; }
export interface TearFoundryV4OnlineLaunchAuthorityRequestV1 { readonly profile: TearFoundryLaunchProfileV1; readonly bootstrap: TearFoundryBootstrapReceiptV1; readonly schedule: TearFoundryJobScheduleV1; readonly job: TearFoundryJobV1; readonly readiness: TearFoundryEvaluationReadinessReceiptV1; readonly request: TearFoundryOnlineTrainingRequestV1; readonly declaredAt: string; }
function time(value: unknown): value is string { return typeof value === "string" && Number.isFinite(Date.parse(value)); }
function text(value: unknown): value is string { return typeof value === "string" && value.trim().length > 0; }
function guard(key: string, expected: string | undefined): Readonly<{ store: "analysis"; key: string; expected?: string }> { return Object.freeze({ store: "analysis" as const, key, ...(expected === undefined ? {} : { expected }) }); }
function copyRequest(input: TearFoundryOnlineTrainingRequestV1): TearFoundryOnlineTrainingRequestV1 { try { const value: unknown = structuredClone(input); if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("invalid Foundry online request"); const copy = value as Record<string, unknown>; if (typeof copy.curriculum !== "object" || copy.curriculum === null || Array.isArray(copy.curriculum) || typeof copy.config !== "object" || copy.config === null || Array.isArray(copy.config)) throw new TypeError("invalid Foundry online request"); return Object.freeze(copy as unknown as TearFoundryOnlineTrainingRequestV1); } catch { throw new TypeError("invalid Foundry online request"); } }
function authority(draft: Omit<TearFoundryV4OnlineLaunchAuthorityV1, "format" | "schemaVersion" | "authorityHash">): TearFoundryV4OnlineLaunchAuthorityV1 { if (!text(draft.profile.id) || ![draft.profile.profileHash, draft.bootstrapReceiptHash, draft.schedule.scheduleHash, draft.job.jobHash, draft.sourceBindingHash, draft.readinessReceiptHash, draft.custodyHash].every((value) => HASH.test(value)) || !text(draft.job.id) || !Number.isSafeInteger(draft.schedule.revision) || draft.schedule.revision < 1 || !text(draft.schedule.id) || !time(draft.declaredAt)) throw new TypeError("invalid Foundry V4 online-launch authority"); const value = Object.freeze({ format: "tear-foundry-v4-online-launch-authority" as const, schemaVersion: 1 as const, profile: Object.freeze({ ...draft.profile }), bootstrapReceiptHash: draft.bootstrapReceiptHash, schedule: Object.freeze({ ...draft.schedule }), job: Object.freeze({ ...draft.job }), sourceBindingHash: draft.sourceBindingHash, readinessReceiptHash: draft.readinessReceiptHash, custodyHash: draft.custodyHash, request: copyRequest(draft.request), declaredAt: draft.declaredAt }); return Object.freeze({ ...value, authorityHash: stableVerificationHash(value) }); }
export function parseTearFoundryV4OnlineLaunchAuthority(value: unknown): TearFoundryV4OnlineLaunchAuthorityV1 { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("invalid Foundry V4 online-launch authority"); const source = value as Record<string, unknown>; if (source.format !== "tear-foundry-v4-online-launch-authority" || source.schemaVersion !== 1 || typeof source.authorityHash !== "string" || !HASH.test(source.authorityHash)) throw new TypeError("invalid Foundry V4 online-launch authority"); const { authorityHash, ...draft } = source, parsed = authority(draft as unknown as Omit<TearFoundryV4OnlineLaunchAuthorityV1, "format" | "schemaVersion" | "authorityHash">); if (authorityHash !== parsed.authorityHash) throw new TypeError("Foundry V4 online-launch authority integrity mismatch"); return parsed; }
function handoff(draft: Omit<TearFoundryV4OnlineLaunchHandoffReceiptV1, "receiptHash">): TearFoundryV4OnlineLaunchHandoffReceiptV1 { if (![draft.authorityHash, draft.sourceBindingHash].every((value) => HASH.test(value)) || !time(draft.declaredAt)) throw new TypeError("invalid Foundry V4 online-launch handoff"); const value = Object.freeze({ ...draft }); return Object.freeze({ ...value, receiptHash: stableVerificationHash(value) }); }
export function parseTearFoundryV4OnlineLaunchHandoffReceipt(value: unknown): TearFoundryV4OnlineLaunchHandoffReceiptV1 { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("invalid Foundry V4 online-launch handoff"); const source = value as TearFoundryV4OnlineLaunchHandoffReceiptV1, { receiptHash, ...draft } = source, parsed = handoff(draft); if (receiptHash !== parsed.receiptHash) throw new TypeError("Foundry V4 online-launch handoff integrity mismatch"); return parsed; }

/**
 * This is the only V4 boundary that may retain a full online-Q request. A
 * scheduler receives only its opaque authority and handoff hashes, never a
 * caller-supplied request. It deliberately creates no C30 checkpoint.
 */
export class TearFoundryV4OnlineLaunchAuthorityExecutor {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore) { if (jobs.backend() !== custody.backend()) throw new TypeError("Foundry V4 online authority must share the C31 Vault boundary"); this.#jobs = jobs; this.#custody = custody; }
  async declare(input: TearFoundryV4OnlineLaunchAuthorityRequestV1): Promise<Readonly<{ authority: TearFoundryV4OnlineLaunchAuthorityV1; binding: TearFoundryExecutionBindingV4; receipt: TearFoundryV4OnlineLaunchHandoffReceiptV1 }>> {
    const profile = parseTearFoundryLaunchProfile(input.profile), bootstrap = parseTearFoundryBootstrapReceipt(input.bootstrap), schedule = input.schedule, job = parseTearFoundryJob(input.job), readiness = parseTearFoundryEvaluationReadinessReceipt(input.readiness), backend = this.#jobs.backend();
    if (job.phase !== "evaluating" || schedule.jobId !== job.id || schedule.jobHash !== job.jobHash || bootstrap.jobHash === job.jobHash || bootstrap.scheduleHash !== schedule.scheduleHash || readiness.disposition !== "evaluation-ready" || readiness.job.id !== job.id || readiness.job.resultJobHash !== job.jobHash || !time(input.declaredAt)) throw new RangeError("Foundry V4 online authority requires exact post-bootstrap evaluation readiness");
    if (profile.jobId !== job.id || profile.manifest.manifestHash !== bootstrap.manifestHash || profile.manifest.rootHash !== bootstrap.manifestRootHash || profile.schedule.id !== schedule.id || profile.schedule.computeBudgetHash !== schedule.computeBudgetHash || profile.schedule.storageBudgetHash !== schedule.storageBudgetHash) throw new RangeError("Foundry V4 online authority profile no longer matches bootstrap");
    const sourcePointerKey = `${POINTER}${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`, sourceRaw = await backend.get("analysis", sourcePointerKey);
    if (sourceRaw === undefined || !HASH.test(sourceRaw)) throw new RangeError("Foundry V4 online authority has no current V4 binding");
    const sourceBindingRaw = await backend.get("analysis", `${BINDING}${sourceRaw}`); let source: TearFoundryExecutionBindingV4; try { source = sourceBindingRaw === undefined ? (() => { throw new TypeError("missing"); })() : parseTearFoundryExecutionBindingV4(JSON.parse(sourceBindingRaw)); } catch { throw new RangeError("Foundry V4 online authority current binding is invalid"); }
    if (source.payload.kind === "online-launch-ready") {
      const profileKey = `foundry-launch-profile:v1:${profile.id}`, readinessKey = `foundry-job-evaluation-ready:v1:${readiness.receiptHashValue}`, bootstrapKey = await this.#bootstrapKey((await backend.keys("analysis")).filter((key) => key.startsWith("foundry-job-bootstrap:v1:")), bootstrap), inventory = await this.#custody.inventory(), relevant = inventory.records.filter((record) => job.inputs.corpusRecordHashes.includes(record.recordHash)).sort((left, right) => left.candidateHash.localeCompare(right.candidateHash)), [authorityRaw, handoffRaw, profileRaw, readinessRaw, bootstrapRaw, held, ...custodyRaw] = await Promise.all([backend.get("analysis", `${AUTHORITY}${source.payload.authorityHash}`), backend.get("analysis", `${RECEIPT}${source.payload.handoffReceiptHash}`), backend.get("analysis", profileKey), backend.get("analysis", readinessKey), bootstrapKey === undefined ? Promise.resolve(undefined) : backend.get("analysis", bootstrapKey), this.#custody.held(input.declaredAt), ...relevant.map((record) => backend.get("analysis", `academy-candidate-custody:v1:${record.candidateHash}`))]);
      try { const prior = authorityRaw === undefined ? undefined : parseTearFoundryV4OnlineLaunchAuthority(JSON.parse(authorityRaw)), priorHandoff = handoffRaw === undefined ? undefined : parseTearFoundryV4OnlineLaunchHandoffReceipt(JSON.parse(handoffRaw)), custodyHash = stableVerificationHash(relevant.map((record, index) => Object.freeze({ candidateHash: record.candidateHash, recordHash: record.recordHash, raw: custodyRaw[index] }))); if (profileRaw === JSON.stringify(profile) && bootstrapRaw !== undefined && readinessRaw !== undefined && job.inputs.corpusRecordHashes.every((recordHash) => held.some((record) => record.recordHash === recordHash)) && prior?.profile.profileHash === profile.profileHash && prior.bootstrapReceiptHash === bootstrap.receiptHash && prior.schedule.scheduleHash === schedule.scheduleHash && prior.job.jobHash === job.jobHash && prior.readinessReceiptHash === readiness.receiptHashValue && prior.custodyHash === custodyHash && stableVerificationHash(prior.request) === stableVerificationHash(copyRequest(input.request)) && priorHandoff?.authorityHash === prior.authorityHash && priorHandoff.sourceBindingHash === prior.sourceBindingHash && source.payload.handoffReceiptHash === priorHandoff.receiptHash) return Object.freeze({ authority: prior, binding: source, receipt: priorHandoff }); } catch { /* fall through to fail closed */ }
      throw new RangeError("Foundry V4 online authority retry lost its immutable handoff");
    }
    if (source.payload.kind !== "evaluation-ready" || source.job.jobHash !== job.jobHash || source.schedule.scheduleHash !== schedule.scheduleHash || (await this.#jobs.get(job.id))?.jobHash !== job.jobHash) throw new RangeError("Foundry V4 online authority source binding changed");
    const profileKey = `foundry-launch-profile:v1:${profile.id}`, readinessKey = `foundry-job-evaluation-ready:v1:${readiness.receiptHashValue}`, bootstrapEntries = (await backend.keys("analysis")).filter((key) => key.startsWith("foundry-job-bootstrap:v1:"));
    const bootstrapKey = await this.#bootstrapKey(bootstrapEntries, bootstrap); if (bootstrapKey === undefined) throw new RangeError("Foundry V4 online authority bootstrap receipt is unavailable");
    const [profileRaw, readinessRaw, bootstrapRaw, held, inventory] = await Promise.all([backend.get("analysis", profileKey), backend.get("analysis", readinessKey), backend.get("analysis", bootstrapKey), this.#custody.held(input.declaredAt), this.#custody.inventory()]);
    if (profileRaw !== JSON.stringify(profile) || readinessRaw === undefined || bootstrapRaw === undefined || !job.inputs.corpusRecordHashes.every((recordHash) => held.some((record) => record.recordHash === recordHash))) throw new RangeError("Foundry V4 online authority profile, readiness, bootstrap, or custody changed");
    try { if (parseTearFoundryEvaluationReadinessReceipt(JSON.parse(readinessRaw)).receiptHashValue !== readiness.receiptHashValue || parseTearFoundryBootstrapReceipt(JSON.parse(bootstrapRaw)).receiptHash !== bootstrap.receiptHash) throw new TypeError("mismatch"); } catch { throw new RangeError("Foundry V4 online authority durable receipt changed"); }
    const relevant = inventory.records.filter((record) => job.inputs.corpusRecordHashes.includes(record.recordHash)).sort((left, right) => left.candidateHash.localeCompare(right.candidateHash)), custodyGuards = await Promise.all(relevant.map(async (record) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, await backend.get("analysis", `academy-candidate-custody:v1:${record.candidateHash}`))));
    if (custodyGuards.length !== job.inputs.corpusRecordHashes.length || custodyGuards.some((entry) => entry.expected === undefined)) throw new RangeError("Foundry V4 online authority custody bytes are unavailable");
    const record = authority({ profile: { id: profile.id, profileHash: profile.profileHash }, bootstrapReceiptHash: bootstrap.receiptHash, schedule: { id: schedule.id, revision: schedule.revision, scheduleHash: schedule.scheduleHash }, job: { id: job.id, jobHash: job.jobHash }, sourceBindingHash: source.bindingHash, readinessReceiptHash: readiness.receiptHashValue, custodyHash: stableVerificationHash(relevant.map((entry, index) => Object.freeze({ candidateHash: entry.candidateHash, recordHash: entry.recordHash, raw: custodyGuards[index]?.expected }))), request: input.request, declaredAt: input.declaredAt });
    const authorityKey = `${AUTHORITY}${record.authorityHash}`, receipt = handoff({ format: "tear-foundry-v4-online-launch-handoff", schemaVersion: 1, authorityHash: record.authorityHash, sourceBindingHash: source.bindingHash, declaredAt: input.declaredAt });
    const actualBinding = createTearFoundryExecutionBindingV4({ schedule: { id: schedule.id, revision: schedule.revision, scheduleHash: schedule.scheduleHash }, job: { id: job.id, jobHash: job.jobHash, phase: job.phase }, payload: { kind: "online-launch-ready", authorityHash: record.authorityHash, handoffReceiptHash: receipt.receiptHash } });
    const receiptKey = `${RECEIPT}${receipt.receiptHash}`, old = await backend.get("analysis", authorityKey);
    if (old !== undefined) { const prior = parseTearFoundryV4OnlineLaunchAuthority(JSON.parse(old)); const handoffRaw = await backend.get("analysis", receiptKey); if (prior.authorityHash === record.authorityHash && handoffRaw !== undefined && parseTearFoundryV4OnlineLaunchHandoffReceipt(JSON.parse(handoffRaw)).receiptHash === receipt.receiptHash && (await backend.get("analysis", `${POINTER}${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`)) === actualBinding.bindingHash) return Object.freeze({ authority: prior, binding: actualBinding, receipt }); throw new RangeError("Foundry V4 online authority retry lost its handoff"); }
    try { await backend.commitIfMatches(Object.freeze([guard(profileKey, profileRaw), guard(readinessKey, readinessRaw), guard(bootstrapKey, bootstrapRaw), guard(`foundry-job-schedule:v1:${schedule.id}`, JSON.stringify(schedule)), guard(`foundry-job:v1:${job.id}`, JSON.stringify(job)), guard(sourcePointerKey, source.bindingHash), guard(`${BINDING}${source.bindingHash}`, sourceBindingRaw), guard(authorityKey, undefined), guard(receiptKey, undefined), ...custodyGuards]), Object.freeze([{ store: "analysis", key: authorityKey, value: JSON.stringify(record) }, { store: "analysis", key: receiptKey, value: JSON.stringify(receipt) }, { store: "analysis", key: `${BINDING}${actualBinding.bindingHash}`, value: JSON.stringify(actualBinding) }, { store: "analysis", key: sourcePointerKey, value: actualBinding.bindingHash }, { store: "indexes", key: `foundry-job-v4-online-launch:${job.id}:${record.authorityHash}`, value: JSON.stringify(Object.freeze({ scheduleHash: schedule.scheduleHash, readinessReceiptHash: readiness.receiptHashValue, handoffReceiptHash: receipt.receiptHash })) }])); } catch { throw new RangeError("Foundry V4 online authority lost its bootstrap, profile, readiness, custody, or binding authority"); }
    return Object.freeze({ authority: record, binding: actualBinding, receipt });
  }
  async #bootstrapKey(keys: readonly string[], expected: TearFoundryBootstrapReceiptV1): Promise<string | undefined> { for (const key of keys) { const raw = await this.#jobs.backend().get("analysis", key); try { if (raw !== undefined && parseTearFoundryBootstrapReceipt(JSON.parse(raw)).receiptHash === expected.receiptHash) return key; } catch { if (raw !== undefined) await this.#jobs.backend().put("quarantine", key, raw); } } return undefined; }
}
