import { stableVerificationHash } from "../replay/hash";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import type { TearAcademyCorpusStore } from "./academy-corpus";
import type { TearAcademyTrainingDatasetLoader } from "./academy-training-dataset";
import { parseTearFoundryBootstrapReceipt } from "./foundry-job-bootstrap";
import { parseTearFoundryJob } from "./foundry-job-state";
import { parseTearFoundryEvaluationReadinessReceipt } from "./foundry-job-offline-training-finalization";
import { TearFoundryOnlineTrainingLaunchExecutor, parseTearFoundryOnlineTrainingLaunch, type TearFoundryOnlineTrainingLaunchV1 } from "./foundry-job-online-training-launch";
import { parseTearFoundryLaunchProfile } from "./foundry-launch-profile";
import type { TearFoundryJobScheduleV1 } from "./foundry-job-schedule";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import { createTearFoundryExecutionBindingV4, parseTearFoundryExecutionBindingV4, type TearFoundryExecutionBindingV4 } from "./foundry-job-v4-offline-terminal";
import { parseTearFoundryV4OnlineLaunchAuthority, parseTearFoundryV4OnlineLaunchHandoffReceipt } from "./foundry-job-v4-online-launch-authority";

const HASH = /^[a-f0-9]{16}$/u, BINDING = "foundry-job-execution-binding:v4:", POINTER = "foundry-job-execution-binding-current:v4:";
const CLAIM = "foundry-job-v4-online-launch-claim:v1:";
const guard = (key: string, expected: string | undefined): Readonly<{ store: "analysis"; key: string; expected?: string }> => Object.freeze({ store: "analysis" as const, key, ...(expected === undefined ? {} : { expected }) });
interface Claim { readonly format: "tear-foundry-v4-online-launch-claim"; readonly schemaVersion: 1; readonly authorityHash: string; readonly handoffReceiptHash: string; readonly sourceBindingHash: string; readonly claimedAt: string; readonly claimHash: string; }
function claim(draft: Omit<Claim, "format" | "schemaVersion" | "claimHash">): Claim { if (![draft.authorityHash, draft.handoffReceiptHash, draft.sourceBindingHash].every((entry) => HASH.test(entry)) || !Number.isFinite(Date.parse(draft.claimedAt))) throw new TypeError("invalid Foundry V4 online launch claim"); const value = Object.freeze({ format: "tear-foundry-v4-online-launch-claim" as const, schemaVersion: 1 as const, ...draft }); return Object.freeze({ ...value, claimHash: stableVerificationHash(value) }); }
function parseClaim(value: unknown): Claim { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("invalid Foundry V4 online launch claim"); const source = value as Record<string, unknown>; if (source.format !== "tear-foundry-v4-online-launch-claim" || source.schemaVersion !== 1 || typeof source.claimHash !== "string" || !HASH.test(source.claimHash)) throw new TypeError("invalid Foundry V4 online launch claim"); const { claimHash, format, schemaVersion, ...draft } = source; void format; void schemaVersion; const parsed = claim(draft as Omit<Claim, "format" | "schemaVersion" | "claimHash">); if (parsed.claimHash !== claimHash) throw new TypeError("Foundry V4 online launch claim integrity mismatch"); return parsed; }

/**
 * The sole scheduled consumer of a V4 online-launch handoff.  It reads no
 * caller request and does not advance C30: it creates the existing unrun
 * checkpoint, then conditionally replaces exactly that handoff with its
 * receipt-bound resume identity.
 */
export class TearFoundryV4OnlineLaunchScheduler {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore; readonly #corpus: TearAcademyCorpusStore; readonly #loader: TearAcademyTrainingDatasetLoader;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore, corpus: TearAcademyCorpusStore, loader: TearAcademyTrainingDatasetLoader) { if (jobs.backend() !== custody.backend() || jobs.backend() !== corpus.backend()) throw new TypeError("Foundry V4 online launch must share the C31 Vault boundary"); this.#jobs = jobs; this.#custody = custody; this.#corpus = corpus; this.#loader = loader; }
  async launch(schedule: TearFoundryJobScheduleV1, source: TearFoundryExecutionBindingV4, at: string): Promise<Readonly<{ binding: TearFoundryExecutionBindingV4; launch: TearFoundryOnlineTrainingLaunchV1 }>> {
    if (!Number.isFinite(Date.parse(at)) || source.payload.kind !== "online-launch-ready" || source.schedule.scheduleHash !== schedule.scheduleHash || source.job.phase !== "evaluating") throw new RangeError("Foundry V4 online launch is not exactly declared");
    const backend = this.#jobs.backend(), authorityKey = `foundry-job-v4-online-launch-authority:v1:${source.payload.authorityHash}`, handoffKey = `foundry-job-v4-online-launch-handoff:v1:${source.payload.handoffReceiptHash}`, claimKey = `${CLAIM}${source.payload.authorityHash}`, pointerKey = `${POINTER}${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`, jobKey = `foundry-job:v1:${source.job.id}`, scheduleKey = `foundry-job-schedule:v1:${schedule.id}`;
    const [authorityRaw, handoffRaw, pointerRaw, sourceRaw, scheduleRaw, jobRaw] = await Promise.all([backend.get("analysis", authorityKey), backend.get("analysis", handoffKey), backend.get("analysis", pointerKey), backend.get("analysis", `${BINDING}${source.bindingHash}`), backend.get("analysis", scheduleKey), backend.get("analysis", jobKey)]);
    if (authorityRaw === undefined || handoffRaw === undefined || pointerRaw === undefined || sourceRaw === undefined || scheduleRaw === undefined || jobRaw === undefined || pointerRaw !== source.bindingHash || sourceRaw !== JSON.stringify(source) || scheduleRaw !== JSON.stringify(schedule)) throw new RangeError("Foundry V4 online launch source authority changed");
    let authority; let handoff; let job; try { authority = parseTearFoundryV4OnlineLaunchAuthority(JSON.parse(authorityRaw)); handoff = parseTearFoundryV4OnlineLaunchHandoffReceipt(JSON.parse(handoffRaw)); job = parseTearFoundryJob(JSON.parse(jobRaw)); } catch { throw new RangeError("Foundry V4 online launch authority is invalid"); }
    if (authority.authorityHash !== source.payload.authorityHash || handoff.receiptHash !== source.payload.handoffReceiptHash || handoff.authorityHash !== authority.authorityHash || handoff.sourceBindingHash !== authority.sourceBindingHash || authority.schedule.scheduleHash !== schedule.scheduleHash || authority.schedule.id !== schedule.id || authority.schedule.revision !== schedule.revision || authority.job.id !== source.job.id || authority.job.jobHash !== source.job.jobHash) throw new RangeError("Foundry V4 online launch handoff changed");
    const declaredSourceRaw = await backend.get("analysis", `${BINDING}${authority.sourceBindingHash}`); try { const declaredSource = declaredSourceRaw === undefined ? undefined : parseTearFoundryExecutionBindingV4(JSON.parse(declaredSourceRaw)); if (declaredSource?.bindingHash !== authority.sourceBindingHash || declaredSource.payload.kind !== "evaluation-ready" || declaredSource.job.jobHash !== source.job.jobHash || declaredSource.schedule.scheduleHash !== schedule.scheduleHash) throw new TypeError("mismatch"); } catch { throw new RangeError("Foundry V4 online launch declared source changed"); }
    if ((await this.#jobs.get(source.job.id))?.jobHash !== source.job.jobHash || JSON.stringify(job) !== jobRaw) throw new RangeError("Foundry V4 online launch job changed");
    const profileKey = `foundry-launch-profile:v1:${authority.profile.id}`, readinessKey = `foundry-job-evaluation-ready:v1:${authority.readinessReceiptHash}`, [profileRaw, readinessRaw, held, inventory] = await Promise.all([backend.get("analysis", profileKey), backend.get("analysis", readinessKey), this.#custody.held(at), this.#custody.inventory()]);
    if (profileRaw === undefined || readinessRaw === undefined) throw new RangeError("Foundry V4 online launch profile or readiness is unavailable");
    let profile; let readiness; try { profile = parseTearFoundryLaunchProfile(JSON.parse(profileRaw)); readiness = parseTearFoundryEvaluationReadinessReceipt(JSON.parse(readinessRaw)); } catch { throw new RangeError("Foundry V4 online launch profile or readiness changed"); }
    if (profile.profileHash !== authority.profile.profileHash || profile.jobId !== source.job.id || readiness.receiptHashValue !== authority.readinessReceiptHash || readiness.job.resultJobHash !== source.job.jobHash) throw new RangeError("Foundry V4 online launch retained authority changed");
    const records = inventory.records.filter((record) => job.inputs.corpusRecordHashes.includes(record.recordHash)).sort((a, b) => a.candidateHash.localeCompare(b.candidateHash)), custodyRaw = await Promise.all(records.map((record) => backend.get("analysis", `academy-candidate-custody:v1:${record.candidateHash}`)));
    const custodyHash = stableVerificationHash(records.map((record, index) => Object.freeze({ candidateHash: record.candidateHash, recordHash: record.recordHash, raw: custodyRaw[index] })));
    if (records.length !== job.inputs.corpusRecordHashes.length || custodyRaw.some((raw) => raw === undefined) || custodyHash !== authority.custodyHash || !job.inputs.corpusRecordHashes.every((hash) => held.some((record) => record.recordHash === hash))) throw new RangeError("Foundry V4 online launch custody changed");
    const bootstrapKeys = (await backend.keys("analysis")).filter((key) => key.startsWith("foundry-job-bootstrap:v1:")); let bootstrapRaw: string | undefined; let bootstrapKey: string | undefined;
    for (const key of bootstrapKeys) { const raw = await backend.get("analysis", key); try { if (raw !== undefined && parseTearFoundryBootstrapReceipt(JSON.parse(raw)).receiptHash === authority.bootstrapReceiptHash) { bootstrapRaw = raw; bootstrapKey = key; break; } } catch { if (raw !== undefined) await backend.put("quarantine", key, raw); } }
    if (bootstrapRaw === undefined) throw new RangeError("Foundry V4 online launch bootstrap changed");
    const desiredClaim = claim({ authorityHash: authority.authorityHash, handoffReceiptHash: handoff.receiptHash, sourceBindingHash: source.bindingHash, claimedAt: authority.declaredAt }), priorClaim = await backend.get("analysis", claimKey);
    if (priorClaim !== undefined) { try { if (parseClaim(JSON.parse(priorClaim)).claimHash !== desiredClaim.claimHash) throw new TypeError("mismatch"); } catch { throw new RangeError("Foundry V4 online launch claim is invalid"); } }
    else {
      try { await backend.commitIfMatches(Object.freeze([guard(scheduleKey, scheduleRaw), guard(jobKey, jobRaw), guard(pointerKey, source.bindingHash), guard(`${BINDING}${source.bindingHash}`, sourceRaw), guard(authorityKey, authorityRaw), guard(handoffKey, handoffRaw), guard(profileKey, profileRaw), guard(readinessKey, readinessRaw), guard(bootstrapKey ?? "", bootstrapRaw), guard(claimKey, undefined), ...records.map((record, index) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, custodyRaw[index]))]), Object.freeze([{ store: "analysis", key: claimKey, value: JSON.stringify(desiredClaim) }, { store: "indexes", key: `foundry-job-v4-online-launch-claim:${source.job.id}:${desiredClaim.claimHash}`, value: JSON.stringify(Object.freeze({ scheduleHash: schedule.scheduleHash, sourceBindingHash: source.bindingHash })) }])); } catch { throw new RangeError("Foundry V4 online launch lost its pre-launch authority"); }
    }
    const output = await new TearFoundryOnlineTrainingLaunchExecutor(this.#jobs, this.#custody, this.#corpus, this.#loader).launch(job, readiness, authority.request, at);
    const launchRaw = await backend.get("analysis", `foundry-job-online-training-launch:v1:${output.launch.launchHash}`); if (launchRaw === undefined || parseTearFoundryOnlineTrainingLaunch(JSON.parse(launchRaw)).launchHash !== output.launch.launchHash) throw new RangeError("Foundry V4 online launch was not durably retained");
    const next = createTearFoundryExecutionBindingV4({ schedule: source.schedule, job: source.job, payload: { kind: "online-resume", authorityHash: authority.authorityHash, handoffReceiptHash: handoff.receiptHash, launchHash: output.launch.launchHash } });
    const nextKey = `${BINDING}${next.bindingHash}`, prior = await backend.get("analysis", nextKey);
    if (prior !== undefined) { const parsed = parseTearFoundryExecutionBindingV4(JSON.parse(prior)); if (parsed.bindingHash === next.bindingHash && (await backend.get("analysis", pointerKey)) === next.bindingHash) return Object.freeze({ binding: parsed, launch: output.launch }); throw new RangeError("Foundry V4 online launch retry lost its binding"); }
    try { await backend.commitIfMatches(Object.freeze([guard(scheduleKey, scheduleRaw), guard(jobKey, jobRaw), guard(pointerKey, source.bindingHash), guard(`${BINDING}${source.bindingHash}`, sourceRaw), guard(authorityKey, authorityRaw), guard(handoffKey, handoffRaw), guard(profileKey, profileRaw), guard(readinessKey, readinessRaw), guard(bootstrapKey ?? "", bootstrapRaw), guard(claimKey, JSON.stringify(desiredClaim)), guard(nextKey, undefined), ...records.map((record, index) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, custodyRaw[index]))]), Object.freeze([{ store: "analysis", key: nextKey, value: JSON.stringify(next) }, { store: "analysis", key: pointerKey, value: next.bindingHash }, { store: "indexes", key: `foundry-job-v4-online-resume:${source.job.id}:${output.launch.launchHash}`, value: JSON.stringify(Object.freeze({ authorityHash: authority.authorityHash, handoffReceiptHash: handoff.receiptHash, scheduleHash: schedule.scheduleHash })) }])); } catch { throw new RangeError("Foundry V4 online launch lost its authority or source binding"); }
    return Object.freeze({ binding: next, launch: output.launch });
  }
}
