import { stableVerificationHash } from "../replay/hash";
import { createTearFoundryExecutionBindingV2, parseTearFoundryExecutionBindingV2, TearFoundryExecutionBindingVault, type TearFoundryExecutionBindingPayloadV1, type TearFoundryExecutionBindingV2 } from "./foundry-job-execution-binding";
import { parseTearFoundryDueAttemptReceipt, type TearFoundryDueAttemptReceiptV1 } from "./foundry-job-due-dispatcher";
import { parseTearFoundryJob, type TearFoundryJobV1 } from "./foundry-job-state";
import { rebindTearFoundryJobSchedule, type TearFoundryJobScheduleV1, type TearFoundryScheduleAuthority } from "./foundry-job-schedule";
import { TearFoundrySuccessorExecutionBindingMaterialVault } from "./foundry-job-successor-binding-material";
import type { TearFoundryJobScheduleVault } from "./foundry-job-schedule";
import type { TearFoundryJobVault } from "./foundry-job-vault";

const HASH = /^[a-f0-9]{16}$/u;
const bindingKey = (hash: string) => `foundry-job-execution-binding:v2:${hash}`;
const pointerKey = (schedule: TearFoundryJobScheduleV1) => `foundry-job-execution-binding-current:v2:${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`;
function time(value: unknown): value is string { return typeof value === "string" && Number.isFinite(Date.parse(value)); }
function same(a: unknown, b: unknown): boolean { return JSON.stringify(a) === JSON.stringify(b); }
export interface TearFoundryBoundContinuationReceiptV1 { readonly format: "tear-foundry-bound-continuation"; readonly schemaVersion: 1; readonly sourceScheduleHash: string; readonly sourceBindingHash: string; readonly nextScheduleHash: string; readonly nextBindingHash: string; readonly attemptReceiptHash: string; readonly continuedAt: string; readonly continuationHash: string; }
function receipt(draft: Omit<TearFoundryBoundContinuationReceiptV1, "continuationHash">): TearFoundryBoundContinuationReceiptV1 { if (!HASH.test(draft.sourceScheduleHash) || !HASH.test(draft.sourceBindingHash) || !HASH.test(draft.nextScheduleHash) || !HASH.test(draft.nextBindingHash) || !HASH.test(draft.attemptReceiptHash) || !time(draft.continuedAt)) throw new TypeError("invalid Foundry bound continuation receipt"); return Object.freeze({ ...draft, continuationHash: stableVerificationHash(draft) }); }
function parseReceipt(value: unknown): TearFoundryBoundContinuationReceiptV1 { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("invalid Foundry bound continuation receipt"); const source = value as TearFoundryBoundContinuationReceiptV1, { continuationHash, ...draft } = source, parsed = receipt(draft); if (continuationHash !== parsed.continuationHash) throw new TypeError("Foundry bound continuation integrity mismatch"); return parsed; }
function successorPayload(binding: TearFoundryExecutionBindingV2, attempt: TearFoundryDueAttemptReceiptV1, material: Awaited<ReturnType<TearFoundrySuccessorExecutionBindingMaterialVault["get"]>>, next: TearFoundryJobV1): TearFoundryExecutionBindingPayloadV1 {
  if (attempt.successorExecutionBindingMaterialRequired === undefined) return binding.successorDeclaration;
  if (material?.sourceJobHash !== binding.job.jobHash || material.attemptReceiptHash !== attempt.receiptHash || material.successor.id !== next.id || material.successor.jobHash !== next.jobHash || material.successor.phase !== next.phase || !same(material.payload, binding.successorDeclaration)) throw new RangeError("Foundry bound continuation material does not match immutable declaration");
  return material.payload;
}
/**
 * Atomic control-plane handoff only. It never selects or invokes an executor.
 * V1 bindings are deliberately recovery-readable but continuation-ineligible.
 */
export class TearFoundryBoundContinuationCoordinator {
  readonly #jobs: TearFoundryJobVault; readonly #schedules: TearFoundryJobScheduleVault; readonly #authority: TearFoundryScheduleAuthority;
  constructor(jobs: TearFoundryJobVault, schedules: TearFoundryJobScheduleVault, authority: TearFoundryScheduleAuthority) { this.#jobs = jobs; this.#schedules = schedules; this.#authority = authority; }
  async continueBoundAttempt(sourceScheduleHash: string, sourceBindingHash: string, previousInput: TearFoundryJobV1, nextInput: TearFoundryJobV1, attemptInput: TearFoundryDueAttemptReceiptV1, nextSuccessorDeclaration: TearFoundryExecutionBindingPayloadV1, at: string, budgets: Readonly<{ computeBudgetHash: string; storageBudgetHash: string }>): Promise<Readonly<{ schedule: TearFoundryJobScheduleV1; binding: TearFoundryExecutionBindingV2; receipt: TearFoundryBoundContinuationReceiptV1 }>> {
    if (!HASH.test(sourceScheduleHash) || !HASH.test(sourceBindingHash) || !HASH.test(budgets.computeBudgetHash) || !HASH.test(budgets.storageBudgetHash) || !time(at)) throw new TypeError("invalid Foundry bound continuation request");
    const backend = this.#jobs.backend(), previous = parseTearFoundryJob(previousInput), next = parseTearFoundryJob(nextInput), attempt = parseTearFoundryDueAttemptReceipt(attemptInput);
    const key = `foundry-job-bound-continuation:v1:${stableVerificationHash({ sourceScheduleHash, sourceBindingHash, nextJobHash: next.jobHash, attemptReceiptHash: attempt.receiptHash })}`;
    const old = await backend.get("analysis", key);
    if (old !== undefined) { try { const prior = parseReceipt(JSON.parse(old)), rebound = (await this.#schedules.list()).find((entry) => entry.scheduleHash === prior.nextScheduleHash), nextBinding = rebound === undefined ? undefined : await new TearFoundryExecutionBindingVault(this.#jobs).getV2(prior.nextBindingHash); if (prior.sourceScheduleHash === sourceScheduleHash && prior.sourceBindingHash === sourceBindingHash && prior.attemptReceiptHash === attempt.receiptHash && rebound?.jobHash === next.jobHash && nextBinding?.schedule.scheduleHash === rebound.scheduleHash && nextBinding.job.jobHash === next.jobHash) return Object.freeze({ schedule: rebound, binding: nextBinding, receipt: prior }); } catch { await backend.put("quarantine", key, old); } throw new RangeError("Foundry bound continuation receipt is corrupt"); }
    const schedule = (await this.#schedules.list()).find((entry) => entry.scheduleHash === sourceScheduleHash); if (schedule === undefined) throw new RangeError("Foundry bound continuation schedule is unavailable");
    const bindings = new TearFoundryExecutionBindingVault(this.#jobs), binding = await bindings.getV2(sourceBindingHash); if (binding === undefined) throw new RangeError("Foundry bound continuation requires an immutable V2 binding");
    if (binding.schedule.scheduleHash !== schedule.scheduleHash || binding.job.jobHash !== previous.jobHash || binding.job.jobHash !== attempt.jobHash || binding.job.phase === next.phase && binding.job.jobHash === next.jobHash || attempt.scheduleHash !== schedule.scheduleHash || attempt.disposition !== "collected") throw new RangeError("Foundry bound continuation source lineage is invalid");
    if (schedule.computeBudgetHash !== budgets.computeBudgetHash || schedule.storageBudgetHash !== budgets.storageBudgetHash || schedule.stopConditionsHash !== next.inputs.stopConditionsHash || !(await this.#authority.held(next, at))) throw new RangeError("Foundry bound continuation is not authorized");
    const rebound = rebindTearFoundryJobSchedule(schedule, previous, next, at);
    const durableNext = await this.#jobs.get(next.id); if (durableNext?.jobHash !== next.jobHash) throw new RangeError("Foundry bound continuation durable successor changed");
    const material = await new TearFoundrySuccessorExecutionBindingMaterialVault(backend).get(attempt.receiptHash), nextPayload = successorPayload(binding, attempt, material, next);
    const nextBinding = createTearFoundryExecutionBindingV2({ schedule: { id: rebound.id, revision: rebound.revision, scheduleHash: rebound.scheduleHash }, job: { id: next.id, jobHash: next.jobHash, phase: next.phase }, payload: nextPayload, successorDeclaration: nextSuccessorDeclaration });
    const [scheduleRaw, jobRaw, attemptRaw, pointerRaw, bindingRaw] = await Promise.all([backend.get("analysis", `foundry-job-schedule:v1:${schedule.id}`), backend.get("analysis", `foundry-job:v1:${next.id}`), backend.get("analysis", `foundry-job-due-attempt:v1:${attempt.actionHash}`), backend.get("analysis", pointerKey(schedule)), backend.get("analysis", bindingKey(sourceBindingHash))]);
    if (scheduleRaw === undefined || jobRaw === undefined || attemptRaw === undefined || pointerRaw !== sourceBindingHash || bindingRaw === undefined) throw new RangeError("Foundry bound continuation durable evidence disappeared");
    let durableAttempt: TearFoundryDueAttemptReceiptV1; try { durableAttempt = parseTearFoundryDueAttemptReceipt(JSON.parse(attemptRaw)); parseTearFoundryExecutionBindingV2(JSON.parse(bindingRaw)); } catch { throw new RangeError("Foundry bound continuation durable evidence is corrupt"); }
    if (durableAttempt.receiptHash !== attempt.receiptHash || durableAttempt.jobHash !== binding.job.jobHash || JSON.stringify(next) !== jobRaw) throw new RangeError("Foundry bound continuation durable lineage changed");
    const output = receipt({ format: "tear-foundry-bound-continuation", schemaVersion: 1, sourceScheduleHash, sourceBindingHash, nextScheduleHash: rebound.scheduleHash, nextBindingHash: nextBinding.bindingHash, attemptReceiptHash: attempt.receiptHash, continuedAt: at });
    try { await backend.commitIfMatches(Object.freeze([{ store: "analysis", key: `foundry-job-schedule:v1:${schedule.id}`, expected: scheduleRaw }, { store: "analysis", key: `foundry-job:v1:${next.id}`, expected: jobRaw }, { store: "analysis", key: `foundry-job-due-attempt:v1:${attempt.actionHash}`, expected: attemptRaw }, { store: "analysis", key: pointerKey(schedule), expected: pointerRaw }, { store: "analysis", key: bindingKey(sourceBindingHash), expected: bindingRaw }, { store: "analysis", key }]), Object.freeze([{ store: "analysis", key: `foundry-job-schedule:v1:${schedule.id}`, value: JSON.stringify(rebound) }, { store: "analysis", key: bindingKey(nextBinding.bindingHash), value: JSON.stringify(nextBinding) }, { store: "analysis", key: pointerKey(rebound), value: nextBinding.bindingHash }, { store: "indexes", key: `foundry-job-execution-binding:v2:${rebound.id}:${String(rebound.revision)}:${nextBinding.bindingHash}`, value: JSON.stringify(Object.freeze({ scheduleHash: rebound.scheduleHash, jobHash: next.jobHash, phase: next.phase })) }, { store: "analysis", key, value: JSON.stringify(output) }])); } catch { throw new RangeError("Foundry bound continuation lost current schedule, binding, attempt, or successor"); }
    return Object.freeze({ schedule: rebound, binding: nextBinding, receipt: output });
  }
}
