import { stableVerificationHash } from "../replay/hash";
import type { GhostVaultBackend } from "../ghost";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import type { TearAcademyCorpusStore } from "./academy-corpus";
import type { TearAcademyTrainingDatasetLoader } from "./academy-training-dataset";
import { createTearOfflineRlCheckpoint, createTearOfflineRlPlan, extractTearOfflineRlTrajectories, advanceTearOfflineRlCheckpoint, parseTearOfflineRlPlan, TearOfflineRlCheckpointVault, TearOfflineRlTrajectoryVault, type TearOfflineRlPlanRequestV1, type TearOfflineRlPlanV1, type TearOfflineRlTrainingConfigV1 } from "./offline-rl-training";
import { parseTearFoundryJob, transitionTearFoundryJob, type TearFoundryJobV1 } from "./foundry-job-state";
import type { TearFoundryJobVault } from "./foundry-job-vault";

const KEY = "foundry-job-offline-training:v1:";
const HASH = /^[a-f0-9]{16}$/u;
export interface TearFoundryOfflineTrainingRequestV1 { readonly manifestId: string; readonly trainerId: string; readonly manifestVersion: number; readonly plan: TearOfflineRlPlanRequestV1; readonly config: TearOfflineRlTrainingConfigV1; }
/** Historical V1 launch hashes cannot safely resume: they omitted the exact plan/configuration bytes. */
export interface TearFoundryOfflineTrainingLaunchV1 { readonly format: "tear-foundry-offline-training-launch"; readonly schemaVersion: 1; readonly launchHash: string; }
export interface TearFoundryOfflineTrainingLaunchV2 { readonly format: "tear-foundry-offline-training-launch"; readonly schemaVersion: 2; readonly job: Readonly<{ id: string; sourceJobHash: string; resultJobHash: string }>; readonly manifest: Readonly<{ id: string; trainerId: string; version: number; manifestHash: string; rootHash: string }>; readonly datasetHash: string; readonly plan: TearOfflineRlPlanV1; readonly config: TearOfflineRlTrainingConfigV1; readonly receiptHash: string; readonly checkpointHash: string; readonly previousLaunchHash?: string; readonly launchHash: string; }
function text(value: unknown): value is string { return typeof value === "string" && value.trim().length > 0; }
function hash(value: unknown): value is string { return typeof value === "string" && HASH.test(value); }
function exact(records: readonly string[], entries: readonly string[]): boolean { return records.length === entries.length && new Set(entries).size === entries.length && entries.every((entry) => records.includes(entry)); }
function validConfig(value: TearOfflineRlTrainingConfigV1): boolean { return Number.isSafeInteger(value.epochs) && value.epochs >= 1 && Number.isFinite(value.learningRate) && value.learningRate > 0 && value.learningRate <= 1 && Number.isFinite(value.gamma) && value.gamma >= 0 && value.gamma <= 1 && Number.isSafeInteger(value.maxStateActionEntries) && value.maxStateActionEntries > 0 && Number.isFinite(value.maxAbsoluteQ) && value.maxAbsoluteQ > 0 && Number.isFinite(value.maxMeanAbsoluteTdError) && value.maxMeanAbsoluteTdError >= 0 && Number.isSafeInteger(value.maxConsecutiveDivergentEpochs) && value.maxConsecutiveDivergentEpochs >= 1; }
function freeze(draft: Omit<TearFoundryOfflineTrainingLaunchV2, "launchHash">): TearFoundryOfflineTrainingLaunchV2 { const plan = parseTearOfflineRlPlan(draft.plan); if (!text(draft.job.id) || !text(draft.manifest.id) || !text(draft.manifest.trainerId) || !Number.isSafeInteger(draft.manifest.version) || draft.manifest.version < 1 || ![draft.job.sourceJobHash, draft.job.resultJobHash, draft.manifest.manifestHash, draft.manifest.rootHash, draft.datasetHash, draft.receiptHash, draft.checkpointHash].every(hash) || !validConfig(draft.config) || (draft.previousLaunchHash !== undefined && !hash(draft.previousLaunchHash))) throw new TypeError("invalid Foundry offline training launch"); const value = Object.freeze({ ...draft, job: Object.freeze({ ...draft.job }), manifest: Object.freeze({ ...draft.manifest }), plan, config: Object.freeze({ ...draft.config }) }); return Object.freeze({ ...value, launchHash: stableVerificationHash(value) }); }
export function parseTearFoundryOfflineTrainingLaunch(value: unknown): TearFoundryOfflineTrainingLaunchV2 { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("invalid Foundry offline training launch"); const source = value as Record<string, unknown>; if (source.format !== "tear-foundry-offline-training-launch" || source.schemaVersion !== 2 || !hash(source.launchHash)) throw new TypeError("Foundry offline training V1 launch is non-resumable"); const typed = source as unknown as TearFoundryOfflineTrainingLaunchV2, { launchHash, ...draft } = typed, parsed = freeze(draft); if (launchHash !== parsed.launchHash) throw new TypeError("Foundry offline training launch integrity mismatch"); return parsed; }

export class TearFoundryOfflineTrainingLaunchVault {
  readonly #backend: GhostVaultBackend;
  constructor(backend: GhostVaultBackend) { this.#backend = backend; }
  async get(launchHash: string): Promise<TearFoundryOfflineTrainingLaunchV2 | undefined> { if (!hash(launchHash)) throw new TypeError("Foundry offline training launch hash is invalid"); const key = `${KEY}${launchHash}`, raw = await this.#backend.get("analysis", key); if (raw === undefined) return undefined; try { return parseTearFoundryOfflineTrainingLaunch(JSON.parse(raw)); } catch (error) { await this.#backend.put("quarantine", key, JSON.stringify(Object.freeze({ format: "foundry-offline-training-launch-quarantine", schemaVersion: 1, key, raw, reason: error instanceof Error ? error.message : String(error) }))); return undefined; } }
}

/** Starts one persisted bounded C34 epoch from an immutable C31 trainer manifest; it emits no model result or policy artifact. */
export class TearFoundryOfflineTrainingExecutor {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore; readonly #corpus: TearAcademyCorpusStore; readonly #loader: TearAcademyTrainingDatasetLoader;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore, corpus: TearAcademyCorpusStore, loader: TearAcademyTrainingDatasetLoader) { if (jobs.backend() !== custody.backend() || jobs.backend() !== corpus.backend()) throw new TypeError("Foundry offline training must share the C31 Vault boundary"); this.#jobs = jobs; this.#custody = custody; this.#corpus = corpus; this.#loader = loader; }
  async start(jobInput: TearFoundryJobV1, request: TearFoundryOfflineTrainingRequestV1, at: string): Promise<Readonly<{ job: TearFoundryJobV1; launch: TearFoundryOfflineTrainingLaunchV2 }>> {
    const job = parseTearFoundryJob(jobInput); if (job.phase !== "curating" || !text(request.manifestId) || !text(request.trainerId) || !Number.isSafeInteger(request.manifestVersion) || request.manifestVersion < 1 || !text(at)) throw new RangeError("Foundry offline training requires a curating job and immutable manifest request");
    const [manifest, held, dataset] = await Promise.all([this.#corpus.getManifest(request.manifestId, { kind: "trainer", id: request.trainerId }, request.manifestVersion), this.#custody.held(at), this.#loader.load({ manifestId: request.manifestId, trainerId: request.trainerId, version: request.manifestVersion })]);
    if (manifest === undefined) throw new RangeError("Foundry offline training manifest or custody changed before output");
    if (dataset.manifest.manifestHash !== manifest.manifestHash || dataset.manifest.rootHash !== manifest.rootHash || !exact(job.inputs.corpusRecordHashes, manifest.entries.map((entry) => entry.custodyRecordHash)) || !job.inputs.corpusRecordHashes.every((entry) => held.some((record) => record.recordHash === entry))) throw new RangeError("Foundry offline training manifest or custody changed before output");
    const plan = createTearOfflineRlPlan(dataset, request.plan); if (plan.reward.rewardHash !== job.inputs.rewardDefinitionHash) throw new RangeError("Foundry offline training reward is not frozen by the job");
    const receipt = extractTearOfflineRlTrajectories(dataset, plan), initial = createTearOfflineRlCheckpoint(receipt, request.config), checkpoint = advanceTearOfflineRlCheckpoint(initial, receipt, request.config, 1);
    const next = transitionTearFoundryJob(job, "training", at, "one bounded offline C34 epoch persisted");
    const launch = freeze({ format: "tear-foundry-offline-training-launch", schemaVersion: 2, job: { id: job.id, sourceJobHash: job.jobHash, resultJobHash: next.jobHash }, manifest: { id: manifest.id, trainerId: manifest.reader.id, version: manifest.version, manifestHash: manifest.manifestHash, rootHash: manifest.rootHash }, datasetHash: dataset.datasetHash, plan, config: request.config, receiptHash: receipt.receiptHash, checkpointHash: checkpoint.checkpointHash });
    await new TearOfflineRlTrajectoryVault(this.#jobs.backend()).persist(receipt); await new TearOfflineRlCheckpointVault(this.#jobs.backend()).persist(checkpoint);
    await this.#jobs.persistSuccessor(job, next, Object.freeze([{ store: "analysis", key: `${KEY}${launch.launchHash}`, value: JSON.stringify(launch) }, { store: "indexes", key: `foundry-job-offline-training:${job.id}:${launch.launchHash}`, value: JSON.stringify(Object.freeze({ checkpointHash: checkpoint.checkpointHash, planHash: plan.planHash })) }]));
    return Object.freeze({ job: next, launch });
  }

  /** Advances exactly one persisted C34 epoch from an immutable V2 launch; it does not finish or publish a model. */
  async resume(jobInput: TearFoundryJobV1, launchHash: string, at: string): Promise<Readonly<{ job: TearFoundryJobV1; launch: TearFoundryOfflineTrainingLaunchV2 }>> {
    const job = parseTearFoundryJob(jobInput), launches = new TearFoundryOfflineTrainingLaunchVault(this.#jobs.backend()), launch = await launches.get(launchHash);
    if (job.phase !== "training" || !text(at)) throw new RangeError("Foundry offline training resume lineage is unavailable");
    if (launch?.job.id !== job.id) throw new RangeError("Foundry offline training resume lineage is unavailable");
    if (launch.job.resultJobHash !== job.jobHash) throw new RangeError("Foundry offline training resume lineage is unavailable");
    const [manifest, held, dataset, receipt, checkpoint] = await Promise.all([this.#corpus.getManifest(launch.manifest.id, { kind: "trainer", id: launch.manifest.trainerId }, launch.manifest.version), this.#custody.held(at), this.#loader.load({ manifestId: launch.manifest.id, trainerId: launch.manifest.trainerId, version: launch.manifest.version }), new TearOfflineRlTrajectoryVault(this.#jobs.backend()).get(launch.receiptHash), new TearOfflineRlCheckpointVault(this.#jobs.backend()).get(launch.checkpointHash)]);
    if (manifest?.manifestHash !== launch.manifest.manifestHash) throw new RangeError("Foundry offline training resume lineage changed");
    if (manifest.rootHash !== launch.manifest.rootHash || dataset.datasetHash !== launch.datasetHash || !exact(job.inputs.corpusRecordHashes, manifest.entries.map((entry) => entry.custodyRecordHash)) || !job.inputs.corpusRecordHashes.every((entry) => held.some((record) => record.recordHash === entry)) || receipt === undefined || checkpoint === undefined || receipt.plan.planHash !== launch.plan.planHash || receipt.plan.rewardHash !== launch.plan.reward.rewardHash) throw new RangeError("Foundry offline training resume lineage changed");
    const nextCheckpoint = advanceTearOfflineRlCheckpoint(checkpoint, receipt, launch.config, 1), next = transitionTearFoundryJob(job, "training", at, "one exact offline C34 epoch resumed");
    const { launchHash: ignoredLaunchHash, ...prior } = launch; void ignoredLaunchHash;
    const nextLaunch = freeze({ ...prior, job: { id: job.id, sourceJobHash: job.jobHash, resultJobHash: next.jobHash }, checkpointHash: nextCheckpoint.checkpointHash, previousLaunchHash: launch.launchHash });
    await new TearOfflineRlCheckpointVault(this.#jobs.backend()).persist(nextCheckpoint); await this.#jobs.persistSuccessor(job, next, Object.freeze([{ store: "analysis", key: `${KEY}${nextLaunch.launchHash}`, value: JSON.stringify(nextLaunch) }, { store: "indexes", key: `foundry-job-offline-training:${job.id}:${nextLaunch.launchHash}`, value: JSON.stringify(Object.freeze({ checkpointHash: nextCheckpoint.checkpointHash, planHash: nextLaunch.plan.planHash })) }])); return Object.freeze({ job: next, launch: nextLaunch });
  }
}
