import { stableVerificationHash } from "../replay/hash";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import { TearFoundryV3MonitoringBridgeExecutor } from "./foundry-job-v3-monitoring-bridge";
import { parseTearFoundryMonitoringEntryReceipt } from "./foundry-job-monitoring";
import { parseTearFoundryJob, requireTearFoundryEvaluationProtocol } from "./foundry-job-state";
import type { TearFoundryJobScheduleV1 } from "./foundry-job-schedule";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import { createTearFoundryExecutionBindingV4, type TearFoundryExecutionBindingV4 } from "./foundry-job-v4-offline-terminal";
import type { TearOfflineRlV3PlanV1, TearOfflineRlV3TrainingResultV1 } from "./offline-rl-v3-training";
import type { TearOnlineRlV3CheckpointV1, TearOnlineRlV3EvaluationResultV1, TearOnlineRlV3PlanV1 } from "./online-rl-v3-training";
import { parseTearPolicyActivation, parseTearPolicyArtifact } from "./policy-artifact-registry";

const HASH = /^[a-f0-9]{16}$/u, KEY = "foundry-job-v4-v3-monitoring-declaration:v1:", BINDING = "foundry-job-execution-binding:v4:", POINTER = "foundry-job-execution-binding-current:v4:";
const guard = (key: string, expected: string | undefined): Readonly<{ store: "analysis"; key: string; expected?: string }> => Object.freeze({ store: "analysis" as const, key, ...(expected === undefined ? {} : { expected }) });
const present = (value: string | undefined): string => { if (value === undefined) throw new RangeError("Foundry V4 V3 bridge evidence disappeared"); return value; };
export interface TearFoundryV4V3MonitoringDeclarationV1 { readonly format: "tear-foundry-v4-v3-monitoring-declaration"; readonly schemaVersion: 1; readonly bridgeHash: string; readonly sourceBindingHash: string; readonly v3: Readonly<{ offline: TearOfflineRlV3PlanV1; training: TearOfflineRlV3TrainingResultV1; online: TearOnlineRlV3PlanV1; checkpoint: TearOnlineRlV3CheckpointV1; evaluation: TearOnlineRlV3EvaluationResultV1 }>; readonly declaredAt: string; readonly declarationHash: string; }
function declaration(input: Omit<TearFoundryV4V3MonitoringDeclarationV1, "declarationHash">): TearFoundryV4V3MonitoringDeclarationV1 { if (!HASH.test(input.bridgeHash) || !HASH.test(input.sourceBindingHash) || !Number.isFinite(Date.parse(input.declaredAt))) throw new TypeError("invalid Foundry V4 V3 declaration"); const value = Object.freeze({ ...input, v3: Object.freeze(structuredClone(input.v3)) }); return Object.freeze({ ...value, declarationHash: stableVerificationHash(value) }); }
export function parseTearFoundryV4V3MonitoringDeclaration(value: unknown): TearFoundryV4V3MonitoringDeclarationV1 { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new TypeError("invalid Foundry V4 V3 declaration"); const typed = value as TearFoundryV4V3MonitoringDeclarationV1, { declarationHash, ...draft } = typed, parsed = declaration(draft); if (!HASH.test(declarationHash) || declarationHash !== parsed.declarationHash) throw new TypeError("Foundry V4 V3 declaration integrity mismatch"); return parsed; }

/** Atomic, approver-free evidence admission. It stores supplied V3 bytes but cannot schedule, execute, register, activate, or promote them. */
export class TearFoundryV4V3MonitoringBridgeExecutor {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore) { if (jobs.backend() !== custody.backend()) throw new TypeError("Foundry V4 V3 bridge must share C31 custody"); this.#jobs = jobs; this.#custody = custody; }
  async declare(schedule: TearFoundryJobScheduleV1, source: TearFoundryExecutionBindingV4, input: Readonly<{ offline: TearOfflineRlV3PlanV1; training: TearOfflineRlV3TrainingResultV1; online: TearOnlineRlV3PlanV1; checkpoint: TearOnlineRlV3CheckpointV1; evaluation: TearOnlineRlV3EvaluationResultV1; candidateArtifactId: string; declaredAt: string }>): Promise<TearFoundryExecutionBindingV4> {
    if (source.payload.kind !== "monitoring-entry-terminal" || source.job.phase !== "monitoring" || source.schedule.scheduleHash !== schedule.scheduleHash || schedule.state !== "disabled" || !Number.isFinite(Date.parse(input.declaredAt))) throw new RangeError("Foundry V4 V3 bridge requires a concluded monitoring terminal");
    const backend = this.#jobs.backend(), scheduleKey = `foundry-job-schedule:v1:${schedule.id}`, jobKey = `foundry-job:v1:${source.job.id}`, sourceKey = `${BINDING}${source.bindingHash}`, pointerKey = `${POINTER}${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`, monitoringKey = `foundry-job-monitoring-entry:v1:${source.payload.monitoringReceiptHash}`;
    const [scheduleRaw, jobRaw, sourceRaw, pointerRaw, monitoringRaw, inventory, held, candidateRaw, activeRaw] = await Promise.all([backend.get("analysis", scheduleKey), backend.get("analysis", jobKey), backend.get("analysis", sourceKey), backend.get("analysis", pointerKey), backend.get("analysis", monitoringKey), this.#custody.inventory(), this.#custody.held(input.declaredAt), backend.get("analysis", `policy-artifact:v1:${input.candidateArtifactId}`), backend.get("analysis", "policy-active:v1")]);
    if ([scheduleRaw, jobRaw, sourceRaw, monitoringRaw, candidateRaw].some((raw) => raw === undefined) || scheduleRaw !== JSON.stringify(schedule) || sourceRaw !== JSON.stringify(source)) throw new RangeError("Foundry V4 V3 bridge authority changed");
    if (pointerRaw !== source.bindingHash) { const nextRaw = typeof pointerRaw === "string" ? await backend.get("analysis", `${BINDING}${pointerRaw}`) : undefined; try { const next = nextRaw === undefined ? undefined : JSON.parse(nextRaw) as TearFoundryExecutionBindingV4; if (next?.payload.kind === "v3-monitoring-bridge-ready") { const storedRaw = await backend.get("analysis", `${KEY}${next.payload.declarationHash}`), stored = storedRaw === undefined ? undefined : parseTearFoundryV4V3MonitoringDeclaration(JSON.parse(storedRaw)); if (stored?.sourceBindingHash === source.bindingHash && stored.declaredAt === input.declaredAt && JSON.stringify(stored.v3) === JSON.stringify({ offline: input.offline, training: input.training, online: input.online, checkpoint: input.checkpoint, evaluation: input.evaluation })) return next; } } catch { throw new RangeError("Foundry V4 V3 bridge retry evidence is invalid"); } throw new RangeError("Foundry V4 V3 bridge authority changed"); }
    let job; let monitoring; let candidate; try { job = parseTearFoundryJob(JSON.parse(present(jobRaw))); monitoring = parseTearFoundryMonitoringEntryReceipt(JSON.parse(present(monitoringRaw))); candidate = parseTearPolicyArtifact(JSON.parse(present(candidateRaw))); } catch { throw new RangeError("Foundry V4 V3 bridge retained evidence is invalid"); }
    if (activeRaw !== undefined) { try { const active = parseTearPolicyActivation(JSON.parse(activeRaw)); if (active.artifactId === candidate.id || active.artifactHash === candidate.artifactHash) throw new RangeError("Foundry V4 V3 bridge candidate is already active"); } catch (error) { if (error instanceof RangeError) throw error; throw new RangeError("Foundry V4 V3 bridge active policy is invalid", { cause: error }); } }
    const protocol = requireTearFoundryEvaluationProtocol(job), records = inventory.records.filter((entry) => job.inputs.corpusRecordHashes.includes(entry.recordHash)).sort((a, b) => a.candidateHash.localeCompare(b.candidateHash)), custodyRaw = await Promise.all(records.map((entry) => backend.get("analysis", `academy-candidate-custody:v1:${entry.candidateHash}`)));
    if (job.jobHash !== source.job.jobHash || monitoring.jobHash !== job.jobHash || monitoring.stopConditionsHash !== job.inputs.stopConditionsHash || records.length !== job.inputs.corpusRecordHashes.length || custodyRaw.some((raw) => raw === undefined) || !job.inputs.corpusRecordHashes.every((recordHash) => held.some((entry) => entry.recordHash === recordHash))) throw new RangeError("Foundry V4 V3 bridge custody or monitoring changed");
    let next: TearFoundryExecutionBindingV4 | undefined;
    const bridge = await new TearFoundryV3MonitoringBridgeExecutor(this.#jobs, this.#custody).bridge(job, { decisionReceiptHash: monitoring.decisionReceiptHash, monitoringReceiptHash: monitoring.receiptHash, offline: input.offline, training: input.training, online: input.online, checkpoint: input.checkpoint, evaluation: input.evaluation, candidateArtifactId: input.candidateArtifactId, bridgedAt: input.declaredAt }, { guards: (value) => { const stored = declaration({ format: "tear-foundry-v4-v3-monitoring-declaration", schemaVersion: 1, bridgeHash: value.bridgeHash, sourceBindingHash: source.bindingHash, v3: { offline: input.offline, training: input.training, online: input.online, checkpoint: input.checkpoint, evaluation: input.evaluation }, declaredAt: input.declaredAt }), declarationKey = `${KEY}${stored.declarationHash}`; next = createTearFoundryExecutionBindingV4({ schedule: source.schedule, job: source.job, payload: { kind: "v3-monitoring-bridge-ready", declarationHash: stored.declarationHash } }); return Object.freeze([guard(scheduleKey, scheduleRaw), guard(jobKey, jobRaw), guard(sourceKey, sourceRaw), guard(pointerKey, source.bindingHash), guard(monitoringKey, monitoringRaw), guard(`policy-artifact:v1:${input.candidateArtifactId}`, candidateRaw), guard("policy-active:v1", activeRaw), guard(declarationKey, undefined), guard(`${BINDING}${next.bindingHash}`, undefined), guard(pointerKey, source.bindingHash), ...records.map((entry, index) => guard(`academy-candidate-custody:v1:${entry.candidateHash}`, custodyRaw[index]))]); }, writes: (value) => { if (next === undefined) throw new Error("Foundry V4 V3 bridge continuation disappeared"); const stored = declaration({ format: "tear-foundry-v4-v3-monitoring-declaration", schemaVersion: 1, bridgeHash: value.bridgeHash, sourceBindingHash: source.bindingHash, v3: { offline: input.offline, training: input.training, online: input.online, checkpoint: input.checkpoint, evaluation: input.evaluation }, declaredAt: input.declaredAt }); return Object.freeze([{ store: "analysis" as const, key: `${KEY}${stored.declarationHash}`, value: JSON.stringify(stored) }, { store: "analysis" as const, key: `${BINDING}${next.bindingHash}`, value: JSON.stringify(next) }, { store: "analysis" as const, key: pointerKey, value: next.bindingHash }, { store: "indexes" as const, key: `foundry-job-v4-v3-monitoring-bridge:${job.id}:${stored.declarationHash}`, value: JSON.stringify({ bridgeHash: value.bridgeHash, protocolHash: protocol.protocolHash, promotional: false }) }]); } });
    if (next?.payload.kind !== "v3-monitoring-bridge-ready") throw new Error("Foundry V4 V3 bridge continuation was not retained"); void bridge; return next;
  }
}
