import { stableVerificationHash } from "../replay/hash";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import { parseTearC34V3C32PolicyCandidate, TearC34V3C32CandidateRegistry } from "./c34-v3-c32-policy-adapter";
import { parseTearFoundryDecisionReceipt } from "./foundry-job-decision";
import { parseTearFoundryMonitoringEntryReceipt } from "./foundry-job-monitoring";
import { parseTearFoundryJob, requireTearFoundryEvaluationProtocol, type TearFoundryJobV1 } from "./foundry-job-state";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import { parseTearOfflineRlV3Plan, parseTearOfflineRlV3TrainingResult, type TearOfflineRlV3PlanV1, type TearOfflineRlV3TrainingResultV1 } from "./offline-rl-v3-training";
import { parseTearOnlineRlV3Checkpoint, parseTearOnlineRlV3EvaluationResult, parseTearOnlineRlV3Plan, type TearOnlineRlV3CheckpointV1, type TearOnlineRlV3EvaluationResultV1, type TearOnlineRlV3PlanV1 } from "./online-rl-v3-training";

const KEY = "foundry-job-v3-monitoring-bridge:v1:";
const HASH = /^[a-f0-9]{16}$/u;
export interface TearFoundryV3MonitoringBridgeV1 { readonly format: "tear-foundry-v3-monitoring-bridge"; readonly schemaVersion: 1; readonly job: Readonly<{ id: string; jobHash: string; protocolHash: string; stopConditionsHash: string }>; readonly v3: Readonly<{ offlinePlanHash: string; offlineTrainingHash: string; onlinePlanHash: string; onlineCheckpointHash: string; evaluationHash: string; adapterHash: string; actionVocabularyHash: string; candidateArtifactId: string; candidateArtifactHash: string }>; readonly v2Monitoring: Readonly<{ decisionReceiptHash: string; monitoringReceiptHash: string; evaluationResultHash: string }>; readonly bridgedAt: string; readonly bridgeHash: string; }
export interface TearFoundryV3MonitoringBridgeContinuationV1 { readonly guards: (bridge: TearFoundryV3MonitoringBridgeV1) => readonly Readonly<{ store: "analysis"; key: string; expected?: string }>[]; readonly writes: (bridge: TearFoundryV3MonitoringBridgeV1) => readonly Readonly<{ store: "analysis" | "indexes"; key: string; value: string }>[]; }
function hash(v: unknown): v is string { return typeof v === "string" && HASH.test(v); }
function text(v: unknown): v is string { return typeof v === "string" && v.trim().length > 0; }
function time(v: unknown): v is string { return text(v) && Number.isFinite(Date.parse(v)); }
function bridge(d: Omit<TearFoundryV3MonitoringBridgeV1, "bridgeHash">): TearFoundryV3MonitoringBridgeV1 { if (!text(d.job.id) || ![d.job.jobHash, d.job.protocolHash, d.job.stopConditionsHash, d.v3.offlinePlanHash, d.v3.offlineTrainingHash, d.v3.onlinePlanHash, d.v3.onlineCheckpointHash, d.v3.evaluationHash, d.v3.adapterHash, d.v3.actionVocabularyHash, d.v3.candidateArtifactHash, d.v2Monitoring.decisionReceiptHash, d.v2Monitoring.monitoringReceiptHash, d.v2Monitoring.evaluationResultHash].every(hash) || !text(d.v3.candidateArtifactId) || !time(d.bridgedAt)) throw new TypeError("invalid Foundry V3 monitoring bridge"); const value = Object.freeze({ ...d, job: Object.freeze({ ...d.job }), v3: Object.freeze({ ...d.v3 }), v2Monitoring: Object.freeze({ ...d.v2Monitoring }) }); return Object.freeze({ ...value, bridgeHash: stableVerificationHash(value) }); }
export function parseTearFoundryV3MonitoringBridge(value: unknown): TearFoundryV3MonitoringBridgeV1 { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("invalid Foundry V3 monitoring bridge"); const typed = value as TearFoundryV3MonitoringBridgeV1, { bridgeHash, ...draft } = typed, parsed = bridge(draft); if (!hash(bridgeHash) || bridgeHash !== parsed.bridgeHash) throw new TypeError("Foundry V3 monitoring bridge integrity mismatch"); return parsed; }

/** Explicitly bridges a current V2 monitoring head to separately validated V3 evidence; it is not a V2 reinterpretation or a promotion. */
export class TearFoundryV3MonitoringBridgeExecutor {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore) { if (jobs.backend() !== custody.backend()) throw new TypeError("Foundry V3 bridge must share C31 custody Vault"); this.#jobs = jobs; this.#custody = custody; }
  async bridge(jobInput: TearFoundryJobV1, input: Readonly<{ decisionReceiptHash: string; monitoringReceiptHash: string; offline: TearOfflineRlV3PlanV1; training: TearOfflineRlV3TrainingResultV1; online: TearOnlineRlV3PlanV1; checkpoint: TearOnlineRlV3CheckpointV1; evaluation: TearOnlineRlV3EvaluationResultV1; candidateArtifactId: string; bridgedAt: string }>, continuation?: TearFoundryV3MonitoringBridgeContinuationV1): Promise<TearFoundryV3MonitoringBridgeV1> {
    const job = parseTearFoundryJob(jobInput), protocol = requireTearFoundryEvaluationProtocol(job), backend = this.#jobs.backend(), offline = parseTearOfflineRlV3Plan(input.offline), training = parseTearOfflineRlV3TrainingResult(input.training), online = parseTearOnlineRlV3Plan(input.online), checkpoint = parseTearOnlineRlV3Checkpoint(input.checkpoint), evaluation = parseTearOnlineRlV3EvaluationResult(input.evaluation);
    if (job.phase !== "monitoring" || !hash(input.decisionReceiptHash) || !hash(input.monitoringReceiptHash) || !text(input.candidateArtifactId) || !time(input.bridgedAt) || (await this.#jobs.get(job.id))?.jobHash !== job.jobHash) throw new RangeError("Foundry V3 bridge requires the exact current monitoring job");
    const [decisionRaw, monitorRaw] = await Promise.all([backend.get("analysis", `foundry-job-decision:v1:${input.decisionReceiptHash}`), backend.get("analysis", `foundry-job-monitoring-entry:v1:${input.monitoringReceiptHash}`)]);
    const decision = decisionRaw === undefined ? undefined : parseTearFoundryDecisionReceipt(JSON.parse(decisionRaw)), monitoring = monitorRaw === undefined ? undefined : parseTearFoundryMonitoringEntryReceipt(JSON.parse(monitorRaw)), held = await this.#custody.held(input.bridgedAt);
    if (decision?.disposition !== "monitoring-ready" || decision.job.resultJobHash !== job.jobHash || monitoring?.jobHash !== job.jobHash || monitoring.decisionReceiptHash !== input.decisionReceiptHash || monitoring.evaluationResultHash !== decision.evaluationResultHash || monitoring.stopConditionsHash !== job.inputs.stopConditionsHash || !job.inputs.corpusRecordHashes.every((entry) => held.some((record) => record.recordHash === entry))) throw new RangeError("Foundry V3 bridge monitoring/custody lineage changed");
    if (training.disposition !== "complete" || training.model === undefined || training.plan.planHash !== offline.planHash || online.offline.v3PlanHash !== offline.planHash || online.offline.trainingHash !== training.trainingHash || checkpoint.status !== "complete" || checkpoint.planHash !== online.planHash || !evaluation.metrics.passed || evaluation.planHash !== online.planHash || evaluation.baselineTrainingHash !== training.trainingHash || evaluation.challengerCheckpointHash !== checkpoint.checkpointHash) throw new RangeError("Foundry V3 bridge evidence is incomplete or changed");
    const candidates = new TearC34V3C32CandidateRegistry(backend), candidate = await candidates.get(input.candidateArtifactId); if (candidate === undefined) throw new RangeError("Foundry V3 bridge candidate is unavailable or corrupt"); const payload = parseTearC34V3C32PolicyCandidate(candidate);
    if (payload.lineage.offlinePlanHash !== offline.planHash || payload.lineage.offlineTrainingHash !== training.trainingHash || payload.lineage.onlinePlanHash !== online.planHash || payload.lineage.onlineCheckpointHash !== checkpoint.checkpointHash || payload.lineage.onlineEvaluationHash !== evaluation.resultHash || payload.lineage.actionVocabularyHash !== offline.actionVocabularyHash || payload.sourceStateAdapter.adapterHash !== training.plan.adapterHash) throw new RangeError("Foundry V3 bridge candidate lineage changed");
    const output = bridge({ format: "tear-foundry-v3-monitoring-bridge", schemaVersion: 1, job: { id: job.id, jobHash: job.jobHash, protocolHash: protocol.protocolHash, stopConditionsHash: job.inputs.stopConditionsHash }, v3: { offlinePlanHash: offline.planHash, offlineTrainingHash: training.trainingHash, onlinePlanHash: online.planHash, onlineCheckpointHash: checkpoint.checkpointHash, evaluationHash: evaluation.resultHash, adapterHash: training.plan.adapterHash, actionVocabularyHash: offline.actionVocabularyHash, candidateArtifactId: candidate.id, candidateArtifactHash: candidate.artifactHash }, v2Monitoring: { decisionReceiptHash: decision.receiptHash, monitoringReceiptHash: monitoring.receiptHash, evaluationResultHash: decision.evaluationResultHash }, bridgedAt: input.bridgedAt });
    const key = `${KEY}${output.bridgeHash}`, old = await backend.get("analysis", key); if (old !== undefined) { try { return parseTearFoundryV3MonitoringBridge(JSON.parse(old)); } catch { await backend.put("quarantine", key, old); throw new RangeError("Foundry V3 bridge receipt is corrupt"); } }
    const base = Object.freeze([{ store: "analysis" as const, key, value: JSON.stringify(output) }, { store: "indexes" as const, key: `foundry-job-v3-monitoring-bridge:${job.id}:${output.bridgeHash}`, value: JSON.stringify(Object.freeze({ jobHash: job.jobHash, candidateArtifactHash: candidate.artifactHash, promotional: false })) }]);
    if (continuation === undefined) await backend.commit(base); else await backend.commitIfMatches(Object.freeze([...continuation.guards(output), Object.freeze({ store: "analysis" as const, key })]), Object.freeze([...base, ...continuation.writes(output)])); return output;
  }
  async get(bridgeHash: string): Promise<TearFoundryV3MonitoringBridgeV1 | undefined> { if (!hash(bridgeHash)) throw new TypeError("Foundry V3 bridge hash is invalid"); const key = `${KEY}${bridgeHash}`, raw = await this.#jobs.backend().get("analysis", key); if (raw === undefined) return undefined; try { return parseTearFoundryV3MonitoringBridge(JSON.parse(raw)); } catch { await this.#jobs.backend().put("quarantine", key, raw); return undefined; } }
}
