import type { GhostVaultStore } from "../ghost";
import { stableVerificationHash } from "../replay/hash";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import { parseTearFoundryV3PostPromotionMonitorRecord } from "./foundry-job-v3-post-promotion-monitor";
import { parseTearFoundryV3PromotionReceipt } from "./foundry-job-v3-promotion";
import { parseTearFoundryV3PromotionApproval } from "./foundry-job-v3-promotion-approval";
import { parseTearFoundryJob, requireTearFoundryEvaluationProtocol } from "./foundry-job-state";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import { parseTearPolicyActivation, parseTearPolicyArtifact } from "./policy-artifact-registry";

const HASH = /^[a-f0-9]{16}$/u, ACTIVE = "policy-active:v1", MONITOR = "foundry-job-v3-post-promotion-monitor:v1:";
const APPROVAL = "foundry-job-v3-promotion-approval:v1:", PROMOTION = "foundry-job-v3-promotion-receipt:v1:", RECEIPT = "foundry-job-v3-post-promotion-rollback:v1:";
export interface TearFoundryV3PostPromotionRollbackReceiptV1 { readonly format: "tear-foundry-v3-post-promotion-rollback"; readonly schemaVersion: 1; readonly monitorHash: string; readonly approvalHash: string; readonly promotionReceiptHash: string; readonly sourceActivationHash: string; readonly rollback: Readonly<{ artifactId: string; artifactHash: string; activationHash: string; revision: number }>; readonly rolledBackAt: string; readonly receiptHash: string; }
function hash(value: unknown): value is string { return typeof value === "string" && HASH.test(value); }
function time(value: unknown): value is string { return typeof value === "string" && value.trim().length > 0 && Number.isFinite(Date.parse(value)); }
function guard(key: string, expected: string | undefined, store: GhostVaultStore = "analysis"): Readonly<{ store: GhostVaultStore; key: string; expected?: string }> { return Object.freeze({ store, key, ...(expected === undefined ? {} : { expected }) }); }
function receipt(draft: Omit<TearFoundryV3PostPromotionRollbackReceiptV1, "receiptHash">): TearFoundryV3PostPromotionRollbackReceiptV1 { if (!hash(draft.monitorHash) || !hash(draft.approvalHash) || !hash(draft.promotionReceiptHash) || !hash(draft.sourceActivationHash) || !draft.rollback.artifactId || !hash(draft.rollback.artifactHash) || !hash(draft.rollback.activationHash) || !Number.isSafeInteger(draft.rollback.revision) || draft.rollback.revision < 1 || !time(draft.rolledBackAt)) throw new TypeError("invalid post-promotion rollback receipt"); return Object.freeze({ ...draft, rollback: Object.freeze({ ...draft.rollback }), receiptHash: stableVerificationHash(draft) }); }
export function parseTearFoundryV3PostPromotionRollbackReceipt(value: unknown): TearFoundryV3PostPromotionRollbackReceiptV1 { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("invalid post-promotion rollback receipt"); const typed = value as TearFoundryV3PostPromotionRollbackReceiptV1, { receiptHash, ...draft } = typed, parsed = receipt(draft); if (!hash(receiptHash) || receiptHash !== parsed.receiptHash) throw new TypeError("post-promotion rollback receipt integrity mismatch"); return parsed; }

/** The sole rollback boundary for a C36 promotion. It cannot use generic registry rollback or act on any non-breach observation. */
export class TearFoundryV3PostPromotionRollbackExecutor {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore) { if (jobs.backend() !== custody.backend()) throw new TypeError("post-promotion rollback must share C31 custody Vault"); this.#jobs = jobs; this.#custody = custody; }
  async rollback(monitorHash: string, rolledBackAt: string): Promise<TearFoundryV3PostPromotionRollbackReceiptV1> {
    if (!hash(monitorHash) || !time(rolledBackAt)) throw new TypeError("post-promotion rollback input is invalid"); const backend = this.#jobs.backend(), receiptKey = `${RECEIPT}${monitorHash}`, existing = await backend.get("analysis", receiptKey);
    if (existing !== undefined) { try { return parseTearFoundryV3PostPromotionRollbackReceipt(JSON.parse(existing)); } catch { await backend.put("quarantine", `${receiptKey}:read`, existing); throw new RangeError("post-promotion rollback receipt is corrupt"); } }
    const monitorKey = `${MONITOR}${monitorHash}`, monitorRaw = await backend.get("analysis", monitorKey); if (monitorRaw === undefined) throw new RangeError("post-promotion rollback requires retained monitor evidence");
    let monitor; try { monitor = parseTearFoundryV3PostPromotionMonitorRecord(JSON.parse(monitorRaw)); } catch { await backend.put("quarantine", `${monitorKey}:rollback`, monitorRaw); throw new RangeError("post-promotion rollback monitor is corrupt"); }
    if (monitor.classification !== "threshold-breach") throw new RangeError("post-promotion rollback requires an exact threshold breach");
    const [activeRaw, approvalRaw, promotionRaw] = await Promise.all([backend.get("analysis", ACTIVE), backend.get("analysis", `${APPROVAL}${monitor.promotion.approvalHash}`), backend.get("analysis", `${PROMOTION}${monitor.promotion.approvalHash}`)]);
    if (activeRaw === undefined || approvalRaw === undefined || promotionRaw === undefined) throw new RangeError("post-promotion rollback provenance is unavailable");
    const active = parseTearPolicyActivation(JSON.parse(activeRaw)), approval = parseTearFoundryV3PromotionApproval(JSON.parse(approvalRaw)), promotion = parseTearFoundryV3PromotionReceipt(JSON.parse(promotionRaw));
    if (active.artifactId !== monitor.promotion.artifactId || active.artifactHash !== monitor.promotion.artifactHash || active.activationHash !== monitor.promotion.activationHash || promotion.receiptHash !== monitor.promotion.promotionReceiptHash || promotion.approvalHash !== monitor.promotion.approvalHash || promotion.activationHash !== active.activationHash || approval.approvalHash !== promotion.approvalHash || approval.candidate.id !== active.artifactId || approval.candidate.artifactHash !== active.artifactHash || approval.rollbackBaseline === undefined) throw new RangeError("post-promotion rollback active provenance changed");
    const actualJobRaw = await backend.get("analysis", `foundry-job:v1:${approval.job.id}`); if (actualJobRaw === undefined) throw new RangeError("post-promotion rollback job is unavailable"); const job = parseTearFoundryJob(JSON.parse(actualJobRaw)), protocol = requireTearFoundryEvaluationProtocol(job);
    if (job.phase !== "monitoring" || job.jobHash !== approval.job.jobHash || protocol.protocolHash !== approval.job.protocolHash || job.inputs.stopConditionsHash !== approval.job.stopConditionsHash || monitor.policy.protocolHash !== protocol.protocolHash || monitor.policy.stopConditionsHash !== job.inputs.stopConditionsHash || JSON.stringify(monitor.policy.thresholds) !== JSON.stringify(protocol.thresholds)) throw new RangeError("post-promotion rollback policy changed");
    const held = await this.#custody.held(rolledBackAt); if (!job.inputs.corpusRecordHashes.every((entry) => held.some((record) => record.recordHash === entry))) throw new RangeError("post-promotion rollback custody changed");
    const baseline = approval.rollbackBaseline, baselineKey = `policy-activation:v1:${String(baseline.revision).padStart(12, "0")}`, baselineRaw = await backend.get("indexes", baselineKey); if (baselineRaw === undefined) throw new RangeError("post-promotion rollback baseline is unavailable"); const baselineActivation = parseTearPolicyActivation(JSON.parse(baselineRaw));
    if (baselineActivation.artifactId !== baseline.artifactId || baselineActivation.artifactHash !== baseline.artifactHash || baselineActivation.activationHash !== baseline.activationHash || baselineActivation.revision !== baseline.revision) throw new RangeError("post-promotion rollback baseline changed");
    const artifactRaw = await backend.get("analysis", `policy-artifact:v1:${baseline.artifactId}`); if (artifactRaw === undefined || parseTearPolicyArtifact(JSON.parse(artifactRaw)).artifactHash !== baseline.artifactHash) throw new RangeError("post-promotion rollback baseline artifact is unavailable");
    const revision = active.revision + 1, draft = { format: "tear-policy-activation" as const, schemaVersion: 1 as const, revision, artifactId: baseline.artifactId, artifactHash: baseline.artifactHash, activatedAt: rolledBackAt, previousArtifactId: active.artifactId }, activation = Object.freeze({ ...draft, activationHash: stableVerificationHash(draft) }), output = receipt({ format: "tear-foundry-v3-post-promotion-rollback", schemaVersion: 1, monitorHash, approvalHash: approval.approvalHash, promotionReceiptHash: promotion.receiptHash, sourceActivationHash: active.activationHash, rollback: { artifactId: activation.artifactId, artifactHash: activation.artifactHash, activationHash: activation.activationHash, revision }, rolledBackAt });
    const custodyGuards = await Promise.all(held.filter((entry) => job.inputs.corpusRecordHashes.includes(entry.recordHash)).map(async (entry) => guard(`academy-candidate-custody:v1:${entry.candidateHash}`, await backend.get("analysis", `academy-candidate-custody:v1:${entry.candidateHash}`))));
    try { await backend.commitIfMatches(Object.freeze([guard(ACTIVE, activeRaw), guard(monitorKey, monitorRaw), guard(`${APPROVAL}${approval.approvalHash}`, approvalRaw), guard(`${PROMOTION}${approval.approvalHash}`, promotionRaw), guard(`foundry-job:v1:${job.id}`, actualJobRaw), guard(baselineKey, baselineRaw, "indexes"), guard(`policy-artifact:v1:${baseline.artifactId}`, artifactRaw), guard(receiptKey, undefined), ...custodyGuards]), Object.freeze([{ store: "analysis", key: ACTIVE, value: JSON.stringify(activation) }, { store: "indexes", key: `policy-activation:v1:${String(revision).padStart(12, "0")}`, value: JSON.stringify(activation) }, { store: "analysis", key: receiptKey, value: JSON.stringify(output) }, { store: "indexes", key: `foundry-job-v3-post-promotion-rollback:${monitorHash}`, value: JSON.stringify(Object.freeze({ rolledBack: true, baselineActivationHash: activation.activationHash })) }])); } catch { throw new RangeError("post-promotion rollback lost current evidence"); }
    return output;
  }
}
