import { stableVerificationHash } from "../replay/hash";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import { parseTearFoundryJob, requireTearFoundryEvaluationProtocol } from "./foundry-job-state";
import type { TearFoundryJobScheduleV1 } from "./foundry-job-schedule";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import { parseTearFoundryV3PostPromotionMonitorRecord } from "./foundry-job-v3-post-promotion-monitor";
import { parseTearFoundryV3PromotionApproval } from "./foundry-job-v3-promotion-approval";
import { parseTearFoundryV3PromotionReceipt } from "./foundry-job-v3-promotion";
import { createTearFoundryExecutionBindingV4, parseTearFoundryExecutionBindingV4, type TearFoundryExecutionBindingV4 } from "./foundry-job-v4-offline-terminal";
import { parseTearFoundryV4PostPromotionWatchAuthority } from "./foundry-job-v4-post-promotion-watch-authority";
import { parseTearFoundryV4V3MonitoringDeclaration } from "./foundry-job-v4-v3-monitoring-bridge";
import { parseTearPolicyActivation, parseTearPolicyArtifact } from "./policy-artifact-registry";

const HASH = /^[a-f0-9]{16}$/u, BINDING = "foundry-job-execution-binding:v4:", POINTER = "foundry-job-execution-binding-current:v4:", AUTHORITY = "foundry-job-v4-post-promotion-watch-authority:v1:", MONITOR = "foundry-job-v3-post-promotion-monitor:v1:";
const guard = (key: string, expected: string | undefined): Readonly<{ store: "analysis"; key: string; expected?: string }> => Object.freeze({ store: "analysis" as const, key, ...(expected === undefined ? {} : { expected }) });
const time = (value: unknown): value is string => typeof value === "string" && Number.isFinite(Date.parse(value));

export interface TearFoundryV4PostPromotionMonitorTerminalV1 {
  readonly format: "tear-foundry-v4-post-promotion-monitor-terminal"; readonly schemaVersion: 1;
  readonly authorityHash: string; readonly declarationHash: string; readonly monitorHash: string;
  readonly classification: "observation" | "threshold-breach"; readonly rollbackProvenance: "not-required" | "rollback-ready-not-invoked";
  readonly completedAt: string; readonly terminalHash: string;
}
function terminal(draft: Omit<TearFoundryV4PostPromotionMonitorTerminalV1, "terminalHash">): TearFoundryV4PostPromotionMonitorTerminalV1 {
  if (![draft.authorityHash, draft.declarationHash, draft.monitorHash].every((value) => HASH.test(value)) || !["observation", "threshold-breach"].includes(draft.classification) || !["not-required", "rollback-ready-not-invoked"].includes(draft.rollbackProvenance) || (draft.classification === "observation") !== (draft.rollbackProvenance === "not-required") || !time(draft.completedAt)) throw new TypeError("invalid Foundry V4 post-promotion monitor terminal");
  const value = Object.freeze({ ...draft }); return Object.freeze({ ...value, terminalHash: stableVerificationHash(value) });
}
export function parseTearFoundryV4PostPromotionMonitorTerminal(value: unknown): TearFoundryV4PostPromotionMonitorTerminalV1 {
  if (value === null || typeof value !== "object" || Array.isArray(value)) throw new TypeError("invalid Foundry V4 post-promotion monitor terminal");
  const typed = value as TearFoundryV4PostPromotionMonitorTerminalV1; if (typed.format !== "tear-foundry-v4-post-promotion-monitor-terminal" || typed.schemaVersion !== 1 || !HASH.test(typed.terminalHash)) throw new TypeError("invalid Foundry V4 post-promotion monitor terminal");
  const { terminalHash, ...draft } = typed, parsed = terminal(draft); if (terminalHash !== parsed.terminalHash) throw new TypeError("Foundry V4 post-promotion monitor terminal integrity mismatch"); return parsed;
}

/** Consumes one named retained local Watch aggregate into a disabled V4 terminal. A breach only records rollback-ready provenance; it never invokes rollback. */
export class TearFoundryV4PostPromotionMonitorTerminalExecutor {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore) { if (jobs.backend() !== custody.backend()) throw new TypeError("Foundry V4 monitor terminal must share C31 custody"); this.#jobs = jobs; this.#custody = custody; }
  async terminalize(schedule: TearFoundryJobScheduleV1, source: TearFoundryExecutionBindingV4, monitorHash: string, completedAt: string): Promise<TearFoundryExecutionBindingV4> {
    if (source.payload.kind !== "v3-post-promotion-watch-ready" || source.job.phase !== "monitoring" || source.schedule.scheduleHash !== schedule.scheduleHash || schedule.state !== "disabled" || !HASH.test(monitorHash) || !time(completedAt)) throw new RangeError("Foundry V4 monitor terminal requires a disabled exact Watch authority");
    const backend = this.#jobs.backend(), pointerKey = `${POINTER}${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`, scheduleKey = `foundry-job-schedule:v1:${schedule.id}`, jobKey = `foundry-job:v1:${source.job.id}`, sourceKey = `${BINDING}${source.bindingHash}`, authorityKey = `${AUTHORITY}${source.payload.authorityHash}`, monitorKey = `${MONITOR}${monitorHash}`;
    const [scheduleRaw, jobRaw, sourceRaw, pointerRaw, authorityRaw, monitorRaw] = await Promise.all([backend.get("analysis", scheduleKey), backend.get("analysis", jobKey), backend.get("analysis", sourceKey), backend.get("analysis", pointerKey), backend.get("analysis", authorityKey), backend.get("analysis", monitorKey)]);
    if ([scheduleRaw, jobRaw, sourceRaw, authorityRaw, monitorRaw].some((raw) => raw === undefined) || scheduleRaw !== JSON.stringify(schedule) || sourceRaw !== JSON.stringify(source)) throw new RangeError("Foundry V4 monitor terminal authority changed");
    if (pointerRaw !== source.bindingHash) { const nextRaw = typeof pointerRaw === "string" ? await backend.get("analysis", `${BINDING}${pointerRaw}`) : undefined; try { const next = nextRaw === undefined ? undefined : parseTearFoundryExecutionBindingV4(JSON.parse(nextRaw)); if (next?.payload.kind === "v3-post-promotion-monitor-terminal" && next.payload.monitorHash === monitorHash) return next; } catch { throw new RangeError("Foundry V4 monitor terminal retry evidence is invalid"); } throw new RangeError("Foundry V4 monitor terminal authority changed"); }
    let job; let authority; let monitor;
    try { job = parseTearFoundryJob(JSON.parse(jobRaw ?? "")); authority = parseTearFoundryV4PostPromotionWatchAuthority(JSON.parse(authorityRaw ?? "")); monitor = parseTearFoundryV3PostPromotionMonitorRecord(JSON.parse(monitorRaw ?? "")); } catch { throw new RangeError("Foundry V4 monitor terminal provenance is invalid"); }
    const protocol = requireTearFoundryEvaluationProtocol(job);
    if (job.jobHash !== source.job.jobHash || authority.authorityHash !== source.payload.authorityHash || authority.monitoring.jobHash !== job.jobHash || authority.monitoring.protocolHash !== protocol.protocolHash || authority.monitoring.stopConditionsHash !== job.inputs.stopConditionsHash || monitor.recordHash !== monitorHash || monitor.promotion.approvalHash !== authority.source.approvalHash || monitor.promotion.promotionReceiptHash !== authority.source.promotionReceiptHash || monitor.policy.protocolHash !== authority.monitoring.protocolHash || monitor.policy.stopConditionsHash !== authority.monitoring.stopConditionsHash || monitor.policy.regressionPolicy !== authority.regressionPolicy) throw new RangeError("Foundry V4 monitor terminal lineage changed");
    const declarationKey = `foundry-job-v4-v3-monitoring-declaration:v1:${authority.source.declarationHash}`, approvalKey = `foundry-job-v3-promotion-approval:v1:${authority.source.approvalHash}`, promotionKey = `foundry-job-v3-promotion-receipt:v1:${authority.source.approvalHash}`, activeKey = "policy-active:v1";
    const [declarationRaw, approvalRaw, promotionRaw, activeRaw] = await Promise.all([backend.get("analysis", declarationKey), backend.get("analysis", approvalKey), backend.get("analysis", promotionKey), backend.get("analysis", activeKey)]);
    if ([declarationRaw, approvalRaw, promotionRaw, activeRaw].some((raw) => raw === undefined)) throw new RangeError("Foundry V4 monitor terminal retained provenance disappeared");
    let declaration; let approval; let promotion; let active;
    try { declaration = parseTearFoundryV4V3MonitoringDeclaration(JSON.parse(declarationRaw ?? "")); approval = parseTearFoundryV3PromotionApproval(JSON.parse(approvalRaw ?? "")); promotion = parseTearFoundryV3PromotionReceipt(JSON.parse(promotionRaw ?? "")); active = parseTearPolicyActivation(JSON.parse(activeRaw ?? "")); } catch { throw new RangeError("Foundry V4 monitor terminal retained provenance is invalid"); }
    if (declaration.declarationHash !== authority.source.declarationHash || approval.approvalHash !== authority.source.approvalHash || approval.bridge.bridgeHash !== declaration.bridgeHash || approval.job.jobHash !== job.jobHash || promotion.receiptHash !== authority.source.promotionReceiptHash || promotion.approvalHash !== approval.approvalHash || active.artifactId !== authority.active.artifactId || active.artifactHash !== authority.active.artifactHash || active.activationHash !== authority.active.activationHash || active.revision !== authority.active.revision || monitor.promotion.artifactId !== active.artifactId || monitor.promotion.artifactHash !== active.artifactHash || monitor.promotion.activationHash !== active.activationHash) throw new RangeError("Foundry V4 monitor terminal active promotion changed");
    const artifactKey = `policy-artifact:v1:${active.artifactId}`, artifactRaw = await backend.get("analysis", artifactKey); if (artifactRaw === undefined || parseTearPolicyArtifact(JSON.parse(artifactRaw)).artifactHash !== active.artifactHash) throw new RangeError("Foundry V4 monitor terminal artifact changed");
    const held = await this.#custody.held(completedAt), custody = await Promise.all(authority.custody.map(async (entry) => { const raw = await backend.get("analysis", `academy-candidate-custody:v1:${entry.candidateHash}`); if (raw === undefined || stableVerificationHash(raw) !== entry.rawHash || !held.some((item) => item.recordHash === entry.recordHash)) throw new RangeError("Foundry V4 monitor terminal custody changed"); return Object.freeze({ ...entry, raw }); }));
    const stored = terminal({ format: "tear-foundry-v4-post-promotion-monitor-terminal", schemaVersion: 1, authorityHash: authority.authorityHash, declarationHash: declaration.declarationHash, monitorHash, classification: monitor.classification, rollbackProvenance: monitor.classification === "threshold-breach" ? "rollback-ready-not-invoked" : "not-required", completedAt }), terminalKey = `foundry-job-v4-post-promotion-monitor-terminal:v1:${stored.terminalHash}`, next = createTearFoundryExecutionBindingV4({ schedule: source.schedule, job: source.job, payload: { kind: "v3-post-promotion-monitor-terminal", declarationHash: declaration.declarationHash, monitorHash } });
    try { await backend.commitIfMatches(Object.freeze([guard(scheduleKey, scheduleRaw), guard(jobKey, jobRaw), guard(sourceKey, sourceRaw), guard(pointerKey, source.bindingHash), guard(authorityKey, authorityRaw), guard(monitorKey, monitorRaw), guard(declarationKey, declarationRaw), guard(approvalKey, approvalRaw), guard(promotionKey, promotionRaw), guard(activeKey, activeRaw), guard(artifactKey, artifactRaw), guard(terminalKey, undefined), guard(`${BINDING}${next.bindingHash}`, undefined), ...custody.map((entry) => guard(`academy-candidate-custody:v1:${entry.candidateHash}`, entry.raw))]), Object.freeze([{ store: "analysis", key: terminalKey, value: JSON.stringify(stored) }, { store: "analysis", key: `${BINDING}${next.bindingHash}`, value: JSON.stringify(next) }, { store: "analysis", key: pointerKey, value: next.bindingHash }, { store: "indexes", key: `foundry-job-v4-post-promotion-monitor:${job.id}:${monitorHash}`, value: JSON.stringify(Object.freeze({ declarationHash: declaration.declarationHash, classification: monitor.classification, rollbackProvenance: stored.rollbackProvenance, scheduleState: "disabled" })) }])); } catch { throw new RangeError("Foundry V4 monitor terminal lost its immutable authority or head"); }
    return next;
  }
}
