import { stableVerificationHash } from "../replay/hash";
import type { GhostVaultBackend } from "../ghost";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import { TearFoundryCollectionExecutor } from "./foundry-job-collection";
import { TearFoundryCuratedManifestExecutor, type TearFoundryCuratedManifestRequestV1 } from "./foundry-job-curation";
import type { TearAcademyCorpusStore } from "./academy-corpus";
import type { TearAcademyTrainingDatasetLoader } from "./academy-training-dataset";
import { TearFoundryScheduleController } from "./foundry-job-schedule";
import type { TearFoundryJobScheduleVault } from "./foundry-job-schedule";
import { TearFoundryOfflineTrainingExecutor, TearFoundryOfflineTrainingLaunchVault, type TearFoundryOfflineTrainingRequestV1 } from "./foundry-job-offline-training";
import { createTearFoundrySuccessorExecutionBindingMaterial, TearFoundrySuccessorExecutionBindingMaterialVault, type TearFoundrySuccessorExecutionBindingMaterialV1 } from "./foundry-job-successor-binding-material";
import type { TearFoundryExecutionBindingPayloadV1 } from "./foundry-job-execution-binding";
import { createTearOfflineRlPlan } from "./offline-rl-training";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import type { TearFoundryJobV1 } from "./foundry-job-state";

const ATTEMPT_KEY = "foundry-job-due-attempt:v1:"; const LEASE_KEY = "foundry-job-due-lease:v1:"; const SCHEDULE_KEY = "foundry-job-schedule:v1:"; const JOB_KEY = "foundry-job:v1:"; const HASH = /^[a-f0-9]{16}$/u;
const LEASE_MS = 60_000;
export interface TearFoundryDueLeaseV1 { readonly format: "tear-foundry-due-lease"; readonly schemaVersion: 1; readonly scheduleHash: string; readonly jobHash: string; readonly leaseId: string; readonly actionHash: string; readonly claimedAt: string; readonly expiresAt: string; readonly leaseHash: string; }
export interface TearFoundryDueAttemptReceiptV1 { readonly format: "tear-foundry-due-attempt"; readonly schemaVersion: 1; readonly scheduleHash: string; readonly jobHash: string; readonly attemptedAt: string; readonly leaseId: string; readonly actionHash: string; readonly disposition: "collected" | "no-authorized-corpus" | "not-due" | "blocked"; /** Required only when this receipt has an exact nonterminal successor payload. */ readonly successorExecutionBindingMaterialRequired?: true; readonly receiptHash: string; }
/** A dispatcher result exposes immutable successor-binding material only when the receipt itself proves it is required. */
export type TearFoundryDueAttemptResultV1 = TearFoundryDueAttemptReceiptV1 & Readonly<{ successorExecutionBindingMaterial?: TearFoundrySuccessorExecutionBindingMaterialV1 }>;
/** The dispatcher pins these identities before the existing executor may write one epoch. */
export interface TearFoundryOfflineDueRequestV1 { readonly training: TearFoundryOfflineTrainingRequestV1; readonly manifestHash: string; readonly manifestRootHash: string; readonly datasetHash: string; readonly planHash: string; readonly configurationHash: string; readonly rewardHash: string; }
function time(value: string): boolean { return Number.isFinite(Date.parse(value)); }
function text(value: unknown): value is string { return typeof value === "string" && value.trim().length > 0; }
function guard(key: string, expected: string | undefined): Readonly<{ store: "analysis"; key: string; expected?: string }> { return Object.freeze({ store: "analysis" as const, key, ...(expected === undefined ? {} : { expected }) }); }
function lease(draft: Omit<TearFoundryDueLeaseV1, "leaseHash">): TearFoundryDueLeaseV1 { if (!HASH.test(draft.scheduleHash) || !HASH.test(draft.jobHash) || !text(draft.leaseId) || !HASH.test(draft.actionHash) || !time(draft.claimedAt) || !time(draft.expiresAt) || Date.parse(draft.expiresAt) <= Date.parse(draft.claimedAt)) throw new TypeError("invalid Foundry due lease"); return Object.freeze({ ...draft, leaseHash: stableVerificationHash(draft) }); }
function parseLease(value: string): TearFoundryDueLeaseV1 { const source = JSON.parse(value) as TearFoundryDueLeaseV1; const parsed = lease({ format: source.format, schemaVersion: source.schemaVersion, scheduleHash: source.scheduleHash, jobHash: source.jobHash, leaseId: source.leaseId, actionHash: source.actionHash, claimedAt: source.claimedAt, expiresAt: source.expiresAt }); if (source.leaseHash !== parsed.leaseHash) throw new TypeError("Foundry due lease integrity mismatch"); return parsed; }
function freeze(draft: Omit<TearFoundryDueAttemptReceiptV1, "receiptHash">): TearFoundryDueAttemptReceiptV1 { if (!HASH.test(draft.scheduleHash) || !HASH.test(draft.jobHash) || !time(draft.attemptedAt) || !text(draft.leaseId) || !HASH.test(draft.actionHash) || !["collected", "no-authorized-corpus", "not-due", "blocked"].includes(draft.disposition)) throw new TypeError("invalid Foundry due attempt"); return Object.freeze({ ...draft, receiptHash: stableVerificationHash(draft) }); }
function parseAttempt(value: string): TearFoundryDueAttemptReceiptV1 { const source = JSON.parse(value) as TearFoundryDueAttemptReceiptV1; const parsed = freeze({ format: source.format, schemaVersion: source.schemaVersion, scheduleHash: source.scheduleHash, jobHash: source.jobHash, attemptedAt: source.attemptedAt, leaseId: source.leaseId, actionHash: source.actionHash, disposition: source.disposition, ...(source.successorExecutionBindingMaterialRequired === undefined ? {} : { successorExecutionBindingMaterialRequired: source.successorExecutionBindingMaterialRequired }) }); if (source.receiptHash !== parsed.receiptHash) throw new TypeError("Foundry due attempt integrity mismatch"); return parsed; }
/** Explicit local dispatcher. It has no timer/worker; callers invoke one bounded attempt themselves. */
export class TearFoundryDueDispatcher {
  readonly #backend: GhostVaultBackend; readonly #jobs: TearFoundryJobVault; readonly #schedules: TearFoundryJobScheduleVault; readonly #custody: TearAcademyCandidateCustodyStore; readonly #corpus: TearAcademyCorpusStore | undefined; readonly #loader: TearAcademyTrainingDatasetLoader | undefined;
  constructor(jobs: TearFoundryJobVault, schedules: TearFoundryJobScheduleVault, custody: TearAcademyCandidateCustodyStore, corpus?: TearAcademyCorpusStore, loader?: TearAcademyTrainingDatasetLoader) { if (jobs.backend() !== custody.backend() || (corpus !== undefined && jobs.backend() !== corpus.backend())) throw new TypeError("Foundry due dispatch must share C31 Vault custody"); this.#backend = jobs.backend(); this.#jobs = jobs; this.#schedules = schedules; this.#custody = custody; this.#corpus = corpus; this.#loader = loader; }
  async #result(receipt: TearFoundryDueAttemptReceiptV1): Promise<TearFoundryDueAttemptResultV1> { if (receipt.successorExecutionBindingMaterialRequired === undefined) return receipt; const material = await new TearFoundrySuccessorExecutionBindingMaterialVault(this.#backend).get(receipt.receiptHash); if (material === undefined) throw new RangeError("Foundry successor binding material is unavailable or corrupt"); return Object.freeze({ ...receipt, successorExecutionBindingMaterial: material }); }
  async #persistSuccessorMaterial(receipt: TearFoundryDueAttemptReceiptV1, sourceJobHash: string, successor: Readonly<{ id: string; jobHash: string; phase: TearFoundryJobV1["phase"] }>, payload: TearFoundryExecutionBindingPayloadV1): Promise<TearFoundryDueAttemptResultV1> { if (receipt.successorExecutionBindingMaterialRequired === undefined) throw new RangeError("Foundry successor material requires a bound attempt receipt"); await new TearFoundrySuccessorExecutionBindingMaterialVault(this.#backend).persist(createTearFoundrySuccessorExecutionBindingMaterial({ attemptReceiptHash: receipt.receiptHash, sourceJobHash, successor, payload })); return await this.#result(receipt); }
  async runDueOnce(scheduleHash: string, at: string, budgets: Readonly<{ computeBudgetHash: string; storageBudgetHash: string }>, leaseId: string): Promise<TearFoundryDueAttemptResultV1> {
    if (!HASH.test(scheduleHash) || !HASH.test(budgets.computeBudgetHash) || !HASH.test(budgets.storageBudgetHash) || !time(at) || !leaseId) throw new TypeError("invalid Foundry due dispatch request");
    const schedule = (await this.#schedules.list()).find((entry) => entry.scheduleHash === scheduleHash); if (schedule === undefined) throw new RangeError("Foundry schedule is unavailable");
    const actionHash = stableVerificationHash(Object.freeze({ scheduleHash, jobHash: schedule.jobHash, attemptedAt: at, leaseId, budgets })); const attemptKey = `${ATTEMPT_KEY}${actionHash}`;
    const existing = await this.#backend.get("analysis", attemptKey); let existingReceipt: TearFoundryDueAttemptReceiptV1 | undefined; if (existing !== undefined) { try { existingReceipt = parseAttempt(existing); } catch { await this.#backend.put("quarantine", attemptKey, existing); } } if (existingReceipt?.actionHash === actionHash) return await this.#result(existingReceipt);
    const job = await this.#jobs.get(schedule.jobId); const controller = new TearFoundryScheduleController(this.#jobs, this.#schedules, { held: async (candidate, when) => {
      const held = await this.#custody.held(when); return candidate.inputs.corpusRecordHashes.every((hash) => held.some((record) => record.recordHash === hash));
    } }); const projection = (await controller.discoverDue(at)).find((entry) => entry.scheduleHash === scheduleHash);
    if (job === undefined) throw new RangeError("Foundry scheduled job is unavailable");
    const scheduleRaw = await this.#backend.get("analysis", `${SCHEDULE_KEY}${schedule.id}`), jobRaw = await this.#backend.get("analysis", `${JOB_KEY}${job.id}`); if (scheduleRaw === undefined || jobRaw === undefined) throw new RangeError("Foundry schedule or job disappeared before claim");
    const custodyGuards = await Promise.all((await this.#custody.inventory()).records.filter((record) => job.inputs.corpusRecordHashes.includes(record.recordHash)).map(async (record) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, await this.#backend.get("analysis", `academy-candidate-custody:v1:${record.candidateHash}`))));
    const leaseKey = `${LEASE_KEY}${scheduleHash}`, priorRaw = await this.#backend.get("analysis", leaseKey); let prior: TearFoundryDueLeaseV1 | undefined;
    if (priorRaw !== undefined) { try { prior = parseLease(priorRaw); } catch { await this.#backend.put("quarantine", leaseKey, priorRaw); throw new RangeError("Foundry due lease is corrupt"); } }
    if (prior !== undefined && Date.parse(prior.expiresAt) > Date.parse(at)) throw new RangeError("Foundry due dispatch is already leased");
    const claimed = lease({ format: "tear-foundry-due-lease", schemaVersion: 1, scheduleHash, jobHash: job.jobHash, leaseId, actionHash, claimedAt: at, expiresAt: new Date(Date.parse(at) + LEASE_MS).toISOString() }); const claimedRaw = JSON.stringify(claimed);
    try { await this.#backend.commitIfMatches(Object.freeze([guard(`${SCHEDULE_KEY}${schedule.id}`, scheduleRaw), guard(`${JOB_KEY}${job.id}`, jobRaw), ...custodyGuards, guard(leaseKey, priorRaw)]), Object.freeze([{ store: "analysis", key: leaseKey, value: claimedRaw }])); } catch { throw new RangeError("Foundry due claim lost its current schedule, job, custody, or lease"); }
    let receipt: TearFoundryDueAttemptReceiptV1;
    try {
      if (schedule.computeBudgetHash !== budgets.computeBudgetHash || schedule.storageBudgetHash !== budgets.storageBudgetHash || projection?.disposition !== "due" || job.phase !== "created") receipt = freeze({ format: "tear-foundry-due-attempt", schemaVersion: 1, scheduleHash, jobHash: job.jobHash, attemptedAt: at, leaseId, actionHash, disposition: projection?.disposition === "due" ? "blocked" : "not-due" });
      else { const result = await new TearFoundryCollectionExecutor(this.#jobs, this.#custody).collect(job, at); receipt = freeze({ format: "tear-foundry-due-attempt", schemaVersion: 1, scheduleHash, jobHash: job.jobHash, attemptedAt: at, leaseId, actionHash, disposition: result.receipt.disposition === "authorized" ? "collected" : "no-authorized-corpus" }); }
    } catch (error) { await this.#backend.commitIfMatches(Object.freeze([guard(leaseKey, claimedRaw)]), Object.freeze([{ store: "analysis", key: leaseKey }])); throw error; }
    await this.#backend.commitIfMatches(Object.freeze([guard(leaseKey, claimedRaw)]), Object.freeze([{ store: "analysis", key: attemptKey, value: JSON.stringify(receipt) }, { store: "indexes", key: `foundry-job-due-attempt:${scheduleHash}:${receipt.receiptHash}`, value: JSON.stringify(Object.freeze({ disposition: receipt.disposition, leaseId, actionHash })) }, { store: "analysis", key: leaseKey }])); return await this.#result(receipt);
  }
  /** One separate, lease-bound legal successor: a collecting head may only admit its declared trainer manifest. */
  async runManifestAdmissionDueOnce(scheduleHash: string, request: TearFoundryCuratedManifestRequestV1, at: string, budgets: Readonly<{ computeBudgetHash: string; storageBudgetHash: string }>, leaseId: string): Promise<TearFoundryDueAttemptResultV1> {
    if (!HASH.test(scheduleHash) || !HASH.test(budgets.computeBudgetHash) || !HASH.test(budgets.storageBudgetHash) || !time(at) || !text(leaseId)) throw new TypeError("invalid Foundry manifest dispatch request");
    const corpus = this.#corpus; if (corpus === undefined) throw new TypeError("Foundry manifest dispatch requires a shared C31 corpus store"); const corpusStore: TearAcademyCorpusStore = corpus;
    const schedule = (await this.#schedules.list()).find((entry) => entry.scheduleHash === scheduleHash); if (schedule === undefined) throw new RangeError("Foundry manifest schedule is unavailable");
    const job = await this.#jobs.get(schedule.jobId); if (job === undefined) throw new RangeError("Foundry manifest dispatch is not authorized");
    const actionHash = stableVerificationHash(Object.freeze({ kind: "manifest-admission", scheduleHash, jobHash: schedule.jobHash, request, attemptedAt: at, leaseId, budgets })), attemptKey = `${ATTEMPT_KEY}${actionHash}`, leaseKey = `${LEASE_KEY}${scheduleHash}`;
    const old = await this.#backend.get("analysis", attemptKey); let existingReceipt: TearFoundryDueAttemptReceiptV1 | undefined; if (old !== undefined) { try { existingReceipt = parseAttempt(old); } catch { await this.#backend.put("quarantine", attemptKey, old); } } if (existingReceipt?.actionHash === actionHash) return await this.#result(existingReceipt);
    if (job.phase !== "collecting" || schedule.computeBudgetHash !== budgets.computeBudgetHash || schedule.storageBudgetHash !== budgets.storageBudgetHash || schedule.stopConditionsHash !== job.inputs.stopConditionsHash) throw new RangeError("Foundry manifest dispatch is not authorized");
    const scheduleRaw = await this.#backend.get("analysis", `${SCHEDULE_KEY}${schedule.id}`), jobRaw = await this.#backend.get("analysis", `${JOB_KEY}${job.id}`), priorRaw = await this.#backend.get("analysis", leaseKey); if (scheduleRaw === undefined || jobRaw === undefined) throw new RangeError("Foundry manifest state disappeared");
    if (priorRaw !== undefined && Date.parse(parseLease(priorRaw).expiresAt) > Date.parse(at)) throw new RangeError("Foundry manifest dispatch is already leased");
    const controller = new TearFoundryScheduleController(this.#jobs, this.#schedules, { held: async (candidate, when) => {
      const held = await this.#custody.held(when); return candidate.inputs.corpusRecordHashes.every((hash) => held.some((record) => record.recordHash === hash));
    } });
    const projection = (await controller.discoverDue(at)).find((entry) => entry.scheduleHash === scheduleHash);
    if (projection?.disposition !== "due") throw new RangeError("Foundry manifest dispatch is not due");
    const [held, inventory] = await Promise.all([this.#custody.held(at), this.#custody.inventory()]);
    if (!job.inputs.corpusRecordHashes.every((hash) => held.some((record) => record.recordHash === hash))) throw new RangeError("Foundry manifest custody is revoked");
    const custodyGuards = await Promise.all(inventory.records.filter((record) => job.inputs.corpusRecordHashes.includes(record.recordHash)).map(async (record) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, await this.#backend.get("analysis", `academy-candidate-custody:v1:${record.candidateHash}`))));
    if (custodyGuards.length !== job.inputs.corpusRecordHashes.length) throw new RangeError("Foundry manifest custody is unavailable");
    const claimed = lease({ format: "tear-foundry-due-lease", schemaVersion: 1, scheduleHash, jobHash: job.jobHash, leaseId, actionHash, claimedAt: at, expiresAt: new Date(Date.parse(at) + LEASE_MS).toISOString() }), claimedRaw = JSON.stringify(claimed);
    try { await this.#backend.commitIfMatches(Object.freeze([guard(`${SCHEDULE_KEY}${schedule.id}`, scheduleRaw), guard(`${JOB_KEY}${job.id}`, jobRaw), ...custodyGuards, guard(leaseKey, priorRaw)]), Object.freeze([{ store: "analysis", key: leaseKey, value: claimedRaw }])); } catch { throw new RangeError("Foundry manifest claim lost its current schedule, job, custody, or lease"); }
    try { const result = await new TearFoundryCuratedManifestExecutor(this.#jobs, this.#custody, corpusStore).admit(job, request, at), receipt = freeze({ format: "tear-foundry-due-attempt", schemaVersion: 1, scheduleHash, jobHash: job.jobHash, attemptedAt: at, leaseId, actionHash, disposition: result.receipt.disposition === "authorized" ? "collected" : "no-authorized-corpus" }); await this.#backend.commitIfMatches(Object.freeze([guard(leaseKey, claimedRaw)]), Object.freeze([{ store: "analysis", key: attemptKey, value: JSON.stringify(receipt) }, { store: "analysis", key: leaseKey }])); return await this.#result(receipt); } catch (error) { await this.#backend.commitIfMatches(Object.freeze([guard(leaseKey, claimedRaw)]), Object.freeze([{ store: "analysis", key: leaseKey }])); throw error; }
  }
  /** One bounded C34 epoch only: a due curating head may invoke its existing immutable offline launch. */
  async runOfflineTrainingDueOnce(scheduleHash: string, request: TearFoundryOfflineDueRequestV1, at: string, budgets: Readonly<{ computeBudgetHash: string; storageBudgetHash: string }>, leaseId: string): Promise<TearFoundryDueAttemptResultV1> {
    if (!HASH.test(scheduleHash) || !HASH.test(budgets.computeBudgetHash) || !HASH.test(budgets.storageBudgetHash) || ![request.manifestHash, request.manifestRootHash, request.datasetHash, request.planHash, request.configurationHash, request.rewardHash].every((value) => HASH.test(value)) || !time(at) || !text(leaseId)) throw new TypeError("invalid Foundry offline due dispatch request");
    const corpus = this.#corpus, loader = this.#loader; if (corpus === undefined || loader === undefined) throw new TypeError("Foundry offline dispatch requires shared C31 corpus and dataset loader");
    const schedule = (await this.#schedules.list()).find((entry) => entry.scheduleHash === scheduleHash); if (schedule === undefined) throw new RangeError("Foundry offline schedule is unavailable");
    const job = await this.#jobs.get(schedule.jobId); if (job === undefined) throw new RangeError("Foundry offline dispatch is not authorized");
    const actionHash = stableVerificationHash(Object.freeze({ kind: "offline-training", scheduleHash, jobHash: schedule.jobHash, request, attemptedAt: at, leaseId, budgets })), attemptKey = `${ATTEMPT_KEY}${actionHash}`, leaseKey = `${LEASE_KEY}${scheduleHash}`;
    const old = await this.#backend.get("analysis", attemptKey); let existingReceipt: TearFoundryDueAttemptReceiptV1 | undefined; if (old !== undefined) { try { existingReceipt = parseAttempt(old); } catch { await this.#backend.put("quarantine", attemptKey, old); } } if (existingReceipt?.actionHash === actionHash) return await this.#result(existingReceipt);
    if (job.phase !== "curating") throw new RangeError(`Foundry offline dispatch phase is ${job.phase}`);
    if (schedule.computeBudgetHash !== budgets.computeBudgetHash || schedule.storageBudgetHash !== budgets.storageBudgetHash) throw new RangeError("Foundry offline dispatch budget is not authorized");
    if (schedule.stopConditionsHash !== job.inputs.stopConditionsHash) throw new RangeError("Foundry offline dispatch stop identity is not authorized");
    const [scheduleRaw, jobRaw, priorRaw, held, inventory] = await Promise.all([this.#backend.get("analysis", `${SCHEDULE_KEY}${schedule.id}`), this.#backend.get("analysis", `${JOB_KEY}${job.id}`), this.#backend.get("analysis", leaseKey), this.#custody.held(at), this.#custody.inventory()]);
    if (scheduleRaw === undefined || jobRaw === undefined) throw new RangeError("Foundry offline state disappeared"); if (priorRaw !== undefined && Date.parse(parseLease(priorRaw).expiresAt) > Date.parse(at)) throw new RangeError("Foundry offline dispatch is already leased");
    const controller = new TearFoundryScheduleController(this.#jobs, this.#schedules, { held: async (candidate, when) => { const live = await this.#custody.held(when); return candidate.inputs.corpusRecordHashes.every((hash) => live.some((record) => record.recordHash === hash)); } });
    if ((await controller.discoverDue(at)).find((entry) => entry.scheduleHash === scheduleHash)?.disposition !== "due") throw new RangeError("Foundry offline dispatch is not due");
    if (!job.inputs.corpusRecordHashes.every((hash) => held.some((record) => record.recordHash === hash))) throw new RangeError("Foundry offline custody is revoked");
    const custodyGuards = await Promise.all(inventory.records.filter((record) => job.inputs.corpusRecordHashes.includes(record.recordHash)).map(async (record) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, await this.#backend.get("analysis", `academy-candidate-custody:v1:${record.candidateHash}`)))); if (custodyGuards.length !== job.inputs.corpusRecordHashes.length) throw new RangeError("Foundry offline custody is unavailable");
    const [manifest, dataset] = await Promise.all([corpus.getManifest(request.training.manifestId, { kind: "trainer", id: request.training.trainerId }, request.training.manifestVersion), loader.load({ manifestId: request.training.manifestId, trainerId: request.training.trainerId, version: request.training.manifestVersion })]);
    const plan = createTearOfflineRlPlan(dataset, request.training.plan);
    if (manifest?.manifestHash !== request.manifestHash || manifest.rootHash !== request.manifestRootHash || dataset.datasetHash !== request.datasetHash || dataset.manifest.manifestHash !== request.manifestHash || dataset.manifest.rootHash !== request.manifestRootHash || plan.planHash !== request.planHash || stableVerificationHash(request.training.config) !== request.configurationHash || plan.reward.rewardHash !== request.rewardHash || plan.reward.rewardHash !== job.inputs.rewardDefinitionHash) throw new RangeError("Foundry offline immutable lineage changed");
    const claimed = lease({ format: "tear-foundry-due-lease", schemaVersion: 1, scheduleHash, jobHash: job.jobHash, leaseId, actionHash, claimedAt: at, expiresAt: new Date(Date.parse(at) + LEASE_MS).toISOString() }), claimedRaw = JSON.stringify(claimed);
    try { await this.#backend.commitIfMatches(Object.freeze([guard(`${SCHEDULE_KEY}${schedule.id}`, scheduleRaw), guard(`${JOB_KEY}${job.id}`, jobRaw), ...custodyGuards, guard(leaseKey, priorRaw)]), Object.freeze([{ store: "analysis", key: leaseKey, value: claimedRaw }])); } catch { throw new RangeError("Foundry offline claim lost its current schedule, job, custody, or lease"); }
    try { const result = await new TearFoundryOfflineTrainingExecutor(this.#jobs, this.#custody, corpus, loader).start(job, request.training, at), receipt = freeze({ format: "tear-foundry-due-attempt", schemaVersion: 1, scheduleHash, jobHash: schedule.jobHash, attemptedAt: at, leaseId, actionHash, disposition: "collected", successorExecutionBindingMaterialRequired: true }); const output = await this.#persistSuccessorMaterial(receipt, job.jobHash, { id: result.job.id, jobHash: result.job.jobHash, phase: result.job.phase }, { kind: "offline-resume", launchHash: result.launch.launchHash }); await this.#backend.commitIfMatches(Object.freeze([guard(leaseKey, claimedRaw)]), Object.freeze([{ store: "analysis", key: attemptKey, value: JSON.stringify(receipt) }, { store: "analysis", key: leaseKey }])); return output; } catch (error) { await this.#backend.commitIfMatches(Object.freeze([guard(leaseKey, claimedRaw)]), Object.freeze([{ store: "analysis", key: leaseKey }])); throw error; }
  }
  /** A V2 training head may resume exactly one existing offline checkpoint epoch. */
  async runOfflineResumeDueOnce(scheduleHash: string, launchHash: string, at: string, budgets: Readonly<{ computeBudgetHash: string; storageBudgetHash: string }>, leaseId: string): Promise<TearFoundryDueAttemptResultV1> {
    if (!HASH.test(scheduleHash) || !HASH.test(launchHash) || !HASH.test(budgets.computeBudgetHash) || !HASH.test(budgets.storageBudgetHash) || !time(at) || !text(leaseId)) throw new TypeError("invalid Foundry offline resume request");
    const corpus = this.#corpus, loader = this.#loader; if (corpus === undefined || loader === undefined) throw new TypeError("Foundry offline resume requires shared C31 corpus and dataset loader");
    const schedule = (await this.#schedules.list()).find((entry) => entry.scheduleHash === scheduleHash); if (schedule === undefined) throw new RangeError("Foundry offline resume schedule is unavailable"); const job = await this.#jobs.get(schedule.jobId); if (job === undefined) throw new RangeError("Foundry offline resume job is unavailable");
    const actionHash = stableVerificationHash(Object.freeze({ kind: "offline-resume", scheduleHash, jobHash: schedule.jobHash, launchHash, attemptedAt: at, leaseId, budgets })), attemptKey = `${ATTEMPT_KEY}${actionHash}`, leaseKey = `${LEASE_KEY}${scheduleHash}`, old = await this.#backend.get("analysis", attemptKey); let existingReceipt: TearFoundryDueAttemptReceiptV1 | undefined; if (old !== undefined) { try { existingReceipt = parseAttempt(old); } catch { await this.#backend.put("quarantine", attemptKey, old); } } if (existingReceipt?.actionHash === actionHash) return await this.#result(existingReceipt);
    if (job.phase !== "training" || schedule.computeBudgetHash !== budgets.computeBudgetHash || schedule.storageBudgetHash !== budgets.storageBudgetHash || schedule.stopConditionsHash !== job.inputs.stopConditionsHash) throw new RangeError("Foundry offline resume is not authorized");
    const launch = await new TearFoundryOfflineTrainingLaunchVault(this.#backend).get(launchHash); if (launch?.job.id !== job.id || launch.job.resultJobHash !== job.jobHash || launch.plan.reward.rewardHash !== job.inputs.rewardDefinitionHash) throw new RangeError("Foundry offline resume V2 lineage is unavailable");
    const [scheduleRaw, jobRaw, priorRaw, held, inventory] = await Promise.all([this.#backend.get("analysis", `${SCHEDULE_KEY}${schedule.id}`), this.#backend.get("analysis", `${JOB_KEY}${job.id}`), this.#backend.get("analysis", leaseKey), this.#custody.held(at), this.#custody.inventory()]); if (scheduleRaw === undefined || jobRaw === undefined || (priorRaw !== undefined && Date.parse(parseLease(priorRaw).expiresAt) > Date.parse(at))) throw new RangeError("Foundry offline resume lease is unavailable");
    const controller = new TearFoundryScheduleController(this.#jobs, this.#schedules, { held: async (candidate, when) => { const live = await this.#custody.held(when); return candidate.inputs.corpusRecordHashes.every((hash) => live.some((record) => record.recordHash === hash)); } }); if ((await controller.discoverDue(at)).find((entry) => entry.scheduleHash === scheduleHash)?.disposition !== "due" || !job.inputs.corpusRecordHashes.every((hash) => held.some((record) => record.recordHash === hash))) throw new RangeError("Foundry offline resume is not due or custody is revoked");
    const guards = await Promise.all(inventory.records.filter((record) => job.inputs.corpusRecordHashes.includes(record.recordHash)).map(async (record) => guard(`academy-candidate-custody:v1:${record.candidateHash}`, await this.#backend.get("analysis", `academy-candidate-custody:v1:${record.candidateHash}`)))); if (guards.length !== job.inputs.corpusRecordHashes.length) throw new RangeError("Foundry offline resume custody is unavailable"); const claimed = lease({ format: "tear-foundry-due-lease", schemaVersion: 1, scheduleHash, jobHash: job.jobHash, leaseId, actionHash, claimedAt: at, expiresAt: new Date(Date.parse(at) + LEASE_MS).toISOString() }), claimedRaw = JSON.stringify(claimed);
    try { await this.#backend.commitIfMatches(Object.freeze([guard(`${SCHEDULE_KEY}${schedule.id}`, scheduleRaw), guard(`${JOB_KEY}${job.id}`, jobRaw), ...guards, guard(leaseKey, priorRaw)]), Object.freeze([{ store: "analysis", key: leaseKey, value: claimedRaw }])); } catch { throw new RangeError("Foundry offline resume claim lost lineage"); }
    try { const result = await new TearFoundryOfflineTrainingExecutor(this.#jobs, this.#custody, corpus, loader).resume(job, launchHash, at); const receipt = freeze({ format: "tear-foundry-due-attempt", schemaVersion: 1, scheduleHash, jobHash: schedule.jobHash, attemptedAt: at, leaseId, actionHash, disposition: "collected", successorExecutionBindingMaterialRequired: true }); const output = await this.#persistSuccessorMaterial(receipt, job.jobHash, { id: result.job.id, jobHash: result.job.jobHash, phase: result.job.phase }, { kind: "offline-resume", launchHash: result.launch.launchHash }); await this.#backend.commitIfMatches(Object.freeze([guard(leaseKey, claimedRaw)]), Object.freeze([{ store: "analysis", key: attemptKey, value: JSON.stringify(receipt) }, { store: "analysis", key: leaseKey }])); return output; } catch (error) { await this.#backend.commitIfMatches(Object.freeze([guard(leaseKey, claimedRaw)]), Object.freeze([{ store: "analysis", key: leaseKey }])); throw error; }
  }
}
