import { stableVerificationHash } from "../replay/hash";
import type { TearAcademyCandidateCustodyStore } from "./academy-candidate-custody";
import { parseTearFoundryJob, requireTearFoundryEvaluationProtocol } from "./foundry-job-state";
import type { TearFoundryJobScheduleV1 } from "./foundry-job-schedule";
import type { TearFoundryJobVault } from "./foundry-job-vault";
import { TearFoundryV3PostPromotionRollbackExecutor } from "./foundry-job-v3-post-promotion-rollback";
import { parseTearFoundryV3PostPromotionMonitorRecord } from "./foundry-job-v3-post-promotion-monitor";
import { parseTearFoundryV3PromotionApproval } from "./foundry-job-v3-promotion-approval";
import { parseTearFoundryV3PromotionReceipt } from "./foundry-job-v3-promotion";
import { createTearFoundryExecutionBindingV4, parseTearFoundryExecutionBindingV4, type TearFoundryExecutionBindingV4 } from "./foundry-job-v4-offline-terminal";
import { parseTearFoundryV4PostPromotionMonitorTerminal } from "./foundry-job-v4-post-promotion-monitor-terminal";
import { parseTearFoundryV4PostPromotionWatchAuthority } from "./foundry-job-v4-post-promotion-watch-authority";
import { parseTearFoundryV4V3MonitoringDeclaration } from "./foundry-job-v4-v3-monitoring-bridge";
import { parseTearPolicyActivation, parseTearPolicyArtifact } from "./policy-artifact-registry";

const HASH = /^[a-f0-9]{16}$/u, BINDING = "foundry-job-execution-binding:v4:", POINTER = "foundry-job-execution-binding-current:v4:";
const guard = (key: string, expected: string | undefined, store: "analysis" | "indexes" = "analysis") => Object.freeze({ store, key, ...(expected === undefined ? {} : { expected }) });
const time = (value: unknown): value is string => typeof value === "string" && Number.isFinite(Date.parse(value));

/** A direct-only V4 handoff: a recorded breach may restore its frozen baseline once, but this class never schedules or triggers itself. */
export class TearFoundryV4PostPromotionRollbackExecutor {
  readonly #jobs: TearFoundryJobVault; readonly #custody: TearAcademyCandidateCustodyStore;
  constructor(jobs: TearFoundryJobVault, custody: TearAcademyCandidateCustodyStore) { if (jobs.backend() !== custody.backend()) throw new TypeError("Foundry V4 rollback must share C31 custody"); this.#jobs = jobs; this.#custody = custody; }
  async rollback(schedule: TearFoundryJobScheduleV1, source: TearFoundryExecutionBindingV4, terminalHash: string, rolledBackAt: string): Promise<TearFoundryExecutionBindingV4> {
    if (source.payload.kind !== "v3-post-promotion-monitor-terminal" || source.job.phase !== "monitoring" || source.schedule.scheduleHash !== schedule.scheduleHash || schedule.state !== "disabled" || !HASH.test(terminalHash) || !time(rolledBackAt)) throw new RangeError("Foundry V4 rollback requires a disabled exact breach terminal");
    const backend = this.#jobs.backend(), p = source.payload, scheduleKey = `foundry-job-schedule:v1:${schedule.id}`, jobKey = `foundry-job:v1:${source.job.id}`, sourceKey = `${BINDING}${source.bindingHash}`, pointerKey = `${POINTER}${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`, terminalKey = `foundry-job-v4-post-promotion-monitor-terminal:v1:${terminalHash}`;
    const [scheduleRaw, jobRaw, sourceRaw, pointerRaw, terminalRaw] = await Promise.all([backend.get("analysis", scheduleKey), backend.get("analysis", jobKey), backend.get("analysis", sourceKey), backend.get("analysis", pointerKey), backend.get("analysis", terminalKey)]);
    if ([scheduleRaw, jobRaw, sourceRaw, terminalRaw].some((raw) => raw === undefined) || scheduleRaw !== JSON.stringify(schedule) || sourceRaw !== JSON.stringify(source)) throw new RangeError("Foundry V4 rollback authority changed");
    if (pointerRaw !== source.bindingHash) { const nextRaw = typeof pointerRaw === "string" ? await backend.get("analysis", `${BINDING}${pointerRaw}`) : undefined; try { const next = nextRaw === undefined ? undefined : parseTearFoundryExecutionBindingV4(JSON.parse(nextRaw)); if (next?.payload.kind === "v3-post-promotion-rollback-terminal" && next.payload.terminalHash === terminalHash) return next; } catch { throw new RangeError("Foundry V4 rollback retry evidence is invalid"); } throw new RangeError("Foundry V4 rollback authority changed"); }
    let job; let terminal;
    try { job = parseTearFoundryJob(JSON.parse(jobRaw ?? "")); terminal = parseTearFoundryV4PostPromotionMonitorTerminal(JSON.parse(terminalRaw ?? "")); } catch { throw new RangeError("Foundry V4 rollback terminal is invalid"); }
    if (job.jobHash !== source.job.jobHash || terminal.terminalHash !== terminalHash || terminal.declarationHash !== p.declarationHash || terminal.monitorHash !== p.monitorHash || terminal.classification !== "threshold-breach" || terminal.rollbackProvenance !== "rollback-ready-not-invoked") throw new RangeError("Foundry V4 rollback requires an exact rollback-ready breach");
    const authorityKey = `foundry-job-v4-post-promotion-watch-authority:v1:${terminal.authorityHash}`, monitorKey = `foundry-job-v3-post-promotion-monitor:v1:${p.monitorHash}`;
    const [authorityRaw, monitorRaw] = await Promise.all([backend.get("analysis", authorityKey), backend.get("analysis", monitorKey)]);
    if (authorityRaw === undefined || monitorRaw === undefined) throw new RangeError("Foundry V4 rollback Watch provenance disappeared");
    let authority; let monitor;
    try { authority = parseTearFoundryV4PostPromotionWatchAuthority(JSON.parse(authorityRaw)); monitor = parseTearFoundryV3PostPromotionMonitorRecord(JSON.parse(monitorRaw)); } catch { throw new RangeError("Foundry V4 rollback Watch provenance is invalid"); }
    const protocol = requireTearFoundryEvaluationProtocol(job);
    if (authority.authorityHash !== terminal.authorityHash || authority.monitoring.jobHash !== job.jobHash || authority.monitoring.protocolHash !== protocol.protocolHash || authority.monitoring.stopConditionsHash !== job.inputs.stopConditionsHash || monitor.recordHash !== p.monitorHash || monitor.classification !== terminal.classification || monitor.promotion.approvalHash !== authority.source.approvalHash || monitor.promotion.promotionReceiptHash !== authority.source.promotionReceiptHash) throw new RangeError("Foundry V4 rollback monitor lineage changed");
    const declarationKey = `foundry-job-v4-v3-monitoring-declaration:v1:${p.declarationHash}`, approvalKey = `foundry-job-v3-promotion-approval:v1:${authority.source.approvalHash}`, promotionKey = `foundry-job-v3-promotion-receipt:v1:${authority.source.approvalHash}`, activeKey = "policy-active:v1";
    const [declarationRaw, approvalRaw, promotionRaw, activeRaw] = await Promise.all([backend.get("analysis", declarationKey), backend.get("analysis", approvalKey), backend.get("analysis", promotionKey), backend.get("analysis", activeKey)]);
    if ([declarationRaw, approvalRaw, promotionRaw, activeRaw].some((raw) => raw === undefined)) throw new RangeError("Foundry V4 rollback retained provenance disappeared");
    let declaration; let approval; let promotion; let active;
    try { declaration = parseTearFoundryV4V3MonitoringDeclaration(JSON.parse(declarationRaw ?? "")); approval = parseTearFoundryV3PromotionApproval(JSON.parse(approvalRaw ?? "")); promotion = parseTearFoundryV3PromotionReceipt(JSON.parse(promotionRaw ?? "")); active = parseTearPolicyActivation(JSON.parse(activeRaw ?? "")); } catch { throw new RangeError("Foundry V4 rollback retained provenance is invalid"); }
    if (declaration.declarationHash !== p.declarationHash || approval.approvalHash !== authority.source.approvalHash || approval.bridge.bridgeHash !== declaration.bridgeHash || promotion.receiptHash !== authority.source.promotionReceiptHash || promotion.activationHash !== active.activationHash || active.artifactId !== authority.active.artifactId || active.artifactHash !== authority.active.artifactHash || active.revision !== authority.active.revision || approval.rollbackBaseline === undefined) throw new RangeError("Foundry V4 rollback active provenance changed");
    const artifactKey = `policy-artifact:v1:${active.artifactId}`, baselineKey = `policy-activation:v1:${String(approval.rollbackBaseline.revision).padStart(12, "0")}`;
    const [artifactRaw, baselineRaw, held] = await Promise.all([backend.get("analysis", artifactKey), backend.get("indexes", baselineKey), this.#custody.held(rolledBackAt)]);
    if (artifactRaw === undefined || baselineRaw === undefined || parseTearPolicyArtifact(JSON.parse(artifactRaw)).artifactHash !== active.artifactHash) throw new RangeError("Foundry V4 rollback active artifact or baseline changed");
    const baseline = parseTearPolicyActivation(JSON.parse(baselineRaw)); if (baseline.activationHash !== approval.rollbackBaseline.activationHash || baseline.artifactHash !== approval.rollbackBaseline.artifactHash || !job.inputs.corpusRecordHashes.every((hash) => held.some((entry) => entry.recordHash === hash))) throw new RangeError("Foundry V4 rollback baseline or custody changed");
    const custody = await Promise.all(authority.custody.map(async (entry) => { const raw = await backend.get("analysis", `academy-candidate-custody:v1:${entry.candidateHash}`); if (raw === undefined || stableVerificationHash(raw) !== entry.rawHash || !held.some((item) => item.recordHash === entry.recordHash)) throw new RangeError("Foundry V4 rollback custody changed"); return Object.freeze({ ...entry, raw }); }));
    const rollback = await new TearFoundryV3PostPromotionRollbackExecutor(this.#jobs, this.#custody).rollback(p.monitorHash, rolledBackAt, {
      guards: (receipt) => { const next = createTearFoundryExecutionBindingV4({ schedule: source.schedule, job: source.job, payload: { kind: "v3-post-promotion-rollback-terminal", declarationHash: p.declarationHash, monitorHash: p.monitorHash, terminalHash, rollbackReceiptHash: receipt.receiptHash } }); return Object.freeze([guard(scheduleKey, scheduleRaw), guard(jobKey, jobRaw), guard(sourceKey, sourceRaw), guard(pointerKey, source.bindingHash), guard(terminalKey, terminalRaw), guard(authorityKey, authorityRaw), guard(declarationKey, declarationRaw), guard(approvalKey, approvalRaw), guard(promotionKey, promotionRaw), guard(activeKey, activeRaw), guard(artifactKey, artifactRaw), guard(baselineKey, baselineRaw, "indexes"), guard(`${BINDING}${next.bindingHash}`, undefined), ...custody.map((entry) => guard(`academy-candidate-custody:v1:${entry.candidateHash}`, entry.raw))]); },
      writes: (receipt) => { const next = createTearFoundryExecutionBindingV4({ schedule: source.schedule, job: source.job, payload: { kind: "v3-post-promotion-rollback-terminal", declarationHash: p.declarationHash, monitorHash: p.monitorHash, terminalHash, rollbackReceiptHash: receipt.receiptHash } }); return Object.freeze([{ store: "analysis" as const, key: `${BINDING}${next.bindingHash}`, value: JSON.stringify(next) }, { store: "analysis" as const, key: pointerKey, value: next.bindingHash }, { store: "indexes" as const, key: `foundry-job-v4-post-promotion-rollback:${job.id}:${terminalHash}`, value: JSON.stringify({ declarationHash: p.declarationHash, monitorHash: p.monitorHash, rollbackReceiptHash: receipt.receiptHash, scheduleState: "disabled" }) }]); },
    });
    const nextRaw = await backend.get("analysis", pointerKey); const next = nextRaw === undefined ? undefined : await backend.get("analysis", `${BINDING}${nextRaw}`); if (next === undefined) throw new RangeError("Foundry V4 rollback terminal was not retained"); const parsed = parseTearFoundryExecutionBindingV4(JSON.parse(next)); if (parsed.payload.kind !== "v3-post-promotion-rollback-terminal" || parsed.payload.rollbackReceiptHash !== rollback.receiptHash) throw new RangeError("Foundry V4 rollback terminal changed"); return parsed;
  }
}
