import type { GhostVaultBackend } from "../ghost";
import type { CanonicalGameplayState } from "../gameplay/runtime/canonical-state";
import { stableVerificationHash } from "../replay/hash";
import { createProductionHeadlessEnvironment, type ProductionHeadlessCheckpoint, type TearScenarioV1 } from "../tearbench";
import { createTearC34C32RuntimeModel, selectTearC34C32RuntimeAction } from "./c34-c32-runtime-compatibility";
import { evaluateTearOfflineRlRewardTransition, parseTearOfflineRlPlan, type TearOfflineRlPlanV1, type TearOfflineRlQValueV1 } from "./offline-rl-training";
import { parseTearOfflineRlV3Plan, parseTearOfflineRlV3TrainingResult, type TearOfflineRlV3PlanV1, type TearOfflineRlV3TrainingResultV1 } from "./offline-rl-v3-training";

const HASH = /^[a-f0-9]{16}$/u;
const KEY = "online-rl-v3-checkpoint:v1:";
const RESULT_KEY = "online-rl-v3-evaluation:v1:";
type Status = "running" | "complete" | "cancelled" | "timed-out" | "stopped-divergence";

export interface TearOnlineRlV3ConfigV1 { readonly learningRate: number; readonly gamma: number; readonly maxTicks: number; readonly maxUpdates: number; readonly maxAbsoluteQ: number; }
export interface TearOnlineRlV3PlanV1 { readonly format: "tear-online-rl-v3-plan"; readonly schemaVersion: 1; readonly id: string; readonly offline: Readonly<{ v3PlanHash: string; trainingHash: string; rewardPlanHash: string; receiptHash: string; adapterHash: string; actionVocabularyHash: string }>; readonly scenarios: readonly TearScenarioV1[]; readonly config: TearOnlineRlV3ConfigV1; readonly planHash: string; }
export interface TearOnlineRlV3CheckpointV1 { readonly format: "tear-online-rl-v3-checkpoint"; readonly schemaVersion: 1; readonly planHash: string; readonly cursor: number; readonly ticks: number; readonly updates: number; readonly status: Status; readonly qValues: readonly TearOfflineRlQValueV1[]; readonly resume?: Readonly<{ cursor: number; checkpoint: ProductionHeadlessCheckpoint }>; readonly checkpointHash: string; }
export interface TearOnlineRlV3EvaluationResultV1 { readonly format: "tear-online-rl-v3-evaluation"; readonly schemaVersion: 1; readonly planHash: string; readonly baselineTrainingHash: string; readonly challengerCheckpointHash: string; readonly traces: readonly Readonly<{ side: "baseline" | "challenger"; scenarioHash: string; reward: number; terminalHash: string }>[]; readonly metrics: Readonly<{ baselineReward: number; challengerReward: number; passed: boolean }>; readonly promotional: false; readonly resultHash: string; }

function record(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function hash(value: unknown): value is string { return typeof value === "string" && HASH.test(value); }
function text(value: unknown): value is string { return typeof value === "string" && value.trim().length > 0; }
function positive(value: unknown, maximum: number): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value > 0 && value <= maximum; }
function finite(value: unknown, min: number, max: number): value is number { return typeof value === "number" && Number.isFinite(value) && value >= min && value <= max; }
function freeze<T>(value: T): T { return Object.freeze(structuredClone(value)); }
function key(stateHash: string, semanticActionHash: string): string { return `${stateHash}:${semanticActionHash}`; }
function ordered(values: readonly TearOfflineRlQValueV1[]): readonly TearOfflineRlQValueV1[] {
  const identities = new Set<string>();
  const output = values.map((entry) => {
    if (!hash(entry.stateHash) || !hash(entry.semanticActionHash) || !hash(entry.actionHash) || !Number.isFinite(entry.value)) throw new TypeError("invalid online RL V3 Q value");
    const identity = key(entry.stateHash, entry.semanticActionHash);
    if (identities.has(identity)) throw new TypeError("online RL V3 Q values repeat a state/action");
    identities.add(identity);
    return freeze(entry);
  });
  return Object.freeze(output.sort((a, b) => a.stateHash.localeCompare(b.stateHash) || a.semanticActionHash.localeCompare(b.semanticActionHash)));
}
function validConfig(value: unknown): value is TearOnlineRlV3ConfigV1 { return record(value) && finite(value.learningRate, 0.000_001, 1) && finite(value.gamma, 0, 1) && positive(value.maxTicks, 20_000) && positive(value.maxUpdates, 1_000_000) && finite(value.maxAbsoluteQ, 0.000_001, 1_000_000); }

function freezePlan(draft: Omit<TearOnlineRlV3PlanV1, "planHash">): TearOnlineRlV3PlanV1 {
  if (!text(draft.id) || !record(draft.offline) || !hash(draft.offline.v3PlanHash) || !hash(draft.offline.trainingHash) || !hash(draft.offline.rewardPlanHash) || !hash(draft.offline.receiptHash) || !hash(draft.offline.adapterHash) || !hash(draft.offline.actionVocabularyHash) || !validConfig(draft.config) || draft.scenarios.length < 1 || draft.scenarios.length > 32) throw new TypeError("invalid online RL V3 plan");
  const scenarios = draft.scenarios.map(freeze), ids = new Set<string>(); for (const scenario of scenarios) { const id = stableVerificationHash(scenario); if (ids.has(id)) throw new RangeError("online RL V3 scenarios repeat"); ids.add(id); }
  const value = Object.freeze({ format: "tear-online-rl-v3-plan" as const, schemaVersion: 1 as const, id: draft.id, offline: freeze(draft.offline), scenarios: Object.freeze(scenarios), config: freeze(draft.config) }); return Object.freeze({ ...value, planHash: stableVerificationHash(value) });
}
/** Freezes only a completed explicit V3 baseline and natural C30 cases. */
export function createTearOnlineRlV3Plan(offlineInput: TearOfflineRlV3PlanV1, resultInput: TearOfflineRlV3TrainingResultV1, rewardInput: TearOfflineRlPlanV1, input: Readonly<{ id: string; scenarios: readonly TearScenarioV1[]; config: TearOnlineRlV3ConfigV1 }>): TearOnlineRlV3PlanV1 {
  const offline = parseTearOfflineRlV3Plan(offlineInput), result = parseTearOfflineRlV3TrainingResult(resultInput), reward = parseTearOfflineRlPlan(rewardInput);
  if (result.disposition !== "complete" || result.model === undefined || result.plan.planHash !== offline.planHash || result.plan.receiptHash !== offline.receipt.receiptHash || reward.planHash !== offline.receipt.planHash || result.plan.adapterHash !== offline.sourceStateAdapter.adapterHash || result.plan.actionVocabularyHash !== offline.actionVocabularyHash) throw new RangeError("online RL V3 requires a completed exact compatible offline result");
  return freezePlan({ format: "tear-online-rl-v3-plan", schemaVersion: 1, id: input.id, offline: { v3PlanHash: offline.planHash, trainingHash: result.trainingHash, rewardPlanHash: reward.planHash, receiptHash: offline.receipt.receiptHash, adapterHash: offline.sourceStateAdapter.adapterHash, actionVocabularyHash: offline.actionVocabularyHash }, scenarios: input.scenarios, config: input.config });
}
export function parseTearOnlineRlV3Plan(value: unknown): TearOnlineRlV3PlanV1 { if (!record(value) || value.format !== "tear-online-rl-v3-plan" || value.schemaVersion !== 1 || !hash(value.planHash) || !Array.isArray(value.scenarios)) throw new TypeError("invalid online RL V3 plan"); const typed = value as unknown as TearOnlineRlV3PlanV1, { planHash, ...draft } = typed, parsed = freezePlan(draft); if (planHash !== parsed.planHash) throw new TypeError("online RL V3 plan integrity mismatch"); return parsed; }

function freezeCheckpoint(draft: Omit<TearOnlineRlV3CheckpointV1, "checkpointHash">): TearOnlineRlV3CheckpointV1 {
  if (!hash(draft.planHash) || !Number.isSafeInteger(draft.cursor) || draft.cursor < 0 || !Number.isSafeInteger(draft.ticks) || draft.ticks < 0 || !Number.isSafeInteger(draft.updates) || draft.updates < 0 || !["running", "complete", "cancelled", "timed-out", "stopped-divergence"].includes(draft.status) || !Array.isArray(draft.qValues) || (draft.resume !== undefined && (draft.resume.cursor !== draft.cursor || !record(draft.resume.checkpoint)))) throw new TypeError("invalid online RL V3 checkpoint");
  const value = Object.freeze({ format: "tear-online-rl-v3-checkpoint" as const, schemaVersion: 1 as const, planHash: draft.planHash, cursor: draft.cursor, ticks: draft.ticks, updates: draft.updates, status: draft.status, qValues: ordered(draft.qValues), ...(draft.resume === undefined ? {} : { resume: freeze(draft.resume) }) });
  return Object.freeze({ ...value, checkpointHash: stableVerificationHash(value) });
}
export function parseTearOnlineRlV3Checkpoint(value: unknown): TearOnlineRlV3CheckpointV1 { if (!record(value) || value.format !== "tear-online-rl-v3-checkpoint" || value.schemaVersion !== 1 || !hash(value.checkpointHash)) throw new TypeError("invalid online RL V3 checkpoint"); const typed = value as unknown as TearOnlineRlV3CheckpointV1, { checkpointHash, ...draft } = typed, parsed = freezeCheckpoint(draft); if (checkpointHash !== parsed.checkpointHash) throw new TypeError("online RL V3 checkpoint integrity mismatch"); return parsed; }
export function createTearOnlineRlV3Checkpoint(planInput: TearOnlineRlV3PlanV1, resultInput: TearOfflineRlV3TrainingResultV1): TearOnlineRlV3CheckpointV1 { const plan = parseTearOnlineRlV3Plan(planInput), result = parseTearOfflineRlV3TrainingResult(resultInput); if (result.trainingHash !== plan.offline.trainingHash || result.model === undefined) throw new RangeError("online RL V3 baseline is unavailable"); return freezeCheckpoint({ format: "tear-online-rl-v3-checkpoint", schemaVersion: 1, planHash: plan.planHash, cursor: 0, ticks: 0, updates: 0, status: "running", qValues: result.model.entries }); }

function maxQ(values: readonly TearOfflineRlQValueV1[], state: CanonicalGameplayState): number { const hash = stableVerificationHash(state); return values.filter((entry) => entry.stateHash === hash).reduce((max, entry) => Math.max(max, entry.value), 0); }
/** Runs only the existing source-owned C30 composition and retains an exact source checkpoint for resume. */
export function advanceTearOnlineRlV3Checkpoint(planInput: TearOnlineRlV3PlanV1, offlineInput: TearOfflineRlV3PlanV1, resultInput: TearOfflineRlV3TrainingResultV1, rewardInput: TearOfflineRlPlanV1, checkpointInput: TearOnlineRlV3CheckpointV1, control: Readonly<{ maxTicks?: number; cancelled?: () => boolean; now?: () => number; timeoutMilliseconds?: number }> = {}): TearOnlineRlV3CheckpointV1 {
  const plan = parseTearOnlineRlV3Plan(planInput), offline = parseTearOfflineRlV3Plan(offlineInput), result = parseTearOfflineRlV3TrainingResult(resultInput), reward = parseTearOfflineRlPlan(rewardInput), checkpoint = parseTearOnlineRlV3Checkpoint(checkpointInput);
  if (checkpoint.planHash !== plan.planHash || result.trainingHash !== plan.offline.trainingHash || reward.planHash !== plan.offline.rewardPlanHash || offline.planHash !== plan.offline.v3PlanHash || offline.actionVocabularyHash !== plan.offline.actionVocabularyHash || result.model === undefined || checkpoint.status !== "running") throw new RangeError("online RL V3 lineage is unavailable or changed");
  const started = (control.now ?? (() => performance.now()))(), now = control.now ?? (() => performance.now()), base = { format: "tear-online-rl-v3-checkpoint" as const, schemaVersion: 1 as const, planHash: checkpoint.planHash }; let cursor = checkpoint.cursor, ticks = checkpoint.ticks, updates = checkpoint.updates, values = ordered(checkpoint.qValues), resume = checkpoint.resume;
  while (cursor < plan.scenarios.length) {
    const scenario = plan.scenarios[cursor]; if (scenario === undefined) throw new Error("validated V3 scenario disappeared"); const environment = createProductionHeadlessEnvironment({ captureSourceTracks: true }); let current: CanonicalGameplayState; let eventCursor = 0;
    try { current = resume === undefined ? environment.reset(scenario) : environment.restoreCheckpoint(resume.checkpoint);
      while (current.tick < Math.min(scenario.maxTicks, plan.config.maxTicks)) {
        if (control.cancelled?.() === true) return freezeCheckpoint({ ...base, cursor, ticks, updates, qValues: values, status: "cancelled", ...(resume === undefined ? {} : { resume }) });
        if (control.timeoutMilliseconds !== undefined && now() - started >= control.timeoutMilliseconds) return freezeCheckpoint({ ...base, cursor, ticks, updates, qValues: values, status: "timed-out", ...(resume === undefined ? {} : { resume }) });
        if (control.maxTicks !== undefined && ticks - checkpoint.ticks >= control.maxTicks) return freezeCheckpoint({ ...base, cursor, ticks, updates, qValues: values, status: "running", ...(resume === undefined ? {} : { resume }) });
        if (updates >= plan.config.maxUpdates) return freezeCheckpoint({ ...base, cursor, ticks, updates, qValues: values, status: "stopped-divergence", ...(resume === undefined ? {} : { resume }) });
        const model = createTearC34C32RuntimeModel(values), selection = selectTearC34C32RuntimeAction(model, current, offline.actionVocabulary, environment.policyObservation().availableActions); if (selection === undefined) return freezeCheckpoint({ ...base, cursor, ticks, updates, qValues: values, status: "stopped-divergence" });
        const transition = environment.step(selection.actions), events = environment.sourceTracks().nativeEvents.slice(eventCursor);
        eventCursor += events.length;
        const rewardValue = evaluateTearOfflineRlRewardTransition(reward, current, transition.observation, events).total, stateHash = stableVerificationHash(current), entryKey = key(stateHash, selection.semanticActionHash), previous = values.find((entry) => key(entry.stateHash, entry.semanticActionHash) === entryKey) ?? { stateHash, semanticActionHash: selection.semanticActionHash, actionHash: stableVerificationHash(selection.actions), value: 0 }, next = previous.value + plan.config.learningRate * (rewardValue + (transition.terminated || transition.truncated ? 0 : plan.config.gamma * maxQ(values, transition.observation)) - previous.value);
        ticks += 1; updates += 1; if (!Number.isFinite(next) || Math.abs(next) > plan.config.maxAbsoluteQ) return freezeCheckpoint({ ...base, cursor, ticks, updates, qValues: values, status: "stopped-divergence" }); values = ordered([...values.filter((entry) => key(entry.stateHash, entry.semanticActionHash) !== entryKey), { ...previous, value: next }]); current = transition.observation; resume = transition.terminated || transition.truncated ? undefined : { cursor, checkpoint: environment.captureCheckpoint() }; if (transition.terminated || transition.truncated) { cursor += 1; resume = undefined; break; }
      } if (current.tick >= Math.min(scenario.maxTicks, plan.config.maxTicks) && resume !== undefined) { cursor += 1; resume = undefined; }
    } finally { environment.dispose(); }
  }
  return freezeCheckpoint({ ...base, cursor, ticks, updates, qValues: values, status: "complete" });
}

function execute(modelEntries: readonly TearOfflineRlQValueV1[], plan: TearOnlineRlV3PlanV1, offline: TearOfflineRlV3PlanV1, reward: TearOfflineRlPlanV1, side: "baseline" | "challenger") { const traces: TearOnlineRlV3EvaluationResultV1["traces"][number][] = []; for (const scenario of plan.scenarios) { const environment = createProductionHeadlessEnvironment({ captureSourceTracks: true }); try { let current = environment.reset(scenario), rewardTotal = 0, eventCursor = 0; while (current.tick < Math.min(scenario.maxTicks, plan.config.maxTicks)) { const selected = selectTearC34C32RuntimeAction(createTearC34C32RuntimeModel(modelEntries), current, offline.actionVocabulary, environment.policyObservation().availableActions); if (selected === undefined) break; const transition = environment.step(selected.actions), events = environment.sourceTracks().nativeEvents.slice(eventCursor); eventCursor += events.length; rewardTotal += evaluateTearOfflineRlRewardTransition(reward, current, transition.observation, events).total; current = transition.observation; if (transition.terminated || transition.truncated) break; } traces.push(Object.freeze({ side, scenarioHash: stableVerificationHash(scenario), reward: rewardTotal, terminalHash: stableVerificationHash(current) })); } finally { environment.dispose(); } } return traces; }
/** Fresh paired C30 evaluation retains a pass/fail fact only; it cannot promote. */
export function evaluateTearOnlineRlV3InSource(planInput: TearOnlineRlV3PlanV1, offlineInput: TearOfflineRlV3PlanV1, resultInput: TearOfflineRlV3TrainingResultV1, rewardInput: TearOfflineRlPlanV1, challengerInput: TearOnlineRlV3CheckpointV1, minimumRewardGain = 0): TearOnlineRlV3EvaluationResultV1 { const plan = parseTearOnlineRlV3Plan(planInput), offline = parseTearOfflineRlV3Plan(offlineInput), result = parseTearOfflineRlV3TrainingResult(resultInput), reward = parseTearOfflineRlPlan(rewardInput), challenger = parseTearOnlineRlV3Checkpoint(challengerInput); if (result.model === undefined || challenger.status !== "complete" || challenger.planHash !== plan.planHash || !Number.isFinite(minimumRewardGain)) throw new RangeError("online RL V3 evaluation lineage is incomplete"); const traces = Object.freeze([...execute(result.model.entries, plan, offline, reward, "baseline"), ...execute(challenger.qValues, plan, offline, reward, "challenger")]); const baselineReward = traces.filter((entry) => entry.side === "baseline").reduce((sum, entry) => sum + entry.reward, 0), challengerReward = traces.filter((entry) => entry.side === "challenger").reduce((sum, entry) => sum + entry.reward, 0); const draft = { format: "tear-online-rl-v3-evaluation" as const, schemaVersion: 1 as const, planHash: plan.planHash, baselineTrainingHash: result.trainingHash, challengerCheckpointHash: challenger.checkpointHash, traces, metrics: Object.freeze({ baselineReward, challengerReward, passed: challengerReward - baselineReward >= minimumRewardGain }), promotional: false as const }; return Object.freeze({ ...draft, resultHash: stableVerificationHash(draft) }); }
export function parseTearOnlineRlV3EvaluationResult(value: unknown): TearOnlineRlV3EvaluationResultV1 {
  if (!record(value) || value.format !== "tear-online-rl-v3-evaluation" || value.schemaVersion !== 1 || !hash(value.resultHash) || !hash(value.planHash) || !hash(value.baselineTrainingHash) || !hash(value.challengerCheckpointHash) || !Array.isArray(value.traces) || !record(value.metrics) || typeof value.metrics.baselineReward !== "number" || !Number.isFinite(value.metrics.baselineReward) || typeof value.metrics.challengerReward !== "number" || !Number.isFinite(value.metrics.challengerReward) || typeof value.metrics.passed !== "boolean" || value.promotional !== false) throw new TypeError("invalid online RL V3 evaluation result");
  const typed = value as unknown as TearOnlineRlV3EvaluationResultV1, { resultHash, ...draft } = typed;
  const parsed = Object.freeze({ ...draft, traces: Object.freeze(draft.traces.map(freeze)), metrics: freeze(draft.metrics), resultHash: stableVerificationHash(draft) });
  if (resultHash !== parsed.resultHash) throw new TypeError("online RL V3 evaluation result integrity mismatch");
  return parsed;
}
export class TearOnlineRlV3CheckpointVault { readonly #backend: GhostVaultBackend; constructor(backend: GhostVaultBackend) { this.#backend = backend; } async persist(input: TearOnlineRlV3CheckpointV1): Promise<TearOnlineRlV3CheckpointV1> { const value = parseTearOnlineRlV3Checkpoint(input), storageKey = `${KEY}${value.checkpointHash}`, prior = await this.#backend.get("analysis", storageKey); if (prior !== undefined) return parseTearOnlineRlV3Checkpoint(JSON.parse(prior)); await this.#backend.commit(Object.freeze([{ store: "analysis", key: storageKey, value: JSON.stringify(value) }])); return value; } async get(checkpointHash: string): Promise<TearOnlineRlV3CheckpointV1 | undefined> { if (!hash(checkpointHash)) throw new TypeError("online RL V3 checkpoint hash is invalid"); const storageKey = `${KEY}${checkpointHash}`, raw = await this.#backend.get("analysis", storageKey); if (raw === undefined) return undefined; try { return parseTearOnlineRlV3Checkpoint(JSON.parse(raw)); } catch (error) { await this.#backend.put("quarantine", storageKey, JSON.stringify({ storageKey, raw, reason: error instanceof Error ? error.message : String(error) })); return undefined; } } }
export class TearOnlineRlV3EvaluationVault { readonly #backend: GhostVaultBackend; constructor(backend: GhostVaultBackend) { this.#backend = backend; } async persist(input: TearOnlineRlV3EvaluationResultV1): Promise<TearOnlineRlV3EvaluationResultV1> { const value = parseTearOnlineRlV3EvaluationResult(input), storageKey = `${RESULT_KEY}${value.resultHash}`, prior = await this.#backend.get("analysis", storageKey); if (prior !== undefined) return parseTearOnlineRlV3EvaluationResult(JSON.parse(prior)); await this.#backend.commit(Object.freeze([{ store: "analysis", key: storageKey, value: JSON.stringify(value) }])); return value; } async get(resultHash: string): Promise<TearOnlineRlV3EvaluationResultV1 | undefined> { if (!hash(resultHash)) throw new TypeError("online RL V3 evaluation result hash is invalid"); const storageKey = `${RESULT_KEY}${resultHash}`, raw = await this.#backend.get("analysis", storageKey); if (raw === undefined) return undefined; try { return parseTearOnlineRlV3EvaluationResult(JSON.parse(raw)); } catch (error) { await this.#backend.put("quarantine", storageKey, JSON.stringify({ storageKey, raw, reason: error instanceof Error ? error.message : String(error) })); return undefined; } } }
