import { describe, expect, it } from "vitest";
import { createMemoryGhostVaultBackend } from "../../src/ghost";
import { stableVerificationHash } from "../../src/replay/hash";
import { createTearFoundryJobV2, createTearFoundryV3PostPromotionTerminalReceipt, createTearPolicyArtifact, TearFoundryJobVault, TearFoundryV3PostPromotionMonitor, TearFoundryV3PostPromotionRollbackExecutor, TearPolicyArtifactRegistry, TearPolicyDecisionJournal, transitionTearFoundryJob, type TearAcademyCandidateCustodyStore } from "../../src/agents";

const h = (letter: string) => letter.repeat(16), compatibility = Object.freeze({ runtime: "tear-policy-runtime.v1", observationClass: "structured-state" as const, actionSchema: "tear-game-action-command-envelope.v1", modelFormats: Object.freeze(["table-policy-v1"]) });
function artifact(id: string) { return createTearPolicyArtifact({ id, createdAt: "2026-08-08T00:00:00.000Z", model: { format: "table-policy-v1", payload: JSON.stringify({ states: {} }) }, encoder: { id: "tear-structured-state", schemaVersion: 1, observationClass: "structured-state", normalizationHash: h("1") }, actionSchema: "tear-game-action-command-envelope.v1", recurrentState: { kind: "none", schemaVersion: 1 }, trainingManifest: { id: "m", version: 1, rootHash: h("2") }, rewardVersion: "r", build: { version: "test", revision: "c36", target: "unit", rulesetVersion: "r", contentHash: "c", configHash: "g" }, metrics: { legalActionRate: 1 }, levelTarget: "class-a", lineage: { trainingRunId: id }, signature: { kind: "local-unsigned", keyId: "test" }, compatibility }); }
async function fixture() {
  const backend = createMemoryGhostVaultBackend(), registry = new TearPolicyArtifactRegistry(backend, compatibility), baseline = artifact("baseline"), candidate = artifact("candidate"); await registry.register(baseline); await registry.register(candidate); const baselineActivation = await registry.activate(baseline.id, "2026-08-08T00:01:00.000Z"), candidateActivation = await registry.activate(candidate.id, "2026-08-08T00:02:00.000Z");
  const corpus = h("8"), custody = { backend: () => backend, held: () => Promise.resolve([{ candidateHash: h("9"), recordHash: corpus }]) } as unknown as TearAcademyCandidateCustodyStore; let job = createTearFoundryJobV2({ id: "rollback-job", createdAt: "2026-08-08T00:00:00.000Z", reason: "authorized", inputs: { champion: { id: baseline.id, artifactHash: baseline.artifactHash }, corpusRecordHashes: [corpus], evaluationPlanHash: h("3"), rewardDefinitionHash: h("4"), invariantSetHash: h("5"), budgetHash: h("6"), stopConditionsHash: h("7"), evaluationProtocol: { version: 1, id: "frozen", thresholds: { minimumRewardGain: 0, requireCompletionRateNotLower: true, maxTicksPerCase: 4, maxAbsoluteRewardPerCase: 100 } } } });
  for (const phase of ["collecting", "curating", "training", "evaluating", "deciding", "monitoring"] as const) job = transitionTearFoundryJob(job, phase, "2026-08-08T00:03:00.000Z", phase); await new TearFoundryJobVault(backend).persist(job); const protocol = job.inputs.evaluationProtocol; if (protocol === undefined) throw new Error("missing protocol");
  const approvalDraft = { format: "tear-foundry-v3-promotion-approval" as const, schemaVersion: 1 as const, job: { id: job.id, jobHash: job.jobHash, protocolHash: protocol.protocolHash, stopConditionsHash: job.inputs.stopConditionsHash }, bridge: { bridgeHash: h("8"), decisionReceiptHash: h("9"), monitoringReceiptHash: h("a"), evaluationResultHash: h("b") }, candidate: { id: candidate.id, artifactHash: candidate.artifactHash, adapterHash: h("c"), actionVocabularyHash: h("d"), offlinePlanHash: h("e"), offlineTrainingHash: h("f"), onlinePlanHash: h("0"), onlineCheckpointHash: h("1"), evaluationHash: h("2") }, rollbackBaseline: { revision: baselineActivation.revision, artifactId: baseline.id, artifactHash: baseline.artifactHash, activationHash: baselineActivation.activationHash }, conditions: { currentMonitoringHead: true, monitoringReadyDecision: true, evidenceRetained: true, heldCustody: true, completedPassedV3: true, inactiveCandidateOnly: true, approverFree: true }, approvedAt: "2026-08-08T00:02:00.000Z" }, approval = Object.freeze({ ...approvalDraft, approvalHash: stableVerificationHash(approvalDraft) });
  const promotionDraft = { format: "tear-foundry-v3-promotion-receipt" as const, schemaVersion: 1 as const, approvalHash: approval.approvalHash, artifactId: candidate.id, artifactHash: candidate.artifactHash, activationHash: candidateActivation.activationHash, revision: candidateActivation.revision, promotedAt: "2026-08-08T00:02:00.000Z" }, promotion = Object.freeze({ ...promotionDraft, receiptHash: stableVerificationHash(promotionDraft) }); await backend.put("analysis", `foundry-job-v3-promotion-approval:v1:${approval.approvalHash}`, JSON.stringify(approval)); await backend.put("analysis", `foundry-job-v3-promotion-receipt:v1:${approval.approvalHash}`, JSON.stringify(promotion));
  const journal = new TearPolicyDecisionJournal(backend); journal.begin("watch-policy:v1:real-c30-breach", 4); const trace = { tick: 1, profile: "competent" as const, objective: "survive" as const, maneuver: "track" as const, confidence: .5, recovery: false, observationClass: "privileged-diagnostic" as const, critic: ["safe"] as const }; journal.append({ tick: 1, receipt: { artifactId: candidate.id, artifactHash: candidate.artifactHash, activationHash: candidateActivation.activationHash, observationHash: h("3"), source: "artifact" }, actions: [{ type: "move", x: 1_000, y: 0 }], trace }); await journal.flush(); const persisted = await journal.read("watch-policy:v1:real-c30-breach"); if (persisted === undefined) throw new Error("missing journal");
  const terminal = createTearFoundryV3PostPromotionTerminalReceipt({ journalId: persisted.id, journalHash: persisted.journalHash, terminal: { status: "failed", tick: 2, reasonHash: h("4") } }), monitor = await new TearFoundryV3PostPromotionMonitor(backend).retain(terminal, "2026-08-08T00:04:00.000Z"); return { backend, baseline, candidate, candidateActivation, monitor, jobs: new TearFoundryJobVault(backend), custody };
}
describe("C36 approval-bound post-promotion rollback", () => {
  it("rolls a planted real Watch/C30 breach back to its frozen baseline atomically and idempotently", async () => { const f = await fixture(), executor = new TearFoundryV3PostPromotionRollbackExecutor(f.jobs, f.custody), result = await executor.rollback(f.monitor.recordHash, "2026-08-08T00:05:00.000Z"); expect(result.rollback.artifactId).toBe(f.baseline.id); expect((await new TearPolicyArtifactRegistry(f.backend, compatibility).active())?.artifactId).toBe(f.baseline.id); expect((await executor.rollback(f.monitor.recordHash, "2026-08-08T00:06:00.000Z")).receiptHash).toBe(result.receiptHash); });
  it("refuses observation, stale/tampered active pointer, corrupt monitor, and never writes a partial rollback", async () => { const f = await fixture(), executor = new TearFoundryV3PostPromotionRollbackExecutor(f.jobs, f.custody); await f.backend.put("analysis", `foundry-job-v3-post-promotion-monitor:v1:${f.monitor.recordHash}`, JSON.stringify({ ...f.monitor, classification: "observation" })); await expect(executor.rollback(f.monitor.recordHash, "2026-08-08T00:05:00.000Z")).rejects.toThrow(/monitor|integrity|breach/u); expect((await new TearPolicyArtifactRegistry(f.backend, compatibility).active())?.artifactId).toBe(f.candidate.id); });
});
