import { describe, expect, it } from "vitest";

import { createMemoryGhostVaultBackend } from "../../src/ghost";
import { stableVerificationHash } from "../../src/replay/hash";
import {
  advanceTearOfflineRlV3Checkpoint, advanceTearOnlineRlV3Checkpoint, completeTearOfflineRlV3Checkpoint,
  createTearC34V3C32PolicyCandidate, createTearFoundryJob, createTearFoundryJobV2, createTearOfflineRlPlan,
  createTearPolicyArtifact,
  createTearOfflineRlV3Checkpoint, createTearOfflineRlV3Plan, createTearOnlineRlV3Checkpoint,
  createTearOnlineRlV3Plan, evaluateTearOnlineRlV3InSource, extractTearOfflineRlTrajectories,
  TearC34V3C32CandidateRegistry, TearFoundryJobVault, TearFoundryV3MonitoringBridgeExecutor, TearFoundryV3PromotionApprovalExecutor, TearFoundryV3PromotionExecutor, TearPolicyArtifactRegistry,
  transitionTearFoundryJob, type TearAcademyCandidateCustodyStore, type TearAcademyTrainingDatasetV1,
} from "../../src/agents";

const h = Object.freeze({ artifact: "1111111111111111", corpus: "2222222222222222", evaluation: "3333333333333333", invariant: "5555555555555555", budget: "6666666666666666", stop: "7777777777777777" });
const scenario = Object.freeze({ format: "tear-contract" as const, kind: "scenario" as const, schemaVersion: 1 as const, id: "foundry-v3-bridge", version: 1, description: "Foundry V3 monitoring bridge fixture", stateClass: "recorded-canonical" as const, executionClass: "training" as const, seed: "foundry-v3-bridge", start: Object.freeze({ mode: "endless" as const, difficulty: "normal" as const, weapon: "sword" as const }), maxTicks: 4, assertions: Object.freeze(["runtime.finite-state"] as const), tags: Object.freeze(["c34", "c36"] as const) });

function v3Fixture() {
  const states = [0, 1].map((tick) => Object.freeze({ tick, input: {} as never, run: Object.freeze({ mode: "endless", wave: 1, score: tick, time: tick, seed: 7 }), player: Object.freeze({ x: 0, y: 0, vx: 0, vy: 0, hp: 100 }), blade: Object.freeze({ state: "held", x: 0, y: 0, vx: 0, vy: 0 }), enemies: Object.freeze([]) }));
  const data = Object.freeze({ format: "tear-academy-training-dataset", schemaVersion: 1, manifest: Object.freeze({ id: "foundry-v3-bridge", version: 1, manifestHash: "a".repeat(16), rootHash: "b".repeat(16) }), sequences: Object.freeze([Object.freeze({ candidateHash: "c".repeat(16), split: "training" as const, lessonId: "movement", segmentKind: "demonstration", tags: Object.freeze([]), sourceScenario: scenario, tracks: Object.freeze({ observations: Object.freeze(states), actions: Object.freeze([Object.freeze({ kind: "command" as const, id: 1, tick: 1, command: Object.freeze({ type: "move" as const, x: 1_000, y: 0 }) })]), nativeEvents: Object.freeze([]), rewardComponents: Object.freeze(states.map((entry) => Object.freeze({ tick: entry.tick, value: null }))), intents: Object.freeze([]), terminal: Object.freeze({ tick: 1, semanticHash: stableVerificationHash(states[1]), terminated: true, truncated: false }) }) as never, sequenceHash: "d".repeat(16) })]), observationCount: 2, actionCount: 1, datasetHash: "e".repeat(16) }) satisfies TearAcademyTrainingDatasetV1;
  const reward = createTearOfflineRlPlan(data, { id: "foundry-v3-bridge", version: 1, seed: 7, reward: { components: [{ id: "score", source: "score.delta", weight: 1, maximumSourceValue: 10, perTransitionCap: 10 }], totalMinimum: -10, totalMaximum: 10 }, limits: { maxTransitions: 4, maxEventsPerTransition: 4, maxRewardViolations: 0 } });
  const receipt = extractTearOfflineRlTrajectories(data, reward), offline = createTearOfflineRlV3Plan(receipt, { id: "offline", version: 1, actionVocabulary: [{ type: "move", x: 1_000, y: 0 }], config: { epochs: 1, learningRate: 0.5, gamma: 0.9, maxStateActionEntries: 10, maxAbsoluteQ: 100, maxMeanAbsoluteTdError: 100, maxConsecutiveDivergentEpochs: 2 } });
  const training = completeTearOfflineRlV3Checkpoint(offline, receipt, advanceTearOfflineRlV3Checkpoint(offline, receipt, createTearOfflineRlV3Checkpoint(offline, receipt), 1)), online = createTearOnlineRlV3Plan(offline, training, reward, { id: "online", scenarios: [scenario], config: { learningRate: 0.5, gamma: 0.9, maxTicks: 4, maxUpdates: 10, maxAbsoluteQ: 100 } });
  const checkpoint = advanceTearOnlineRlV3Checkpoint(online, offline, training, reward, createTearOnlineRlV3Checkpoint(online, training)), evaluation = evaluateTearOnlineRlV3InSource(online, offline, training, reward, checkpoint);
  const candidate = createTearC34V3C32PolicyCandidate(offline, training, online, checkpoint, evaluation, { id: "v3-bridge-candidate", createdAt: "2026-08-08T00:00:00.000Z", encoder: { id: "tear-c34-c32-canonical-source-state.v1", schemaVersion: 1, observationClass: "structured-state", normalizationHash: "1".repeat(16) }, actionSchema: "tear-game-action-command-envelope.v1", recurrentState: { kind: "none", schemaVersion: 1 }, trainingManifest: { id: "c31-manifest", version: 1, rootHash: "2".repeat(16) }, rewardVersion: "c34-v3", build: { version: "test", revision: "c34", target: "unit", rulesetVersion: "r", contentHash: "c", configHash: "g" }, metrics: { pairedPassed: 1 }, levelTarget: "class-a", lineage: { trainingRunId: training.trainingHash }, signature: { kind: "local-unsigned", keyId: "development" } });
  return { data, reward, offline, training, online, checkpoint, evaluation, candidate };
}

async function setup() {
  const backend = createMemoryGhostVaultBackend(), vault = new TearFoundryJobVault(backend);
  const created = createTearFoundryJobV2({ id: "foundry-v3-bridge", createdAt: "2026-08-08T00:00:00.000Z", reason: "authorized", inputs: { champion: { id: "champion", artifactHash: h.artifact }, corpusRecordHashes: [h.corpus], evaluationPlanHash: h.evaluation, rewardDefinitionHash: "8".repeat(16), invariantSetHash: h.invariant, budgetHash: h.budget, stopConditionsHash: h.stop, evaluationProtocol: { version: 1, id: "foundry-v3-bridge", thresholds: { minimumRewardGain: 0, requireCompletionRateNotLower: true, maxTicksPerCase: 4, maxAbsoluteRewardPerCase: 100 } } } });
  let job = transitionTearFoundryJob(created, "collecting", "2026-08-08T00:00:01.000Z", "collected"); job = transitionTearFoundryJob(job, "curating", "2026-08-08T00:00:02.000Z", "curated"); job = transitionTearFoundryJob(job, "training", "2026-08-08T00:00:03.000Z", "trained"); job = transitionTearFoundryJob(job, "evaluating", "2026-08-08T00:00:04.000Z", "ready"); job = transitionTearFoundryJob(job, "deciding", "2026-08-08T00:00:05.000Z", "evaluated"); const deciding = job; job = transitionTearFoundryJob(job, "monitoring", "2026-08-08T00:00:06.000Z", "passed"); await vault.persist(job);
  const decisionDraft = { format: "tear-foundry-decision-receipt" as const, schemaVersion: 1 as const, job: Object.freeze({ sourceJobHash: deciding.jobHash, resultJobHash: job.jobHash }), evaluationReceiptHash: "9".repeat(16), evaluationResultHash: h.evaluation, disposition: "monitoring-ready" as const, decidedAt: "2026-08-08T00:00:06.000Z" }, decision = Object.freeze({ ...decisionDraft, receiptHash: stableVerificationHash(decisionDraft) });
  const monitoringDraft = { format: "tear-foundry-monitoring-entry" as const, schemaVersion: 1 as const, jobHash: job.jobHash, decisionReceiptHash: decision.receiptHash, evaluationResultHash: h.evaluation, stopConditionsHash: h.stop, observedAt: "2026-08-08T00:00:07.000Z", health: "evidence-retained" as const }, monitoring = Object.freeze({ ...monitoringDraft, receiptHash: stableVerificationHash(monitoringDraft) });
  await backend.commit(Object.freeze([{ store: "analysis", key: `foundry-job-decision:v1:${decision.receiptHash}`, value: JSON.stringify(decision) }, { store: "analysis", key: `foundry-job-monitoring-entry:v1:${monitoring.receiptHash}`, value: JSON.stringify(monitoring) }]));
  const custody = { backend: () => backend, held: () => Promise.resolve([{ recordHash: h.corpus }]) } as unknown as TearAcademyCandidateCustodyStore;
  return { backend, vault, custody, job, decision, monitoring };
}

describe("C36 V3 monitoring bridge", () => {
  it("retains one exact inactive V3 candidate bridge and exact retry is idempotent", async () => {
    const context = await setup(), v3 = v3Fixture(), registry = new TearC34V3C32CandidateRegistry(context.backend); await registry.register(v3.candidate.artifact);
    const executor = new TearFoundryV3MonitoringBridgeExecutor(context.vault, context.custody), input = { decisionReceiptHash: context.decision.receiptHash, monitoringReceiptHash: context.monitoring.receiptHash, offline: v3.offline, training: v3.training, online: v3.online, checkpoint: v3.checkpoint, evaluation: v3.evaluation, candidateArtifactId: v3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" };
    const first = await executor.bridge(context.job, input), again = await executor.bridge(context.job, input);
    expect(again).toEqual(first); expect(await executor.get(first.bridgeHash)).toEqual(first);
    expect((await context.backend.keys("analysis")).filter((key) => key.startsWith("foundry-job-v3-monitoring-bridge:v1:")).length).toBe(1);
    expect(await context.backend.get("analysis", "policy-active:v1")).toBeUndefined();
  });

  it("refuses non-V3, non-inactive, mismatched, stale, and revoked provenance", async () => {
    const context = await setup(), v3 = v3Fixture(), registry = new TearC34V3C32CandidateRegistry(context.backend); await registry.register(v3.candidate.artifact);
    const executor = new TearFoundryV3MonitoringBridgeExecutor(context.vault, context.custody), input = { decisionReceiptHash: context.decision.receiptHash, monitoringReceiptHash: context.monitoring.receiptHash, offline: v3.offline, training: v3.training, online: v3.online, checkpoint: v3.checkpoint, evaluation: v3.evaluation, candidateArtifactId: v3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" };
    await expect(executor.bridge(context.job, { ...input, monitoringReceiptHash: "0".repeat(16) })).rejects.toThrow(/lineage/u);
    const payload = JSON.parse(v3.candidate.artifact.model.payload) as Record<string, unknown>, lineage = payload.lineage as Record<string, unknown>, mismatched = createTearPolicyArtifact({ ...v3.candidate.artifact, id: "mismatched-v3-bridge-candidate", model: { format: v3.candidate.artifact.model.format, payload: JSON.stringify({ ...payload, lineage: { ...lineage, offlinePlanHash: "0".repeat(16) } }) } });
    await registry.register(mismatched); await expect(executor.bridge(context.job, { ...input, candidateArtifactId: mismatched.id })).rejects.toThrow(/candidate lineage/u);
    const next = transitionTearFoundryJob(context.job, "completed", "2026-08-08T00:02:00.000Z", "closed"); await context.vault.persistSuccessor(context.job, next);
    await expect(executor.bridge(context.job, input)).rejects.toThrow(/current/u);
    const revoked = await setup(), revokedV3 = v3Fixture(), revokedRegistry = new TearC34V3C32CandidateRegistry(revoked.backend); await revokedRegistry.register(revokedV3.candidate.artifact);
    const mutable = revoked.custody as unknown as { held: () => Promise<readonly unknown[]> }; mutable.held = () => Promise.resolve([]);
    await expect(new TearFoundryV3MonitoringBridgeExecutor(revoked.vault, revoked.custody).bridge(revoked.job, { decisionReceiptHash: revoked.decision.receiptHash, monitoringReceiptHash: revoked.monitoring.receiptHash, offline: revokedV3.offline, training: revokedV3.training, online: revokedV3.online, checkpoint: revokedV3.checkpoint, evaluation: revokedV3.evaluation, candidateArtifactId: revokedV3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" })).rejects.toThrow(/custody|lineage/u);
    const legacy = await setup(), legacyV3 = v3Fixture(), legacyRegistry = new TearC34V3C32CandidateRegistry(legacy.backend); await legacyRegistry.register(legacyV3.candidate.artifact);
    await expect(new TearFoundryV3MonitoringBridgeExecutor(legacy.vault, legacy.custody).bridge(legacy.job, { decisionReceiptHash: legacy.decision.receiptHash, monitoringReceiptHash: legacy.monitoring.receiptHash, offline: createTearOfflineRlPlan(legacyV3.data, { id: "legacy", version: 1, seed: 1, reward: { components: [{ id: "score", source: "score.delta", weight: 1, maximumSourceValue: 10, perTransitionCap: 10 }], totalMinimum: -10, totalMaximum: 10 }, limits: { maxTransitions: 4, maxEventsPerTransition: 4, maxRewardViolations: 0 } }) as never, training: legacyV3.training, online: legacyV3.online, checkpoint: legacyV3.checkpoint, evaluation: legacyV3.evaluation, candidateArtifactId: legacyV3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" })).rejects.toThrow(/V3|invalid|lineage/u);
    const noninactive = await setup(), noninactiveV3 = v3Fixture(), noninactiveRegistry = new TearC34V3C32CandidateRegistry(noninactive.backend); await noninactiveRegistry.register(noninactiveV3.candidate.artifact);
    await noninactive.backend.put("analysis", `policy-artifact:v1:${noninactiveV3.candidate.artifact.id}`, JSON.stringify({ ...noninactiveV3.candidate.artifact, extensions: { ...noninactiveV3.candidate.artifact.extensions, candidateOnly: false } }));
    await expect(new TearFoundryV3MonitoringBridgeExecutor(noninactive.vault, noninactive.custody).bridge(noninactive.job, { decisionReceiptHash: noninactive.decision.receiptHash, monitoringReceiptHash: noninactive.monitoring.receiptHash, offline: noninactiveV3.offline, training: noninactiveV3.training, online: noninactiveV3.online, checkpoint: noninactiveV3.checkpoint, evaluation: noninactiveV3.evaluation, candidateArtifactId: noninactiveV3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" })).rejects.toThrow(/candidate/u);
    const v1 = await setup(), v1V3 = v3Fixture(), v1Job = createTearFoundryJob({ id: "legacy-foundry-v1", createdAt: "2026-08-08T00:00:00.000Z", reason: "legacy", inputs: { champion: { id: "champion", artifactHash: h.artifact }, corpusRecordHashes: [h.corpus], evaluationPlanHash: h.evaluation, rewardDefinitionHash: "8".repeat(16), invariantSetHash: h.invariant, budgetHash: h.budget, stopConditionsHash: h.stop } });
    let v1Monitoring = transitionTearFoundryJob(v1Job, "collecting", "2026-08-08T00:00:01.000Z", "collected"); v1Monitoring = transitionTearFoundryJob(v1Monitoring, "curating", "2026-08-08T00:00:02.000Z", "curated"); v1Monitoring = transitionTearFoundryJob(v1Monitoring, "training", "2026-08-08T00:00:03.000Z", "trained"); v1Monitoring = transitionTearFoundryJob(v1Monitoring, "evaluating", "2026-08-08T00:00:04.000Z", "ready"); v1Monitoring = transitionTearFoundryJob(v1Monitoring, "deciding", "2026-08-08T00:00:05.000Z", "evaluated"); v1Monitoring = transitionTearFoundryJob(v1Monitoring, "monitoring", "2026-08-08T00:00:06.000Z", "passed"); await v1.vault.persist(v1Monitoring);
    const v1Registry = new TearC34V3C32CandidateRegistry(v1.backend); await v1Registry.register(v1V3.candidate.artifact);
    await expect(new TearFoundryV3MonitoringBridgeExecutor(v1.vault, v1.custody).bridge(v1Monitoring, { decisionReceiptHash: v1.decision.receiptHash, monitoringReceiptHash: v1.monitoring.receiptHash, offline: v1V3.offline, training: v1V3.training, online: v1V3.online, checkpoint: v1V3.checkpoint, evaluation: v1V3.evaluation, candidateArtifactId: v1V3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" })).rejects.toThrow(/V1/u);
  });

  it("quarantines corrupt retained bridge bytes", async () => {
    const context = await setup(), v3 = v3Fixture(), registry = new TearC34V3C32CandidateRegistry(context.backend); await registry.register(v3.candidate.artifact);
    const executor = new TearFoundryV3MonitoringBridgeExecutor(context.vault, context.custody), result = await executor.bridge(context.job, { decisionReceiptHash: context.decision.receiptHash, monitoringReceiptHash: context.monitoring.receiptHash, offline: v3.offline, training: v3.training, online: v3.online, checkpoint: v3.checkpoint, evaluation: v3.evaluation, candidateArtifactId: v3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" });
    const key = `foundry-job-v3-monitoring-bridge:v1:${result.bridgeHash}`; await context.backend.put("analysis", key, "corrupt");
    await expect(executor.get(result.bridgeHash)).resolves.toBeUndefined(); expect(await context.backend.get("quarantine", key)).toBe("corrupt");
  });

  it("freezes exact approval evidence and rejects changed custody, baseline, or stored bytes", async () => {
    const context = await setup(), v3 = v3Fixture(), candidates = new TearC34V3C32CandidateRegistry(context.backend); await candidates.register(v3.candidate.artifact);
    const bridge = await new TearFoundryV3MonitoringBridgeExecutor(context.vault, context.custody).bridge(context.job, { decisionReceiptHash: context.decision.receiptHash, monitoringReceiptHash: context.monitoring.receiptHash, offline: v3.offline, training: v3.training, online: v3.online, checkpoint: v3.checkpoint, evaluation: v3.evaluation, candidateArtifactId: v3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" });
    const compatibility = Object.freeze({ runtime: "tear-policy-runtime.v1" as const, observationClass: "structured-state" as const, actionSchema: "tear-game-action-command-envelope.v1" as const, modelFormats: Object.freeze(["table-policy-v1"]) }), baseline = createTearPolicyArtifact({ id: "rollback-baseline", createdAt: "2026-08-08T00:00:00.000Z", model: { format: "table-policy-v1", payload: "{}" }, encoder: { id: "baseline", schemaVersion: 1, observationClass: "structured-state", normalizationHash: "a".repeat(16) }, actionSchema: "tear-game-action-command-envelope.v1", recurrentState: { kind: "none", schemaVersion: 1 }, trainingManifest: { id: "baseline", version: 1, rootHash: "b".repeat(16) }, rewardVersion: "baseline", build: { version: "test", revision: "baseline", target: "unit", rulesetVersion: "r", contentHash: "c", configHash: "d" }, metrics: {}, levelTarget: "class-a", lineage: { trainingRunId: "baseline" }, signature: { kind: "local-unsigned", keyId: "development" }, compatibility });
    const policies = new TearPolicyArtifactRegistry(context.backend, compatibility); await policies.register(baseline); await policies.activate(baseline.id, "2026-08-08T00:01:01.000Z");
    const approval = new TearFoundryV3PromotionApprovalExecutor(context.vault, context.custody), first = await approval.approve(context.job, bridge.bridgeHash, "2026-08-08T00:02:00.000Z"), again = await approval.approve(context.job, bridge.bridgeHash, "2026-08-08T00:02:00.000Z");
    expect(again).toEqual(first); expect(first.rollbackBaseline).toMatchObject({ artifactId: baseline.id, artifactHash: baseline.artifactHash }); expect(await context.backend.get("analysis", "policy-active:v1")).toBeDefined();
    const approvalKey = `foundry-job-v3-promotion-approval:v1:${first.approvalHash}`; await context.backend.put("analysis", approvalKey, "corrupt"); expect(await approval.get(first.approvalHash)).toBeUndefined(); expect(await context.backend.get("quarantine", approvalKey)).toBe("corrupt");
    const revoked = await setup(), revokedV3 = v3Fixture(), revokedCandidates = new TearC34V3C32CandidateRegistry(revoked.backend); await revokedCandidates.register(revokedV3.candidate.artifact); const revokedBridge = await new TearFoundryV3MonitoringBridgeExecutor(revoked.vault, revoked.custody).bridge(revoked.job, { decisionReceiptHash: revoked.decision.receiptHash, monitoringReceiptHash: revoked.monitoring.receiptHash, offline: revokedV3.offline, training: revokedV3.training, online: revokedV3.online, checkpoint: revokedV3.checkpoint, evaluation: revokedV3.evaluation, candidateArtifactId: revokedV3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" });
    (revoked.custody as unknown as { held: () => Promise<readonly unknown[]> }).held = () => Promise.resolve([]); await expect(new TearFoundryV3PromotionApprovalExecutor(revoked.vault, revoked.custody).approve(revoked.job, revokedBridge.bridgeHash, "2026-08-08T00:02:00.000Z")).rejects.toThrow(/custody|lineage/u);
  });

  it("atomically consumes one exact approval into a V3 active pointer and is retry-idempotent", async () => {
    const context = await setup(), v3 = v3Fixture(), candidates = new TearC34V3C32CandidateRegistry(context.backend);
    await candidates.register(v3.candidate.artifact);
    const bridge = await new TearFoundryV3MonitoringBridgeExecutor(context.vault, context.custody).bridge(context.job, { decisionReceiptHash: context.decision.receiptHash, monitoringReceiptHash: context.monitoring.receiptHash, offline: v3.offline, training: v3.training, online: v3.online, checkpoint: v3.checkpoint, evaluation: v3.evaluation, candidateArtifactId: v3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" });
    const approval = await new TearFoundryV3PromotionApprovalExecutor(context.vault, context.custody).approve(context.job, bridge.bridgeHash, "2026-08-08T00:02:00.000Z"), executor = new TearFoundryV3PromotionExecutor(context.vault, context.custody);
    const first = await executor.promote(approval.approvalHash, "2026-08-08T00:03:00.000Z"), retry = await executor.promote(approval.approvalHash, "2026-08-08T00:03:00.000Z");
    expect(retry).toEqual(first); expect(first.artifactHash).toBe(v3.candidate.artifact.artifactHash);
    expect(JSON.parse((await context.backend.get("analysis", "policy-active:v1")) ?? "null")).toMatchObject({ artifactId: v3.candidate.artifact.id, artifactHash: v3.candidate.artifact.artifactHash, activationHash: first.activationHash });
  });

  it("refuses missing or changed approval evidence without creating a candidate active pointer", async () => {
    const empty = await setup(), emptyExecutor = new TearFoundryV3PromotionExecutor(empty.vault, empty.custody);
    await expect(emptyExecutor.promote("0".repeat(16), "2026-08-08T00:03:00.000Z")).rejects.toThrow(/approval/u);
    expect(await empty.backend.get("analysis", "policy-active:v1")).toBeUndefined();

    const context = await setup(), v3 = v3Fixture(), candidates = new TearC34V3C32CandidateRegistry(context.backend); await candidates.register(v3.candidate.artifact);
    const bridge = await new TearFoundryV3MonitoringBridgeExecutor(context.vault, context.custody).bridge(context.job, { decisionReceiptHash: context.decision.receiptHash, monitoringReceiptHash: context.monitoring.receiptHash, offline: v3.offline, training: v3.training, online: v3.online, checkpoint: v3.checkpoint, evaluation: v3.evaluation, candidateArtifactId: v3.candidate.artifact.id, bridgedAt: "2026-08-08T00:01:00.000Z" });
    const approval = await new TearFoundryV3PromotionApprovalExecutor(context.vault, context.custody).approve(context.job, bridge.bridgeHash, "2026-08-08T00:02:00.000Z");
    await context.backend.put("analysis", `policy-artifact:v1:${v3.candidate.artifact.id}`, "corrupt");
    await expect(new TearFoundryV3PromotionExecutor(context.vault, context.custody).promote(approval.approvalHash, "2026-08-08T00:03:00.000Z")).rejects.toThrow(/candidate/u);
    expect(await context.backend.get("analysis", "policy-active:v1")).toBeUndefined();
    expect(await context.backend.get("analysis", `foundry-job-v3-promotion-receipt:v1:${approval.approvalHash}`)).toBeUndefined();
  });
});
