import { describe, expect, it } from "vitest";
import { createMemoryGhostVaultBackend } from "../../src/ghost";
import { TearFoundryExecutionBindingVault, TearFoundryJobScheduleVault, TearFoundryJobVault, TearFoundryScheduledExecution, createTearFoundryJob, createTearFoundryJobSchedule, type TearAcademyCandidateCustodyStore } from "../../src/agents";

const h = Object.freeze({ artifact: "a".repeat(16), corpus: "b".repeat(16), candidate: "c".repeat(16), evaluation: "d".repeat(16), reward: "e".repeat(16), invariant: "f".repeat(16), budget: "1".repeat(16), stop: "2".repeat(16), compute: "3".repeat(16), storage: "4".repeat(16) });
async function fixture(held = true) { const backend = createMemoryGhostVaultBackend(), jobs = new TearFoundryJobVault(backend), schedules = new TearFoundryJobScheduleVault(backend), job = createTearFoundryJob({ id: "scheduled-job", createdAt: "2026-08-08T00:00:00.000Z", reason: "authorized", inputs: { champion: { id: "champion", artifactHash: h.artifact }, corpusRecordHashes: [h.corpus], evaluationPlanHash: h.evaluation, rewardDefinitionHash: h.reward, invariantSetHash: h.invariant, budgetHash: h.budget, stopConditionsHash: h.stop } }); await jobs.persist(job); const enabled = createTearFoundryJobSchedule({ id: "scheduled", jobId: job.id, jobHash: job.jobHash, intervalMs: 60_000, computeBudgetHash: h.compute, storageBudgetHash: h.storage, stopConditionsHash: h.stop, state: "enabled", configuredAt: "2026-08-08T00:00:00.000Z" }); await schedules.persist(enabled); const custody = { backend: () => backend, held: () => Promise.resolve(held ? [{ candidateHash: h.candidate, recordHash: h.corpus }] : []), inventory: () => Promise.resolve({ records: [{ candidateHash: h.candidate, recordHash: h.corpus }], rejectedKeys: [] }) } as unknown as TearAcademyCandidateCustodyStore; const bindings = new TearFoundryExecutionBindingVault(jobs); await bindings.bindV3(enabled, job, { payload: { kind: "none" }, successorDeclaration: { kind: "exact-phase-payload", payload: { kind: "trainer-manifest", manifest: { id: "published", trainerId: "c36", version: 1 } }, nextDeclaration: { kind: "exact-phase-payload", payload: { kind: "offline-launch", offline: { training: { manifestId: "published", trainerId: "c36", manifestVersion: 1, plan: { id: "x", version: 1, seed: 1, reward: { components: [{ id: "score", source: "score.delta" as const, weight: 1, maximumSourceValue: 1, perTransitionCap: 1 }], totalMinimum: -1, totalMaximum: 1 }, limits: { maxTransitions: 1, maxEventsPerTransition: 1, maxRewardViolations: 0 } }, config: { epochs: 1, learningRate: .5, gamma: .5, maxStateActionEntries: 1, maxAbsoluteQ: 1, maxMeanAbsoluteTdError: 1, maxConsecutiveDivergentEpochs: 1 } }, manifest: { id: "published", trainerId: "c36", version: 1 }, manifestHash: "5".repeat(16), manifestRootHash: "6".repeat(16), datasetHash: "7".repeat(16), planHash: "8".repeat(16), configurationHash: "9".repeat(16), rewardHash: h.reward } }, nextDeclaration: { kind: "emitted-v2-training", nextDeclaration: { kind: "repeat-v2-training" } } } } }); return { backend, jobs, enabled: { schedule: enabled }, execution: new TearFoundryScheduledExecution(jobs, schedules, custody) }; }
describe("C36 bound one-shot scheduled execution", () => {
  it("uses only the persisted created binding, retries its own attempt, and leaves the successor schedule stale", async () => { const f = await fixture(), at = "2026-08-08T00:01:00.000Z", first = await f.execution.runScheduledOnce(f.enabled.schedule.scheduleHash, at, "one"); expect(first).toMatchObject({ phase: "created", scheduleHash: f.enabled.schedule.scheduleHash }); await expect(f.execution.runScheduledOnce(f.enabled.schedule.scheduleHash, at, "one")).resolves.toEqual(first); await expect(f.jobs.get("scheduled-job")).resolves.toMatchObject({ phase: "collecting" }); });
  it("refuses missing, preserves a revoked head, and admits one concurrent bound claimant", async () => { const missing = await fixture(); await expect(missing.execution.runScheduledOnce("f".repeat(16), "2026-08-08T00:01:00.000Z", "missing")).rejects.toThrow(/enabled/u); const revoked = await fixture(false); await expect(revoked.execution.runScheduledOnce(revoked.enabled.schedule.scheduleHash, "2026-08-08T00:01:00.000Z", "revoked")).resolves.toMatchObject({ phase: "created" }); await expect(revoked.jobs.get("scheduled-job")).resolves.toMatchObject({ phase: "created" }); const concurrent = await fixture(), values = await Promise.allSettled([concurrent.execution.runScheduledOnce(concurrent.enabled.schedule.scheduleHash, "2026-08-08T00:01:00.000Z", "one"), concurrent.execution.runScheduledOnce(concurrent.enabled.schedule.scheduleHash, "2026-08-08T00:01:00.000Z", "two")]); expect(values.filter((entry) => entry.status === "fulfilled")).toHaveLength(1); });
});
