import { describe, expect, it } from "vitest";
import { createMemoryGhostVaultBackend } from "../../src/ghost";
import { stableVerificationHash } from "../../src/replay/hash";
import { TearFoundryJobVault, TearFoundryScheduledExecution, TearFoundryV4OnlineLaunchAuthorityExecutor, createTearFoundryExecutionBindingV4, createTearFoundryJobSchedule, createTearFoundryJobV2, createTearFoundryLaunchProfile, transitionTearFoundryJob } from "../../src/agents";

const at = "2026-08-08T00:00:00.000Z", h = (value: string) => value.repeat(16);
async function fixture() {
  const backend = createMemoryGhostVaultBackend(), jobs = new TearFoundryJobVault(backend), created = createTearFoundryJobV2({ id: "v4-online-job", createdAt: at, reason: "authorized", inputs: { champion: { id: "champion", artifactHash: h("a") }, corpusRecordHashes: [h("b")], evaluationPlanHash: h("c"), rewardDefinitionHash: h("d"), invariantSetHash: h("e"), budgetHash: h("f"), stopConditionsHash: h("1"), evaluationProtocol: { version: 1, id: "frozen", thresholds: { minimumRewardGain: 0, requireCompletionRateNotLower: true, maxTicksPerCase: 10, maxAbsoluteRewardPerCase: 10 } } } }), collecting = transitionTearFoundryJob(created, "collecting", at, "collected"), curating = transitionTearFoundryJob(collecting, "curating", at, "curated"), training = transitionTearFoundryJob(curating, "training", at, "trained"), job = transitionTearFoundryJob(training, "evaluating", at, "offline complete"), schedule = createTearFoundryJobSchedule({ id: "v4-online-schedule", jobId: job.id, jobHash: job.jobHash, intervalMs: 60_000, computeBudgetHash: h("2"), storageBudgetHash: h("3"), stopConditionsHash: h("1"), state: "enabled", configuredAt: at }), protocol = created.inputs.evaluationProtocol;
  if (protocol === undefined) throw new Error("fixture lost evaluation protocol");
  await jobs.persist(job);
  await backend.put("analysis", `foundry-job-schedule:v1:${schedule.id}`, JSON.stringify(schedule));
  const profile = createTearFoundryLaunchProfile({ id: "v4-online-profile", jobId: job.id, reason: "authorized", declaredAt: at, manifest: { id: "manifest", trainerId: "trainer", version: 1, manifestHash: h("4"), rootHash: h("5") }, schedule: { id: schedule.id, intervalMs: schedule.intervalMs, computeBudgetHash: schedule.computeBudgetHash, storageBudgetHash: schedule.storageBudgetHash }, inputs: { evaluationPlanHash: created.inputs.evaluationPlanHash, rewardDefinitionHash: created.inputs.rewardDefinitionHash, invariantSetHash: created.inputs.invariantSetHash, budgetHash: created.inputs.budgetHash, stopConditionsHash: created.inputs.stopConditionsHash, evaluationProtocol: protocol }, successorDeclaration: { kind: "exact-phase-payload", payload: { kind: "trainer-manifest", manifest: { id: "manifest", trainerId: "trainer", version: 1 } }, nextDeclaration: { kind: "exact-phase-payload", payload: { kind: "offline-launch", offline: { training: { manifestId: "manifest", trainerId: "trainer", manifestVersion: 1, plan: { id: "offline", version: 1, seed: 1, reward: { components: [{ id: "score", source: "score.delta", weight: 1, maximumSourceValue: 1, perTransitionCap: 1 }], totalMinimum: -1, totalMaximum: 1 }, limits: { maxTransitions: 1, maxEventsPerTransition: 1, maxRewardViolations: 0 } }, config: { epochs: 1, learningRate: .5, gamma: .5, maxStateActionEntries: 1, maxAbsoluteQ: 1, maxMeanAbsoluteTdError: 1, maxConsecutiveDivergentEpochs: 1 } }, manifest: { id: "manifest", trainerId: "trainer", version: 1 }, manifestHash: h("4"), manifestRootHash: h("5"), datasetHash: h("6"), planHash: h("7"), configurationHash: h("8"), rewardHash: created.inputs.rewardDefinitionHash } }, nextDeclaration: { kind: "emitted-v2-training", nextDeclaration: { kind: "repeat-v2-training" } } } } });
  await backend.put("analysis", `foundry-launch-profile:v1:${profile.id}`, JSON.stringify(profile));
  const bootstrapDraft = { format: "tear-foundry-bootstrap-receipt" as const, schemaVersion: 1 as const, jobHash: created.jobHash, manifestHash: profile.manifest.manifestHash, manifestRootHash: profile.manifest.rootHash, scheduleHash: schedule.scheduleHash, bindingHash: h("6"), bootstrappedAt: at }, bootstrap = Object.freeze({ ...bootstrapDraft, receiptHash: stableVerificationHash(bootstrapDraft) });
  await backend.put("analysis", `foundry-job-bootstrap:v1:${h("7")}`, JSON.stringify(bootstrap));
  const readinessDraft = { format: "tear-foundry-evaluation-readiness-receipt" as const, schemaVersion: 1 as const, job: { id: job.id, sourceJobHash: created.jobHash, resultJobHash: job.jobHash }, finalizedAt: at, disposition: "evaluation-ready" as const, launchHash: h("8"), receiptHash: h("9"), checkpointHash: h("0"), trainingHash: h("a") }, readiness = Object.freeze({ ...readinessDraft, receiptHashValue: stableVerificationHash(readinessDraft) });
  await backend.put("analysis", `foundry-job-evaluation-ready:v1:${readiness.receiptHashValue}`, JSON.stringify(readiness));
  const source = createTearFoundryExecutionBindingV4({ schedule: { id: schedule.id, revision: schedule.revision, scheduleHash: schedule.scheduleHash }, job: { id: job.id, jobHash: job.jobHash, phase: job.phase }, payload: { kind: "evaluation-ready" } });
  await backend.put("analysis", `foundry-job-execution-binding:v4:${source.bindingHash}`, JSON.stringify(source)); await backend.put("analysis", `foundry-job-execution-binding-current:v4:${schedule.id}:${String(schedule.revision)}:${schedule.scheduleHash}`, source.bindingHash);
  await backend.put("analysis", "academy-candidate-custody:v1:candidate", "held"); let held = true;
  const custody = { backend: () => backend, held: () => Promise.resolve(held ? [{ candidateHash: "candidate", recordHash: h("b") }] : []), inventory: () => Promise.resolve({ records: [{ candidateHash: "candidate", recordHash: h("b") }], rejectedKeys: [] }) } as never;
  const input = { profile, bootstrap, schedule, job, readiness, request: { curriculum: { id: "online", version: 1, seed: 1, stages: [] }, config: { maxIterations: 1 } } as never, declaredAt: at };
  return { backend, jobs, custody, input, setHeld: (value: boolean) => { held = value; } };
}
describe("C36 V4 online-launch authority", () => {
  it("atomically hands exact evaluation readiness to an opaque no-execution V4 payload and retries itself", async () => {
    const f = await fixture(), executor = new TearFoundryV4OnlineLaunchAuthorityExecutor(f.jobs, f.custody), first = await executor.declare(f.input), retry = await executor.declare(f.input);
    expect(first.binding.payload).toMatchObject({ kind: "online-launch-ready", authorityHash: first.authority.authorityHash, handoffReceiptHash: first.receipt.receiptHash }); expect(retry).toEqual(first);
    const scheduled = new TearFoundryScheduledExecution(f.jobs, { list: () => Promise.resolve([f.input.schedule]) } as never, f.custody);
    await expect(scheduled.runScheduledOnce(f.input.schedule.scheduleHash, "2026-08-08T00:01:00.000Z", "retain-only")).resolves.toMatchObject({ bindingHash: first.binding.bindingHash }); expect((await f.backend.keys("analysis")).some((key) => key.startsWith("foundry-job-online-training-launch:v1:"))).toBe(false);
  });
  it("fails closed when custody, profile, readiness, or current V4 source authority changes", async () => {
    const cases = ["custody", "profile", "readiness", "source"] as const;
    for (const kind of cases) { const f = await fixture(); if (kind === "custody") f.setHeld(false); if (kind === "profile") await f.backend.put("analysis", `foundry-launch-profile:v1:${f.input.profile.id}`, "rewritten"); if (kind === "readiness") await f.backend.put("analysis", `foundry-job-evaluation-ready:v1:${f.input.readiness.receiptHashValue}`, "rewritten"); if (kind === "source") await f.backend.put("analysis", `foundry-job-execution-binding-current:v4:${f.input.schedule.id}:${String(f.input.schedule.revision)}:${f.input.schedule.scheduleHash}`, h("f")); await expect(new TearFoundryV4OnlineLaunchAuthorityExecutor(f.jobs, f.custody).declare(f.input)).rejects.toThrow(/authority|custody|binding|profile|readiness/u); expect((await f.backend.keys("analysis")).some((key) => key.startsWith("foundry-job-v4-online-launch-authority:v1:"))).toBe(false); }
  });
});
