import { describe, expect, it } from "vitest";
import { createMemoryGhostVaultBackend } from "../../src/ghost";
import { stableVerificationHash } from "../../src/replay/hash";
import { TearFoundryExecutionBindingVault, TearFoundryJobScheduleVault, TearFoundryJobVault, TearFoundryScheduledExecution, createTearFoundryJob, createTearFoundryJobSchedule, createTearOfflineRlPlan, type TearAcademyCandidateCustodyStore, type TearAcademyCorpusStore, type TearAcademyTrainingDatasetLoader, type TearAcademyTrainingDatasetV1 } from "../../src/agents";

const h = Object.freeze({ artifact: "a".repeat(16), corpus: "b".repeat(16), candidate: "c".repeat(16), evaluation: "d".repeat(16), reward: "e".repeat(16), invariant: "f".repeat(16), budget: "1".repeat(16), stop: "2".repeat(16), compute: "3".repeat(16), storage: "4".repeat(16) });
async function fixture(held = true) { const backend = createMemoryGhostVaultBackend(), jobs = new TearFoundryJobVault(backend), schedules = new TearFoundryJobScheduleVault(backend), job = createTearFoundryJob({ id: "scheduled-job", createdAt: "2026-08-08T00:00:00.000Z", reason: "authorized", inputs: { champion: { id: "champion", artifactHash: h.artifact }, corpusRecordHashes: [h.corpus], evaluationPlanHash: h.evaluation, rewardDefinitionHash: h.reward, invariantSetHash: h.invariant, budgetHash: h.budget, stopConditionsHash: h.stop } }); await jobs.persist(job); const enabled = createTearFoundryJobSchedule({ id: "scheduled", jobId: job.id, jobHash: job.jobHash, intervalMs: 60_000, computeBudgetHash: h.compute, storageBudgetHash: h.storage, stopConditionsHash: h.stop, state: "enabled", configuredAt: "2026-08-08T00:00:00.000Z" }); await schedules.persist(enabled); const custody = { backend: () => backend, held: () => Promise.resolve(held ? [{ candidateHash: h.candidate, recordHash: h.corpus }] : []), inventory: () => Promise.resolve({ records: [{ candidateHash: h.candidate, recordHash: h.corpus }], rejectedKeys: [] }) } as unknown as TearAcademyCandidateCustodyStore; const bindings = new TearFoundryExecutionBindingVault(jobs); await bindings.bindV3(enabled, job, { payload: { kind: "none" }, successorDeclaration: { kind: "exact-phase-payload", payload: { kind: "trainer-manifest", manifest: { id: "published", trainerId: "c36", version: 1 } }, nextDeclaration: { kind: "exact-phase-payload", payload: { kind: "offline-launch", offline: { training: { manifestId: "published", trainerId: "c36", manifestVersion: 1, plan: { id: "x", version: 1, seed: 1, reward: { components: [{ id: "score", source: "score.delta" as const, weight: 1, maximumSourceValue: 1, perTransitionCap: 1 }], totalMinimum: -1, totalMaximum: 1 }, limits: { maxTransitions: 1, maxEventsPerTransition: 1, maxRewardViolations: 0 } }, config: { epochs: 1, learningRate: .5, gamma: .5, maxStateActionEntries: 1, maxAbsoluteQ: 1, maxMeanAbsoluteTdError: 1, maxConsecutiveDivergentEpochs: 1 } }, manifest: { id: "published", trainerId: "c36", version: 1 }, manifestHash: "5".repeat(16), manifestRootHash: "6".repeat(16), datasetHash: "7".repeat(16), planHash: "8".repeat(16), configurationHash: "9".repeat(16), rewardHash: h.reward } }, nextDeclaration: { kind: "emitted-v2-training", nextDeclaration: { kind: "repeat-v2-training" } } } } }); return { backend, jobs, enabled: { schedule: enabled }, execution: new TearFoundryScheduledExecution(jobs, schedules, custody) }; }
describe("C36 bound one-shot scheduled execution", () => {
  it("uses only the persisted created binding, retries its own attempt, and leaves the successor schedule stale", async () => { const f = await fixture(), at = "2026-08-08T00:01:00.000Z", first = await f.execution.runScheduledOnce(f.enabled.schedule.scheduleHash, at, "one"); expect(first).toMatchObject({ phase: "created", scheduleHash: f.enabled.schedule.scheduleHash }); await expect(f.execution.runScheduledOnce(f.enabled.schedule.scheduleHash, at, "one")).resolves.toEqual(first); await expect(f.jobs.get("scheduled-job")).resolves.toMatchObject({ phase: "collecting" }); });
  it("refuses missing, preserves a revoked head, and admits one concurrent bound claimant", async () => { const missing = await fixture(); await expect(missing.execution.runScheduledOnce("f".repeat(16), "2026-08-08T00:01:00.000Z", "missing")).rejects.toThrow(/enabled/u); const revoked = await fixture(false); await expect(revoked.execution.runScheduledOnce(revoked.enabled.schedule.scheduleHash, "2026-08-08T00:01:00.000Z", "revoked")).resolves.toMatchObject({ phase: "created" }); await expect(revoked.jobs.get("scheduled-job")).resolves.toMatchObject({ phase: "created" }); const concurrent = await fixture(), values = await Promise.allSettled([concurrent.execution.runScheduledOnce(concurrent.enabled.schedule.scheduleHash, "2026-08-08T00:01:00.000Z", "one"), concurrent.execution.runScheduledOnce(concurrent.enabled.schedule.scheduleHash, "2026-08-08T00:01:00.000Z", "two")]); expect(values.filter((entry) => entry.status === "fulfilled")).toHaveLength(1); });

  it("continues a bootstrapped V3 declaration through collection, manifest admission, offline launch, and resumed training", async () => {
    const backend = createMemoryGhostVaultBackend(), jobs = new TearFoundryJobVault(backend), schedules = new TearFoundryJobScheduleVault(backend);
    const scenario = Object.freeze({ format: "tear-contract" as const, kind: "scenario" as const, schemaVersion: 1 as const, id: "scheduled-v3", version: 1, description: "scheduled V3 lifecycle", stateClass: "recorded-canonical" as const, executionClass: "training" as const, seed: "scheduled-v3", start: Object.freeze({ mode: "endless" as const, difficulty: "normal" as const, weapon: "sword" as const }), maxTicks: 4, assertions: Object.freeze(["runtime.finite-state"] as const), tags: Object.freeze(["c36"] as const) });
    const states = [0, 1].map((tick) => Object.freeze({ tick, input: {} as never, run: Object.freeze({ mode: "endless", wave: 1, score: tick, time: tick, seed: 1 }), player: Object.freeze({ x: 0, y: 0, vx: 0, vy: 0, hp: 100 }), blade: Object.freeze({ state: "held", x: 0, y: 0, vx: 0, vy: 0 }), enemies: Object.freeze([]) }));
    const dataset = Object.freeze({ format: "tear-academy-training-dataset", schemaVersion: 1, manifest: Object.freeze({ id: "published", version: 1, manifestHash: "5".repeat(16), rootHash: "6".repeat(16) }), sequences: Object.freeze([Object.freeze({ candidateHash: h.candidate, split: "training", lessonId: "movement-foundations", segmentKind: "demonstration", tags: Object.freeze([]), sourceScenario: scenario, tracks: Object.freeze({ observations: Object.freeze(states), actions: Object.freeze([Object.freeze({ kind: "command" as const, id: 1, tick: 1, command: Object.freeze({ type: "move" as const, x: 1_000, y: 0 }) })]), nativeEvents: Object.freeze([]), rewardComponents: Object.freeze(states.map((entry) => Object.freeze({ tick: entry.tick, value: null }))), intents: Object.freeze([]), terminal: Object.freeze({ tick: 1, semanticHash: stableVerificationHash(states[1]), terminated: true, truncated: false }) }) as never, sequenceHash: "7".repeat(16) })]), observationCount: 2, actionCount: 1, datasetHash: "8".repeat(16) }) satisfies TearAcademyTrainingDatasetV1;
    const training = Object.freeze({ manifestId: "published", trainerId: "c36", manifestVersion: 1, plan: { id: "scheduled-v3", version: 1, seed: 1, reward: { components: [{ id: "score", source: "score.delta" as const, weight: 1, maximumSourceValue: 10, perTransitionCap: 10 }], totalMinimum: -10, totalMaximum: 10 }, limits: { maxTransitions: 4, maxEventsPerTransition: 4, maxRewardViolations: 0 as const } }, config: { epochs: 2, learningRate: .5, gamma: .9, maxStateActionEntries: 10, maxAbsoluteQ: 10, maxMeanAbsoluteTdError: 10, maxConsecutiveDivergentEpochs: 2 } });
    const plan = createTearOfflineRlPlan(dataset, training.plan), manifest = Object.freeze({ id: "published", reader: Object.freeze({ kind: "trainer" as const, id: "c36" }), version: 1, manifestHash: dataset.manifest.manifestHash, rootHash: dataset.manifest.rootHash, entries: Object.freeze([{ custodyRecordHash: h.corpus, split: "training" as const, entryHash: "9".repeat(16) }]) });
    let held = true;
    const custody = { backend: () => backend, held: () => Promise.resolve(held ? [{ candidateHash: h.candidate, recordHash: h.corpus }] : []), inventory: () => Promise.resolve({ records: [{ candidateHash: h.candidate, recordHash: h.corpus }], rejectedKeys: [] }) } as unknown as TearAcademyCandidateCustodyStore;
    const corpus = { backend: () => backend, getManifest: () => Promise.resolve(manifest) } as unknown as TearAcademyCorpusStore;
    const loader = { load: () => Promise.resolve(dataset) } as unknown as TearAcademyTrainingDatasetLoader;
    const job = createTearFoundryJob({ id: "scheduled-v3-job", createdAt: "2026-08-08T00:00:00.000Z", reason: "frozen V3 fixture", inputs: { champion: { id: "champion", artifactHash: h.artifact }, corpusRecordHashes: [h.corpus], evaluationPlanHash: h.evaluation, rewardDefinitionHash: plan.reward.rewardHash, invariantSetHash: h.invariant, budgetHash: h.budget, stopConditionsHash: h.stop } });
    await jobs.persist(job);
    const schedule = createTearFoundryJobSchedule({ id: "scheduled-v3", jobId: job.id, jobHash: job.jobHash, intervalMs: 60_000, computeBudgetHash: h.compute, storageBudgetHash: h.storage, stopConditionsHash: h.stop, state: "enabled", configuredAt: "2026-08-08T00:00:00.000Z" });
    await schedules.persist(schedule);
    const offline = Object.freeze({ kind: "offline-launch" as const, offline: Object.freeze({ training, manifest: Object.freeze({ id: manifest.id, trainerId: manifest.reader.id, version: manifest.version }), manifestHash: manifest.manifestHash, manifestRootHash: manifest.rootHash, datasetHash: dataset.datasetHash, planHash: plan.planHash, configurationHash: stableVerificationHash(training.config), rewardHash: plan.reward.rewardHash }) });
    await new TearFoundryExecutionBindingVault(jobs).bindV3(schedule, job, { payload: { kind: "none" }, successorDeclaration: { kind: "exact-phase-payload", payload: { kind: "trainer-manifest", manifest: { id: manifest.id, trainerId: manifest.reader.id, version: manifest.version } }, nextDeclaration: { kind: "exact-phase-payload", payload: offline, nextDeclaration: { kind: "emitted-v2-training", nextDeclaration: { kind: "repeat-v2-training" } } } } });
    const execute = () => new TearFoundryScheduledExecution(jobs, schedules, custody, corpus, loader);
    const at = (minute: number) => `2026-08-08T00:0${String(minute)}:00.000Z`;
    const current = async () => (await schedules.list()).find((entry) => entry.id === schedule.id) ?? (() => { throw new Error("current schedule missing"); })();
    await expect(execute().runScheduledOnce(schedule.scheduleHash, at(1), "collect")).resolves.toMatchObject({ phase: "created" });
    expect(await jobs.get(job.id)).toMatchObject({ phase: "collecting" });
    const collecting = await current(); held = false;
    await expect(execute().runScheduledOnce(collecting.scheduleHash, at(2), "revoked-after-restart")).rejects.toThrow(/not due|custody/u);
    expect(await jobs.get(job.id)).toMatchObject({ phase: "collecting" }); held = true;
    await expect(execute().runScheduledOnce(collecting.scheduleHash, at(2), "curate")).resolves.toMatchObject({ phase: "collecting" });
    expect(await jobs.get(job.id)).toMatchObject({ phase: "curating" });
    const curating = await current();
    await expect(execute().runScheduledOnce(curating.scheduleHash, at(3), "launch")).resolves.toMatchObject({ phase: "curating" });
    expect(await jobs.get(job.id)).toMatchObject({ phase: "training" });
    const trainingSchedule = await current();
    await expect(execute().runScheduledOnce(trainingSchedule.scheduleHash, at(4), "resume")).resolves.toMatchObject({ phase: "training" });
    const resumed = await jobs.get(job.id); expect(resumed).toMatchObject({ phase: "training" }); expect(resumed?.events).toHaveLength(5);
    expect((await backend.keys("analysis")).some((key) => key.startsWith("policy-"))).toBe(false);
  });
});
