import { describe, expect, it } from "vitest";
import { GhostLocalPublicationJobs, GhostLocalPublicationConsentLedger, GhostPublicationTransport, GhostStreamingRecorder, GhostLocalVault, createMemoryGhostVaultBackend } from "../../src/ghost";
import type { GhostPublicationBearerPort } from "../../src/platform/firebase-publication-bearer";

const consent = Object.freeze({ format: "tear-academy-consent" as const, schemaVersion: 1 as const, revision: "transport", decidedAt: "2026-08-09T00:00:00.000Z", localRecording: "granted" as const, cloudPublication: "granted" as const, analytics: "denied" as const, modelTraining: "no-training" as const });
const now = "2026-08-09T00:01:00.000Z";
async function fixture() { const backend = createMemoryGhostVaultBackend(), vault = new GhostLocalVault(backend), recorder = new GhostStreamingRecorder({ sessionId: "transport-capsule", createdAt: now, vault, chunkEntries: 1, maxPendingWrites: 1 }); await recorder.start(); await recorder.append({ kind: "commands", tick: 1, value: { command: "move" } }); await recorder.finalize(now); const ledger = new GhostLocalPublicationConsentLedger(backend), publicationConsent = await ledger.decide({ subject: "signed-in-player", isAnonymous: false }, { revision: 1, cloudPublication: "granted", decidedAt: now }), jobs = new GhostLocalPublicationJobs(vault, ledger); const job = await jobs.enqueue({ capsuleId: "transport-capsule", createdAt: now, partBytes: 4, custody: { consent, publicationConsent, privacy: "pseudonymous", visibility: "private", eligibility: { resumed: false, modded: false, coached: false, ghostAssisted: false, bot: false, debug: false, stateForge: false }, decidedAt: now } }); return { backend, vault, jobs, job }; }
function bearer(input: { fail?: boolean } = {}): GhostPublicationBearerPort { return { acquireAuthorization() { return input.fail ? Promise.reject(new Error("firebase-user-unavailable")) : Promise.resolve({ authorization: "Bearer fresh" }); } }; }
function requestUrl(url: string | URL | Request): string { return url instanceof Request ? url.url : url instanceof URL ? url.href : url; }
function worker(input: { failPart?: boolean; changedEtag?: boolean } = {}) { const etags = new Map<number, string>(); const requests: string[] = []; const fetch = ((url: string | URL | Request, init?: RequestInit) => { const path = new URL(requestUrl(url)).pathname; requests.push(`${init?.method ?? "GET"} ${path}`); if (path === "/v1/uploads") return Promise.resolve(Response.json({ capsuleId: "transport-capsule", uploadId: "upload", status: "uploading" }, { status: 201 })); if (path === "/v1/uploads/transport-capsule") return Promise.resolve(Response.json({ capsuleId: "transport-capsule", status: "uploading", byteLength: undefined, partCount: undefined, parts: [...etags].map(([partNumber, etag]) => ({ partNumber, etag: input.changedEtag ? `${etag}-changed` : etag })) })); const match = /parts\/(\d+)$/u.exec(path); if (match) { if (input.failPart) return Promise.resolve(Response.json({ error: "down" }, { status: 503 })); const n = Number(match[1]); etags.set(n, `etag-${String(n)}`); return Promise.resolve(Response.json({ partNumber: n, etag: `etag-${String(n)}` }, { status: 201 })); } if (path.endsWith("/complete")) return Promise.resolve(Response.json({ capsuleId: "transport-capsule", status: "finalized", verification: "verified", etag: "object-etag" })); if (path.endsWith("/abort")) return Promise.resolve(Response.json({ capsuleId: "transport-capsule", status: "deleted", aborted: true })); return Promise.resolve(Response.json({ error: "missing" }, { status: 404 })); }) as typeof globalThis.fetch; return { fetch, requests, etags }; }

describe("C38 foreground publication transport", () => {
  it("uses fresh bearer actions and persists only bounded completion metadata", async () => { const f = await fixture(), w = worker(); const transport = new GhostPublicationTransport({ endpoint: "https://publication.test", fetch: async (url, init) => { const response = await w.fetch(url, init); if (new URL(requestUrl(url)).pathname === "/v1/uploads/transport-capsule") { return Response.json({ capsuleId: "transport-capsule", status: "uploading", byteLength: f.job.workerManifest.byteLength, partCount: f.job.workerManifest.partCount, parts: [...w.etags].map(([partNumber, etag]) => ({ partNumber, etag })) }); } return response; }, bearer: bearer(), jobs: f.jobs, vault: f.vault }); const state = await transport.runOnce(f.job.id, now); expect(state.terminal).toBe("finalized"); expect(state.etags).toHaveLength(f.job.transfer.parts.length); expect(w.requests.some((x) => x.startsWith("PUT "))).toBe(true); const raw = await f.backend.get("analysis", `ghost-publication-transport:v1:${f.job.id}`); expect(raw).not.toContain("Bearer"); expect(raw).not.toContain("commands"); });

  it("backs off transient transport failure without starting a timer, and fails closed on signout", async () => { const f = await fixture(), w = worker({ failPart: true }); const transport = new GhostPublicationTransport({ endpoint: "https://publication.test", fetch: async (url, init) => { const path = new URL(requestUrl(url)).pathname; if (path === "/v1/uploads/transport-capsule") return Response.json({ capsuleId: "transport-capsule", status: "uploading", byteLength: f.job.workerManifest.byteLength, partCount: f.job.workerManifest.partCount, parts: [] }); return w.fetch(url, init); }, bearer: bearer(), jobs: f.jobs, vault: f.vault }); const first = await transport.runOnce(f.job.id, now); expect(first.retryAt).toBeDefined(); expect(await transport.runOnce(f.job.id, now)).toEqual(first); const g = await fixture(), signedOut = new GhostPublicationTransport({ endpoint: "https://publication.test", fetch: w.fetch, bearer: bearer({ fail: true }), jobs: g.jobs, vault: g.vault }); expect((await signedOut.runOnce(g.job.id, now)).terminal).toBe("failed"); });
});
