import { describe, expect, it } from "vitest";
import { compareTearBotHumanLikeness, createTearBotHumanLikenessThresholds, createTearHumanCalibrationDistribution, type TearHumanCalibrationSourceReceiptV1, type TearBotV3CanonicalEvaluationReportV1 } from "../../src/agents";
import { stableVerificationHash } from "../../src/replay/hash";

function receipt(participantId: string): TearHumanCalibrationSourceReceiptV1 { const draft = { format: "tearbot-human-calibration-source" as const, schemaVersion: 1 as const, participantId, issuerId: "test", consentHash: "a".repeat(16), capsule: { id: participantId, rootIntegrity: "b".repeat(16), fromTick: 0, toTick: 4, actionHash: "c".repeat(16), replayContextHash: "d".repeat(16) }, features: { commandCount: 4, activeCommandCount: 2, activeCommandRate: .5, meanInterCommandTicks: 2, maximumInterCommandTicks: 2 } }; return Object.freeze({ ...draft, receiptHash: stableVerificationHash(draft) }); }
function evaluation(): TearBotV3CanonicalEvaluationReportV1 { const provenance = { approvalHash: "1".repeat(16), promotionReceiptHash: "2".repeat(16), artifactId: "promoted-v3", artifactHash: "3".repeat(16), activationHash: "4".repeat(16), candidatePayloadHash: "5".repeat(16) }, decisions = [{ tick: 0, stateHash: "6".repeat(16), semanticActionHash: "7".repeat(16), actionCount: 1, source: "artifact" as const, artifactId: provenance.artifactId, artifactHash: provenance.artifactHash, activationHash: provenance.activationHash }, { tick: 2, stateHash: "8".repeat(16), semanticActionHash: "9".repeat(16), actionCount: 1, source: "artifact" as const, artifactId: provenance.artifactId, artifactHash: provenance.artifactHash, activationHash: provenance.activationHash }], episode = { caseId: "held-out", scenarioHash: "a".repeat(16), freshWorldOrdinal: 1, terminal: { tick: 2, semanticHash: "b".repeat(16), terminated: true, truncated: false }, decisions, eventHash: "c".repeat(16) }, draft = { format: "tearbot-v3-canonical-evaluation-report" as const, schemaVersion: 1 as const, planHash: "d".repeat(16), provenance, episodes: [episode], distribution: { episodes: 1, completionRate: 1, meanTicks: 2, maxTicksPerCase: 3 }, placement: "unassigned" as const, humanCalibration: "not-compared" as const }; return Object.freeze({ ...draft, reportHash: stableVerificationHash(draft) }); }
const thresholds = () => createTearBotHumanLikenessThresholds({ maximumMeanTraceCommandCountDifference: 10, maximumActiveCommandRateDifference: 1, maximumMeanInterCommandTicksDifference: 10, maximumMeanMaximumInterCommandTicksDifference: 10 });

describe("C35 held-out human-likeness comparison", () => {
  it("compares only hash-bound 30-participant calibration and exact promoted canonical evaluation without certifying", () => { const distribution = createTearHumanCalibrationDistribution(Array.from({ length: 30 }, (_, index) => receipt(`p-${String(index)}`))), report = compareTearBotHumanLikeness({ distribution, evaluation: evaluation(), thresholds: thresholds() }); expect(report).toMatchObject({ status: "compared-not-certified", subject: "promoted-v3-canonical-non-omega", placement: "unassigned", certification: "not-certified", calibrationDistributionHash: distribution.distributionHash }); expect(report.comparison?.candidate.meanTraceCommandCount).toBe(2); expect(report.comparison?.withinFrozenThresholds).toBe(true); });
  it("fails closed for altered evidence, short populations, Omega, and no-action evaluations", () => { const distribution = createTearHumanCalibrationDistribution(Array.from({ length: 30 }, (_, index) => receipt(`p-${String(index)}`))), altered = { ...distribution, metrics: { ...distribution.metrics, meanTraceCommandCount: 999 } }; expect(compareTearBotHumanLikeness({ distribution: altered, evaluation: evaluation(), thresholds: thresholds() }).status).toBe("insufficient-evidence"); expect(compareTearBotHumanLikeness({ distribution, evaluation: evaluation(), thresholds: thresholds(), subject: "level-omega" }).reason).toBe("omega-excluded"); const short = { ...distribution, participantCount: 29, sourceReceiptHashes: distribution.sourceReceiptHashes.slice(0, 29) }, { distributionHash: ignoredDistributionHash, ...shortDraft } = short, shortHash = { ...short, distributionHash: stableVerificationHash(shortDraft) }; void ignoredDistributionHash; expect(compareTearBotHumanLikeness({ distribution: shortHash, evaluation: evaluation(), thresholds: thresholds() }).reason).toBe("insufficient-participants"); const report = evaluation(), noActions = { ...report, episodes: report.episodes.map((entry) => ({ ...entry, decisions: entry.decisions.map((decision) => ({ ...decision, actionCount: 0 })) })) }, { reportHash: ignoredReportHash, ...noActionDraft } = noActions, noActionReport = { ...noActions, reportHash: stableVerificationHash(noActionDraft) }; void ignoredReportHash; expect(compareTearBotHumanLikeness({ distribution, evaluation: noActionReport, thresholds: thresholds() }).reason).toBe("no-canonical-decisions"); });
});
